### ISSUE TITLE
Identity Server 

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/core#1]
Move authentication to Identity Server when it goes RTM. 

https://identityserver.io/

**Comment by jcgillespie** [comment]
Just curious, what do you mean by RTM and which packages? IdentityServer4 went to 1.0 at the end of December. https://www.nuget.org/packages/IdentityServer4/

**Comment by kspearrin** [comment]
That's what I meant. I have already started this work and everything will be switched over to it starting with the next releases.

**Comment by kspearrin** [comment]
This is done.
