### ISSUE TITLE
drag and drop into folder

### ISSUE THREAD

**Issue by rggjan** [bitwarden/core#100]
Would be great to be able to drag and drop logins in "My Vault" in the browser from one folder to another, to simplify sorting...

**Comment by kspearrin** [comment]
Please open in the appropriate repository. This doesn’t seem related to core.

**Comment by rggjan** [comment]
Oh, sorry Kyle... I didn't notice there were multiple repositories. Moved to https://github.com/bitwarden/web/issues/110
