### ISSUE TITLE
Core manual deploy

### ISSUE THREAD

**Issue by artur** [bitwarden/core#103]
Hi guys, I noticed that you are using docker core container, but how can I create my own ? I though the compilation would create it, but only API and Identity were used.

Or am I missing something ?

**Comment by kspearrin** [comment]
It is possible, but there is currently no documented path for deploying outside Docker. You'd need to be familiar with .NET Core publishing to figure it out.

**Comment by displaycard** [comment]
hi @kspearrin thanks for the quick answer, do you have some tips that could be useful when researching this ?

**Comment by artur** [comment]
Hi @kspearrin thanks for the quick answer, that's unfortunate, could point me out some useful resources regarding this ?

**Comment by kspearrin** [comment]
It really depends on what you're trying to deploy to. Just look at what the build.sh scripts for each project in the solution do for bundling the docker images. Those are all the different pieces.

**Comment by artur** [comment]
I might be confusing something, but src/Core doesn't contain any build.sh, do I need to nitpick from the others build.sh and build my own for src/Core ?

**Comment by kspearrin** [comment]
src/Core is only a class library. Look at src/Api and src/Identity

**Comment by artur** [comment]
Hum... Ok, but why then you have a docker container named bitwarden/core ? That's the thing that's confusing me

**Comment by kspearrin** [comment]
> Hum... Ok, but why then you have a docker container named bitwarden/core ? That's the thing that's confusing me

But there's not....

**Comment by artur** [comment]
Hum... maybe i'm confusing it with the bitwarden/setup, is this related to the installation ?

**Comment by kspearrin** [comment]
Yes, that is the installer that setups things up and also performs updates.
