### ISSUE TITLE
Session expired right after the login

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [bitwarden/core#105]
![2017-10-19_10-49-16](https://user-images.githubusercontent.com/897428/31759791-39afa720-b4bb-11e7-9735-7a800140cec9.png)

The server responses with 401 error on /api/accounts/profile

```
cf-ray:3b0225f408a26f84-SIN
content-length:0
date:Thu, 19 Oct 2017 07:50:45 GMT
server:cloudflare-nginx
server-version:1.12.1
status:401
www-authenticate:Bearer error="invalid_token", error_description="The signature key was not found"
```

**Comment by kspearrin** [comment]
Sounds like you have a configuration issue with identity server. Was this installed with our standard installer?

**Comment by Snowrisk** [comment]
Hi. I have the same problem. I'm running it at Docker.
Where do i find the log files?

**Comment by kspearrin** [comment]
./bwdata/core/logs

**Comment by Snowrisk** [comment]
Can't find /logs :
![grafik](https://user-images.githubusercontent.com/7990156/34385965-96de21e6-eb26-11e7-918b-7fba2a4b0a16.png)
