### ISSUE TITLE
No Domain leads to domain '-letsencrypt'

### ISSUE THREAD

**Issue by lroellin** [bitwarden/core#106]
Hi

I installed the docker image with ./bitwarden.sh install and then start. I did NOT provide a domain and didn't want Let's Encrypt, since I wanted it to just be reachable via IP.

However, the domain is now set to `-letsencrypt`, so when I connect to `http://123.123.123.123` (obviously redacted), I get redirected to `https://-letsencrypt`.

**Comment by kspearrin** [comment]
The installer will break in uncertain ways if you do not provide a domain. You should use "localhost" if you are just testing.

**Comment by kspearrin** [comment]
P.S. I'd recommend just deleting the `./bwdata` directory and starting over with the install since your config files are now messed up.

**Comment by kspearrin** [comment]
Safeguarded against with https://github.com/bitwarden/core/commit/0e247b711d0718173bf301f707517e20a7cb97ea
