### ISSUE TITLE
Enterprise Licence / Open Source / Self Hosted

### ISSUE THREAD

**Issue by christianreiss** [bitwarden/core#107]
Hey folks,

First off again Kudos for awesome fork. The docker deployment is working like a charm and we (non profit, read: Family) using it avidly.  It's pure bliss. Now, please read the following sentence knowing I am on your side trying to support: Browsing the code on github especially VerifyLicense, UserLicense et all I was wondering what someone would keep making a fork and simply removing all requirements for licenses for the premium things? 

I can imagine that larger scale deployments would rather invest a few hours or code hacking to remove those restraints and still net a profit compared to the license costs. 

Would, for self hosted versions, a donation button not make more sense? If people can simply comment out some lines of code and bypass any paywalls compared to volunarily donating money... well. I can see both sides, really.

-Chris.

**Comment by kspearrin** [comment]
Hey Chris,
Thanks for the feedback. As you know, we just released the self-hosting features. This work was primarily expedited for commercial business use. As such, all of our billing around this feature was built with this in mind. At least for now.

While it would be a pretty crappy thing to do, it is entirely possible for someone to fork the codebase and remove our licensing code. It's just part of being open source and if someone is that determined we're ok with that. They probably would not have ever paid us for the product in the first place. However, you're now on your own and in the business of maintaining that fork if you want to continue to receive important future updates, which I would consider rather critical with a product like bitwarden.

That said, we understand that people also may want to use the self-hosted solution to share with family and friends as well. We currently don't have a payment option set up for this type of use yet, but we are certainly evaluating these options and hope to have something available soon.

**Comment by christianreiss** [comment]
... and I feel crappy by just mentioning it. Lest be known that even tho I crave the sharing features we are not (ab)using it and stick to the normal license mode for now.

Cheers!
