### ISSUE TITLE
Use Docker image with different ports than 80 and 443

### ISSUE THREAD

**Issue by mr-gosh** [bitwarden/core#108]
we have allready something running on 80/443 on the docker host as you proposed in [here](https://github.com/bitwarden/core/issues/62#issuecomment-333186728) so we changed the config in the yaml file - it seems to work as we can open the webinterface - BUT when you try to add a new user it fails with an unexpected error

> Errors have occurred
> An unexpected error has occurred.

are you sure this works on different ports than 80/443?

**Comment by kspearrin** [comment]
This is now officially supported with v1.14.0. The installer will prompt you for alternate ports.

**Comment by bingcheng1998** [comment]
> This is now officially supported with v1.14.0. The installer will prompt you for alternate ports.

@kspearrin Thanks.

But when I tried to install it with docker, it didn't prompt me for alternate ports.

```shell
Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.26.0-rc1, build 07cab513
(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.example.com): bitwarden.xxx.com
(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): y
(!) Enter your email address (Let's Encrypt will send you certificate expiration reminders): xxx@xxx.com
Using default tag: latest
latest: Pulling from certbot/certbot
Digest: sha256:ba624186374c7e10191f7c70702c9dd059c9e9cade0ed8e800625e0aa5f55977
Status: Image is up to date for certbot/certbot:latest
docker.io/certbot/certbot:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint certbot (d80b2cea22c58434b8fb689a58f2a5e8e4bf5418c07f60eca27b4ec3923be59a): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.
ERRO[0000] error waiting for container: context canceled
```

I wonder is v1.14.0 the latest version?
