### ISSUE TITLE
Multiple urls

### ISSUE THREAD

**Issue by JaceHensley** [bitwarden/core#109]
Would be nice if a login could correspond to multiple urls. Like google.com and android.com. I find I need my Google login for both.

**Comment by kspearrin** [comment]
See https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7

**Comment by sanmai-NL** [comment]
@JaceHensley: so can this be closed now? 
@kspearrin: how can I contribute to the list of equivalent domains? (bitbucket.org & id.atlassian.com isn’t on it.)

**Comment by kspearrin** [comment]
Yes, done.

@sanmai-NL  See https://github.com/bitwarden/core/blob/master/src/Core/Utilities/StaticStore.cs#L11
