### ISSUE TITLE
Docker, mssql requirements, an the overbloated software development system of the moment

### ISSUE THREAD

**Issue by Zamana** [bitwarden/core#110]
In the beginning I was excited about this project. A chance to get rid of Keepass and use something more "web based". For a company, running a self hosted system is much better than using a database that an [ex]employee can keep at home...

I then tried to deploy Bitwarden on my self hosted humble AWS AIM machine, with just 1GB of RAM, and after some hours banging my head, I realized that mssql was continually restarting (or, better said, was not running) because it requires "at least 3250 megabytes of memory".

Ok, I can upgrade my machine. No problema with that. But in the end this whole thing seems to bloated and fancy to me. It seems too much for too little. A programmer's toy. And I'm a programmer.

Djizussss! We are talking about a database for passwords... Why it needs to be sooooooo complicated? Docker??? We really need this?

I hope that someone (not me) forks this code and do something simpler.

**Comment by kspearrin** [comment]
I am not really sure what you have opened this issue to suggest? That we change our technology stack?

**Comment by kspearrin** [comment]
We have updated the install docs to make the Linux RAM requirements more clear.

**Comment by OhjeezwhathaveIdone** [comment]
@kspearrin [here's](https://github.com/Microsoft/mssql-docker/issues/114#issuecomment-332976038) a comment from one of the collaborators of the mssql-docker project advising that they are going to lower the requirement to  2GB.  Sure people's perception that even 2GB for a password manager might still be too high it is still 50% less than what it was originally which might appeal/make it more accessible to a greater range of people.

**Comment by kspearrin** [comment]
@OhjeezwhathaveIdone That's great! We'll be able to reduce the requirement for bitwarden installations to whatever the minimum for sql server is.

**Comment by twright-msft** [comment]
The minimum memory requirement for the mssql-server-linux container image has been reduced to 2 GB as of the SQL Server 2017 CU2 release (:2017-CU2).

**Comment by joshuacox** [comment]
> I am not really sure what you have opened this issue to suggest? That we change our technology stack?

Not the whole stack! but why in blue blazing hell would I want my password data in a microsoft product?!? encrypted binary blobs I hope, but still what a poor choice.  Let me leap out of the frying pan (lastpass/logmein) and jump directly into the fire (microsoft).
