### ISSUE TITLE
Backup of BitWarden

### ISSUE THREAD

**Issue by kereza** [bitwarden/core#112]
Hello,

This is not an issue and I am not sure if I should ask this question here or if it is already asked. I did not see such question asked here.

Anyway, what is the best way to make backup of BitWarden database? Should we backup the whole container "MSsql" or some kind of dump etc?  

Thank you in advance.

**Comment by kspearrin** [comment]
There are two folders that are important and should be backed up. You do not need to backup and docker containers, since those are ephemeral. 

You should backup and keep safe:

- `./bwdata/mssql/backups`
- `./bwdata/core/attachments`

**Comment by kereza** [comment]
Thanks.
