### ISSUE TITLE
Expire trusted devices after 30 days

### ISSUE THREAD

**Issue by rggjan** [bitwarden/core#113]
After transitioning from LastPass, I think this was a good feature:
https://blog.lastpass.com/2015/11/new-in-security-expiring-trusted-devices-after-30-days.html/

Maybe you could consider it as well?

**Comment by kspearrin** [comment]
We already support this. Select "Rememeber me" when performing 2FA.

**Comment by rggjan** [comment]
Oh, I didn't read anywhere that 2FA is expiring after thirty days for bitwarden... I'll wait a bit longer then and see if it automatically logs out.

**Comment by kspearrin** [comment]
It will not automatically lock out. But it will require you to enter 2FA again the next time you log in.

**Comment by rggjan** [comment]
I see, thanks for the clarification!
