### ISSUE TITLE
Feature Request: Credential history

### ISSUE THREAD

**Issue by haneef95** [bitwarden/core#114]
It would be good if we can keep a history of our credential change.

Let's say I have a record with the following info:
```
Username: MyName123
Password: abc456
applicable domains: google.com, example.com, g3.com

```
and then I change the same record to:
```
Username: MyName321
Password: abc654
applicable domains: google.com, example.com, g3.com, q4.com

```
I should be able to see a history of when it was changed and who change it (if it's a shared folder/record).

Thanks,

Moved from: https://github.com/bitwarden/web/issues/121

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/core/issues/33 https://github.com/bitwarden/core/issues/51
