### ISSUE TITLE
Access to web vault on-premise server

### ISSUE THREAD

**Issue by jafreis** [bitwarden/core#118]
Hi,

I have set up an on-premise bitwarden server, after configuring the browser extension (Chrome) with the URL's, when I click the "Bitwarden Web Vault" button it redirects to the site https://vault.bitwarden.com instead of redirecting the URL of the Web Vault configured in extension.

Sincerely,
José Reis

**Comment by kspearrin** [comment]
Hi, can you please open this issue in the browser repo since this is an issue there.
