### ISSUE TITLE
Add support to re-prompt password for individual passwords or notes

### ISSUE THREAD

**Issue by haveneersrobin** [bitwarden/core#119]
I would really like the possibility to require a password 'each time' when opening a secure note/password. Even though your vault is unlocked, you would still need to enter your master password to view specific notes/passwords. 

This is useful, for example, for notes that contain sensitive information or passwords with 'high confidentiality'.

LastPass offers this via 'Require Password Reprompt'.

**Comment by jungle-boogie** [comment]
I support and request this feature. Thanks for raising this issue, @haveneersrobin.

**Comment by haveneersrobin** [comment]
@jungle-boogie Shame this hasn't good any(more) attention

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/core/issues/83

**Comment by Cabus1982** [comment]
I agree, very important with my VISA Cards
