### ISSUE TITLE
Secure Notes Support

### ISSUE THREAD

**Issue by sergei1152** [bitwarden/core#12]
Last pass gives you the ability to store secure notes, useful for things like storing licence keys and other important unstructured information.

**Comment by kspearrin** [comment]
This is definitely on the roadmap.

**Comment by KarimGeiger** [comment]
Isn't this kind of already there? Just not providing login information but a note. Works for me. Though, there should be a section for "note only" passwords, or something.

**Comment by kspearrin** [comment]
@KarimGeiger Yes, you could easily still do this today. It will just be a separation in your vault listing in the end.

**Comment by sreich** [comment]
I assume the scope of this issue also includes various built-in templates for secure notes? LastPass offers database, server, drivers license, health insurance (all with icons)

**Comment by evaryont** [comment]
For reference, Lastpass seems to store secure notes internally with the URL "sn", or possibly "http://sn" (not sure if Bitwarden added the protocol during import or not). Something to look out for in the import code.

**Comment by kspearrin** [comment]
@evaryont We handle secure notes during import today, they just end up going into the current "Notes" field for a login with no username/password.

**Comment by rk-development** [comment]
hello, is there any ETA for this one?
keeping important information as notes isn't secure at all.

**Comment by kspearrin** [comment]
@rk-development Within the next 30-45 days

**Comment by rk-development** [comment]
Thank you!
This will make me switch from LastPass for sure.

**Comment by luispabon** [comment]
@kspearrin I can see notes are currently imported as a login with website `sn`, will these be automagically moved to secure notes, once the feature becomes available?

**Comment by kspearrin** [comment]
@luispabon  We will adjust the importers to properly import secure notes. There is no path for migrating existing imported data.

**Comment by luispabon** [comment]
Understood, thank you.

> --
Kind regards,
Luis Pabon

**Comment by zikeji** [comment]
This is good to hear! Will definitely be moving once this feature is introduced.

**Comment by kspearrin** [comment]
Update: We've got this working in our dev builds for web vault and browser extension so far. Still need to implement it into the mobile app now.

**Comment by rk-development** [comment]
Is there any way to jump into dev/beta builds or i have to wait till official release?

**Comment by kspearrin** [comment]
You can build from source using the directions on the readme of this repo.

**Comment by dakoellis** [comment]
Super Interested in this as well.  Is this issue the best way to stay updated when the feature becomes available  for cloud, or is there somewhere else that will be updated?

**Comment by kspearrin** [comment]
We will post an announcement on social media/blog when this is released.

**Comment by kspearrin** [comment]
done for next release

**Comment by haveneersrobin** [comment]
Is there a possibility to require a password 'each time' when opening a secure note. Even though your vault is unlocked, you would still need to enter your master password to view specific notes. LastPass offers this via 'Require Password Reprompt'.

**Comment by ruppalsingh** [comment]
@haveneersrobin Please open a new issue.

**Comment by haveneersrobin** [comment]
@ruppalsingh Apologies. Done: #119
