### ISSUE TITLE
Some Questions about Docker Container

### ISSUE THREAD

**Issue by Homer-Sim** [bitwarden/core#120]
Hello,

I would like to understand hosting a own Bitwarden server on my own server with Docker containers.

If I am installing a bitwarden server is all my password data on my own machine or is it still in contact with your servers?

I installed your containers on a virtual lab machine (no access possibility via 80/443) so I was not able to test it completely. But I recognized a constantly restarting  mssql container.

To give it a try on my running home server I a, fearing two things:
1. How can Bitwarden be integrated into an existing caddy webserver acting mainly as reverse proxy for different web applications (nextcloud, cops, wordpress, etc). All is for private use only.
2. Is there a way to setup a defined local folder for storing data for backup reasons?

Thanks, I guess there will come up some more questions.

**Comment by Homer-Sim** [comment]
![2017-11-05 21_11_26-testdocker int](https://user-images.githubusercontent.com/13933431/32418636-fcd244d2-c26d-11e7-92bb-a03803aa6e73.jpg)

**Comment by kspearrin** [comment]
Yes, all data is stored on your machine. There is no contact with bitwarden servers (unless using push notifications as documented in the install article).

The restarting is likely due to not meeting the minimum RAM requirements. See install docs.

1. The current installer does not support running on a server alongside other web applications/ports. Hopefully a future update will allow this.
2. All data is stored in the ./bwdata folder relative to your installation. You can back it up however you like. See https://help.bitwarden.com/article/backup-on-premise/

**Comment by Homer-Sim** [comment]
Thanks for your quick answer even if it makes me waiting for an update.
Yes, the memory can be the issue.
Maybe it is possible to make the /bwdata customized with -v volume ?
Wouldn't it be enough to expose the two ports and ask for an external value -p 82:80 .... to make it running parallel to other web apps?

And my last question. A own stack would have the basic/free options or is there "no limitation"?

Thanks, great job you doing here

**Comment by kspearrin** [comment]
Yes, you can modify the ports manually in the compose file if you like. This will get overwritten each time you update though.

I don't understand your last question, sorry.

**Comment by Homer-Sim** [comment]
last question is related to this:

![2017-11-06 20_38_56-free open source password manager _ bitwarden](https://user-images.githubusercontent.com/13933431/32460295-94e8c4ca-c332-11e7-9625-40e9d00a1b9c.jpg)
![2017-11-06 20_38_46-free open source password manager _ bitwarden](https://user-images.githubusercontent.com/13933431/32460301-98b15c20-c332-11e7-9c9e-61997174046a.jpg)

**Comment by kspearrin** [comment]
Please see https://help.bitwarden.com/article/licensing-on-premise/

We plan to add an option for self-hosting to the personal plan in the future.

**Comment by kspearrin** [comment]
We've just updated our families plan (used to be called personal) to now include self-hosting as part of it's license.
