### ISSUE TITLE
Error creating organization in self-hosted instance

### ISSUE THREAD

**Issue by nbebout** [bitwarden/core#126]
I created a families organization and attempted to load the trial license into my self-hosted instance, and it says

Errors have occurred

An unhandled server error has occurred.

**Comment by nbebout** [comment]
And yes, I just upgraded it a few minutes ago, so it should be running the latest version

**Comment by kspearrin** [comment]
@nbebout Can you look in ./bwdata/core/logs/Api to see what the error was?

**Comment by nbebout** [comment]
2017-11-09 04:57:26.835 +00:00 [Error] Procedure or function Organization_Create has too many arguments specified.
System.Data.SqlClient.SqlException (0x80131904): Procedure or function Organization_Create has too many arguments specified.

I can attach more logs if you want, but i think this seems to be the important part?

**Comment by kspearrin** [comment]
Try running `./bitwarden.sh -updatedb`

**Comment by nbebout** [comment]
Works, thanks.  Sorry, I had forgotten that step when I upgraded.
