### ISSUE TITLE
Error with Families organization on self-hosted bitwarden instance

### ISSUE THREAD

**Issue by nbebout** [bitwarden/core#127]
Everytime I go to my organization on my self-hosted bitwarden instance I see

 Organization Disabled
This organization is currently disabled. Users will not see your shared logins or collections.
Update your license to reinstate this organization.

I have updated to the latest release a couple days ago, which added the Families support.  I have a current Families trial license installed.  I tried re-installing the license to see if that fixed it, but it doesn't.

**Comment by kspearrin** [comment]
Can you check ./bwdata/core/logs/Jobs and see why it disabled the org?

**Comment by kspearrin** [comment]
> I tried re-installing the license to see if that fixed it, but it doesn't.

Did you get an error when you did this or what?

**Comment by nbebout** [comment]
[bwlog.txt](https://github.com/bitwarden/core/files/1462838/bwlog.txt)
It accepts the license, and when I click on "Billing & Licensing" below the error, it even shows that I have a license.  Nothing looks obvious on the logs, but I've attached it here.

**Comment by kspearrin** [comment]
Might need to go back another day on the logs.

Try refreshing the page after updating the license. That should make it go away.

**Comment by nbebout** [comment]
It appears that it works now after I refreshed the page.

The original error was
2017-11-09 06:00:02.129 +00:00 [Information] Starting job '"validate-2017-11-09 06:00:2017-11-09 06:00:03.768 +00:00 [Information] Validating licenses for 1 organizations.
2017-11-09 06:00:03.996 +00:00 [Information] Organization d5c7b602-2372-4b5d-a35d-a8260054450d("bebout.net") has an invalid license and is being disabled.
2017-11-09 06:00:04.289 +00:00 [Information] Finished job '"validate-organizations"'.

But updating the license must have fixed it.

**Comment by kspearrin** [comment]
I'm wondering if it's just going to disable it again in a few hours though. For some reason it thinks you license is invalid.

**Comment by nbebout** [comment]
Does it matter that it is a trial license instead of a regular license?

**Comment by kspearrin** [comment]
Well, the trial license likely has an expiration date on it for when your trial actually ends. It will get disabled after that, but it sounds like you used the same license to upload again and it was accepted so you must still be under a valid trial.

**Comment by nbebout** [comment]
It does, and it is still current.

I'll keep an eye on it and will let you know if it stops working again or not.

**Comment by kspearrin** [comment]
Were you altering data from the database or anything that would cause incompatibilities with your license?

**Comment by nbebout** [comment]
No

**Comment by nbebout** [comment]
It stopped working again on 2017-11-11.  Same error.
2017-11-11 00:00:2017-11-11 00:00:03.301 +00:00 [Information] Validating licenses for 1 organizations.
2017-11-11 00:00:03.539 +00:00 [Information] Organization d5c7b602-2372-4b5d-a35d-a8260054450d("bebout.net") has an invalid license and is being disabled.

I had even re-downloaded a new license file and it is still happening.

**Comment by kspearrin** [comment]
Thanks. I will investigate this more tomorrow and get a fix out ASAP.

**Comment by kspearrin** [comment]
@nbebout I found the issue. It only affects family plans. I will put a fix out tomorrow.

**Comment by kspearrin** [comment]
This should now be fixed with v1.14.1

**Comment by nbebout** [comment]
Yes, I updated last night and re-imported my license and it is still enabled this morning.  Thanks for the quick fix!
