### ISSUE TITLE
Verification mail is not being sent in local installation

### ISSUE THREAD

**Issue by amenk** [bitwarden/core#128]
I am trying to activate my enterprise license, for which I have to send the verification mail in my on-premise installation.

I have done

      sudo vi bwdata/env/global.override.env 

and set the SMTP settings (mailjet).

Even the UI displays "Mail was successfully sent" this does not seem to be the case

1) Ad hoc help: how do I refresh the mail settings? isn't bitwarden.sh stop/start enough?
2) The UI should not say "mail was successfully sent" in case it wasn't

**Comment by kspearrin** [comment]
You can check mail logs in ./bwdata/core/logs/api 

Can you share the settings you have?

**Comment by amenk** [comment]
I do not have such log

   ~/bwdata/core/logs$ ls
   Jobs


2017-11-11 15:45 GMT+01:00 Kyle Spearrin <notifications@github.com>:

**Comment by kspearrin** [comment]
It sounds like you have a misconfiguration. I would test your settings outside if bitwarden first to make sure you can send mail with them.

**Comment by amenk** [comment]
I already sent mails using Thunderbird with that config ...
Any idea why the log is not created?
​

**Comment by kspearrin** [comment]
Not sure why there is no log. Can you share your redacted smtp Settings so i can have a look?

**Comment by amenk** [comment]
I shared my SMTP privately with @kspearrin - there seems to be a problem on the side of mailjet in the moment.
I also did a test with telnet, getting a "queue as ......." message but the mail does not appear to be processed properly by mailjet.

This almost can be closed. 

But I found one small glitch: When I change my SMTP data to a bad login, I do get a log message, but the popup on the web vault still says "Mail was sent".

**Comment by kspearrin** [comment]
Unfortunately we need to send SMTP asynchronously, so in the event of an error we only know later, which is why we just log it.

**Comment by amenk** [comment]
Not sure if it is the same issue. Mine turned out to be on the side of mailjet. They confirmed mails.as accepted but did not deliver them.

**Comment by sorcer1122** [comment]
Well, at least it behaves in a very similar manner, except I used postfix. Any ideas how to find the log?

**Comment by amenk** [comment]
What do the postfix logs say?

**Comment by sorcer1122** [comment]
This is the problem - logs say nothing, there is not even a record of anything. I also tried other SMTP servers like gmail but it did not fix the issue.

**Comment by amenk** [comment]
You could try to "simulate" a SMTP server using netcat nc -s to see if it bitwarden tries to communicate at all with the SMTP

**Comment by alatteri** [comment]
I am seeing the same exact problem.  Nothing in the logs, verified my settings properly.  Really hoping to use Bitwarden in enterprise environment.

**Comment by dmatora** [comment]
same problem, nothing in the logs

**Comment by thieumaxx** [comment]
i have the same problem. when i want to send a mail i've an error and i don't know why

**Comment by brycematheson** [comment]
Similar issue as above. Using Gmail as the SMTP relay, but I see no logs and no verification emails.

**Comment by kspearrin** [comment]
@brycematheson Did you enable "insecure apps" for your gmail account so that SMTP connections could be made?

**Comment by brycematheson** [comment]
@kspearrin I did, yes. I've tried toggling between both settings, but no luck. I'll keep playing with it.
