### ISSUE TITLE
Amazon worldwide equivalent domains

### ISSUE THREAD

**Issue by dwf** [bitwarden/core#130]
The ones I know of:
- amazon.ca
- amazon.co.uk
- amazon.es
- amazon.de
- amazon.fr
- amazon.it
- amazon.co.nz
- amazon.com.au
- amazon.co.jp`

**Comment by kspearrin** [comment]
added a few missing ones for next release.

**Comment by dwf** [comment]
Did this get added? Still doesn't work for me.
