### ISSUE TITLE
(self-hosted) Disable Registrations?

### ISSUE THREAD

**Issue by christianreiss** [bitwarden/core#131]
Hey folks,

running a current dockerized, self-hosted installation.
On initial installation I enabled registrations. Now that all users are registered I would like to disable registrations again. So I set globalSettings__disableUserRegistration in ./bwdata/env/global.override.env to false and re-started the containers via bitwarden.sh.

No effect, the option is still there. What would be the correct way to disable registrations?

Cheers,
-Chris.

**Comment by kspearrin** [comment]
After you disable it, users will get an error when trying to register. The options still show though.

**Comment by christianreiss** [comment]
Tested, tried- you are right. Now obvious tho. Maybe remove the registration link?
-Chris.
