### ISSUE TITLE
Password length/strength settings

### ISSUE THREAD

**Issue by kereza** [bitwarden/core#132]
Hello,

This is probably a stupid question, but I searched a little bit and could not find an answer.

Is there a setting in BitWarden (hosted on premise) where I can select what is the length of the self generated password?

Thank you in advance.

**Comment by kspearrin** [comment]
What self generated password?

**Comment by kereza** [comment]
![capture](https://user-images.githubusercontent.com/7092383/32782481-314beeea-c951-11e7-8aa6-3285a996f5ac.PNG)

**Comment by kspearrin** [comment]
This one is not configurable at this time. The password generators in the client apps have a whole array of options, however.

**Comment by kspearrin** [comment]
If you want to further request this, please open this issue under the web repo, since it applies there.
