### ISSUE TITLE
Bitwarden installation fails

### ISSUE THREAD

**Issue by calltheninja** [bitwarden/core#133]
Using most recent bitwarden build and official install guide at https://help.bitwarden.com/article/install-on-premise/

Using Ubuntu 16.04.2 LTS. Installer docker-ce and docker-compose from official docker repos.

Error on step "./bitwarden.sh start" installation appeared successful.

Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.8.0, build unknown

ERROR: Version in "/opt/bitwarden/bwdata/docker/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

We're very excited about this software so hopefully we can get this working. Thanks!

**Comment by kspearrin** [comment]
Sounds like your using an outdated version of docker/compose. Make sure you are updated.

**Comment by calltheninja** [comment]
Ran an apt update and upgrade with no upgrades avail for docker. This is the docker repo we're using from our /etc/apt/sources.list:
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

Maybe docker just doesn't support 3.0 for 16.04? That would be a bummer.

**Comment by kspearrin** [comment]
Do not install with apt-get. It is not up to date. Please see official docs linked from: https://help.bitwarden.com/article/install-on-premise/

**Comment by calltheninja** [comment]
The docs link to:
https://docs.docker.com/engine/installation/
Which takes me to:
https://docs.docker.com/engine/installation/linux/ubuntu/
Which takes me to:
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

Which suggests using the APT repository we're using. Am I missing something super-obvious here? This is my first time with docker. If there's a non-docker way to install it and docs for it, I'm happy to go that route since we already have a LAMP stack on this server.

Thanks for the quick responses and help : )

**Comment by kspearrin** [comment]
Compose should be installed with https://docs.docker.com/compose/install/#install-compose

**Comment by calltheninja** [comment]
Gotcha. It looks like the latest version of docker in the official repos for Ubuntu 16.04 is Docker version 17.09.0-ce, build afdb6d4 but according to the docker-compose compatibility matrix (linked from that page) that version can't handle 3.x compose files. See https://github.com/docker/compose/releases

Looks like we'll need a later version of Ubuntu for this install. I'll go ahead and close this issue in that case. Thanks for your help : ).

**Comment by kspearrin** [comment]
So you should be fine with Ubuntu 16. That is what I use when testing.

**Comment by calltheninja** [comment]
Doh! I realize I mis-interpreted that compatibility matrix. It only speaks to docker-engine's compatibility not docker-composer.

So I got to the "updatedb" step in your installation guide with the failure:
`docker:` Error response from daemon: cannot join network of a non running container: 83de7f75d9a2d3eae7bf87ba53198e6feac301416e51b1917f17b97832dcba82.
ERRO[0000] error waiting for container: context canceled `

When I do 'docker ps' I get this and it never comes online, just keep restarting. Is this because I have a pre-existing MySQL service running?
83de7f75d9a2        bitwarden/mssql:1.14.1         "/entrypoint.sh"    About a minute ago   Restarting (1) 6 seconds ago

**Comment by kspearrin** [comment]
You likely arnt meeting the RAM requirements of mssql. See https://help.bitwarden.com/article/install-on-premise/#adjust-resources
