### ISSUE TITLE
Reverse proxy support during installation

### ISSUE THREAD

**Issue by Aidenir** [bitwarden/core#138]
I just got bitwarden up and running after some mucking about with the mssql image, and just want to thank you for making this application. I've been on the hunt for exactly this for many years.

However in my homelab I keep all services behind an haproxy which does TLS termination using letsencrypt cert (fully automated process). During the setup using the bitwarden.sh script you give the option to specify the domain it will run on, but it would be great with like an option to say if this is reverse proxied or not. The problem I had was that I am running it on a non-default port internally (many services on the same machine, can't have 443 on all of them :) ). And when I tried to register a user I just got "An error occured", with no info anywhere. But it was because in many of the config documents the port I specified had been added to the external domain name, ex https://my.domain:8443 instead of just https://my.domain. After I  found this it was easy enough to fix, but could be a useful option.

Do you accept pull requests? I could maybe get one up during the week, shouldn't be too hard?

**Comment by Aidenir** [comment]
Solved by merged PR #139.

**Comment by suprdave23** [comment]
Replying to this, as I am running into this exact same issue. Installed bitwarden today and need to run it behind an nginx reverse proxy. I can get the login page just fine, but trying to login gives me:

"An unexpected error has occurred."

I cannot find any docs on where error logs are kept to help me understand what it is having an issue with. I have stopped bitwarden and edited the "global.override.env" to remove all mention of my proxy port from configuration directives in there (10443), but am still getting this error.

What else needs to be changed to have it support running behind a proxy?


Thanks!

**Comment by kspearrin** [comment]
@suprdave23 Logs can be found in `./bwdata/core/logs`. This update/PR will go out with our release next week.
