### ISSUE TITLE
On prem non-standard port redirection issue/Android app won't connect

### ISSUE THREAD

**Issue by Shadow00Caster** [bitwarden/core#140]
I have the latest version of bitwarden running on premise and am using non-standard ports for HTTP (8091, 8091) which were defined through the install script.  The web vault and browser extension appear to be working normally, however the Android app stated that there is a problem connecting to the server.

I noticed that when trying to access the seperate server URLs (api, ident etc), they appear to be redirecting to the standard ports and not adhering to the custom ports as configured.

I see that in the global.override.env file, the URLs are correctly defined (https://sub.domain.tld:8091/<api, identity, attachments>), however if I try to access any of those 3 URLs through a browser, it redirects to the standard HTTPS port (443, https://sub.domain.tld/<api, identity, attachments>).  The same occurs if I access the server internally via IP.

Not sure if this is intended behavior and my Android app not working is something else or not.

**Comment by kspearrin** [comment]
Would it be possible for you to send me the endpoints so that I can ping them from my side and see what is going on? You can email them to support@bitwarden.com

**Comment by Shadow00Caster** [comment]
I sent an email to support@bitwarden.com with the endpoint.

**Comment by kspearrin** [comment]
@Shadow00Caster I have followed up via your email.

**Comment by Shadow00Caster** [comment]
Saw that, thanks.  Responded to that as well, looks like it's just the root of the route/path that is redirecting (/api etc) where an actual found doc works as normal (/api/alive).

Still have the Android issue as well as atleast one other person: https://github.com/bitwarden/mobile/issues/175
