### ISSUE TITLE
Kudos + Some questions

### ISSUE THREAD

**Issue by davidroth** [bitwarden/core#141]
First of all let me congratulate you for this awesome project. Really impressive to see this big project  (with backend, frontend, mobile) being developed by a single person - great work!

We are currently investigating and maybe considering switching our organisation to bitwarden - we'd definitely need the payed version ;) Especially being open source and having such a nice codebase (i love the fact that its .net+c#) is a big bonus for this solution.

Some technical questions (I am a .net developer):
I had a brief look at the server side code and some parts came to my attention.

 - Stored procs for sql logic
Is there a specific reason on why you implemented all your queries as stored proc? In my experience this has several drawbacks.  (Business Logic split between c# and sql server, tightly bound to sql server, no refactoring/find all references/ compiler checks, some more ...)

 I'd love to see a new version using EntityFrameworkCore instead (Linq, Compiler check for queries + refactoring, easy support for other stores like mysql+postgres, easier maintaining/debugging/ of business logic)

- No unit/integration tests

I know, writing tests isn't always the first priority, and I am sure you have enough to do with maintaining all the parts (frontend, backend, mobile). However, some integration tests should be added so that its easier to bring the codebase forward without breaking functionality + introducing bugs. 

I am really interested in contributing to this beautiful project.  Would you accept pull requests for these topics?

**Comment by kspearrin** [comment]
> Stored procs for sql logic

There is no plan to utilize EF. Stored procedures in the database offer much better performance and better maintainability (think of a DBA role). Sure, having it all in C# would be nice and all (for some of the reasons you motioned), but we have many rather complex queries that are not even possible in EF. I'd be happy to point you to some if you haven't already found them.

> No unit/integration tests

Yes, this is one thing that will start being prioritized in the coming year as more manpower becomes available. We'd be happy to accept any PRs in this regard. The codebase is already setup rather well for testing/mocking (DI everywhere).
