### ISSUE TITLE
Support for Multiple URLs per Entry

### ISSUE THREAD

**Issue by CodingMarkus** [bitwarden/core#142]
Some sites have multiple domains but the same account works with all of them. Of course, I can just make one entry per domain but if I ever have to change the password, I have to remember to change it for every entry. I think there is a better solution to that.

My suggestion:
At the moment it's already possible to store custom fields of type "Text", "Hidden" (Password) and "Boolean" (Checkbox). Just add a new type: "Alias URL". When set, the code will also consider this field when searching for a match for the current URL. 

Implementing it like that seems to be the smallest hassle IMHO. There's virtually no UI change other than adding a new custom type. There's also virtually no API change anywhere, other than supporting another custom type. Only the code that matches for URL needs to understand the meaning of that new type, for the rest of the code this is just the same as "Text" (unless you want to syntax check URL fields).

I must admit, I don't know how the search code looks like at the moment, so it could have a performance impact to search these extra values of the standard values are fields in a rational database whereas the extra fields are not (e.g. they are all stored in one db field as JSON). OTHO, if you ever want to make notes text fields searchable, you'd have the same problem.

If I would have to implement something like bitwarden, I had chosen the database format as follows: The standard fields that every entry has (or can have) are columns of a database table (table A), the custom fields however are entries in an own table (table B), one entry per field and the relationship is expressed via a n-to-m cross table that maps custom fields in B to entries in A. That way finding all matching URLs is just a matter of two to three selects: 1st select finds all entries of table A whose URL column matches the current domain (that's would already be the current situation), 2nd select finds all entries in table B whose type is URL and whose values matches the current domain. And iff the 2nd select found something, then there's a 3rd select that's  a join of B  and the n-to-m cross table to find the IDs of the entries in A that belong to the found entries in B (or if the IDs are of no use, you can make a 3 table join and directly get the entries from A). This allows custom values to be indexed if desired and to be fully searchable at maximum speed a database can offer. It also offers you unlimited flexible to add more custom fields in the future (more types).

Without a database, I had done it like this: I had build up a lookup table whose keys are the URLs and whose values the references to the entries (those of table A). If those URLs are then taken from the URL field of an entry or from a custom data field would play no role for the search code (the search code won't care where the URL came from). Only the code building/updating that table would need to know about these new custom fields. The search code iterates over all keys of the table (one can cache those in an array for speed reasons), finds the matching ones and then uses these matches to perform look-ups to retrieve the matching values.

Well, I'm just sharing ideas here, feel free to ignore them. For me it would be only important to get these alias URLs. If you need an example where this would make sense, think of StackExchange: You can use the same account to login to stackoverflow.com, serverfault.com, and superuser.com

**Comment by tcoenraad** [comment]
I believe this is what you're looking for: https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7

**Comment by CodingMarkus** [comment]
@tcoenraad Well, that's the feature I know from LastPass and for me this already sucked when I was still using that service. I didn't know it even exist as neither the mobile app, no the browser app show this feature or have any indication that it exists and I only use those, I never use the website. Having a global list seems somehow sub-optimal to me, with no real personal benefit, other that it will work automatically for pre-configured domains. You know, global data is so "far away" from the actual login data that are all bound to a single item. Yet I'll guess it will work for my use case; I'm about to test that right now.

**Comment by kspearrin** [comment]
This is done for next release.
