### ISSUE TITLE
Making backups

### ISSUE THREAD

**Issue by gregf** [bitwarden/core#144]
When I look at my bwdata directory with du -hs bwdata it reports back that the directory is 202M the `bwdata/mssql/vault_log.ldf` file alone is 72M.

I run `./bitwarden.sh stop`. I then pull down my bwdata directory with rsync. My local copy of bwdata is only 23M and the same `vault_log.ldf` file is now 2.7M.

What gives? I need to make a proper backup so I can redo my server, but I'm afraid i'm going to loose everything with these numbers not adding up. 

Thanks!

**Comment by kspearrin** [comment]
Probably caches from SQL server or something. I'm not sure. Just try it?

**Comment by gregf** [comment]
Strangly enough reuploading the data to the server it shows back up as 202M strange to me, but it does restore fine.
