### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by chasgames** [bitwarden/core#145]
Hi just bought a Rock64 Development board with 4GB RAM to host bitwarden on. 

Now i realise i can't install it because the Bitwarden docker images are x86_64 only, Any idea how to get this working? 

do i need to find ARM replacements for these docker images?

Nginx - how about lsioarmhf/nginx-armhf ?
microsoft/aspnetcore:2.0 - how about rootdevelop/rpi-aspnetcore ?
microsoft/dotnet:2.0.0-runtime - seems to have a tag for ARM support already 2.0-runtime-stretch-arm32v7

Thanks!:>

**Comment by kspearrin** [comment]
I don’t think sql server is compatible with ARM.

**Comment by chasgames** [comment]
Ahh didn't realise this uses sql server.

Can we can use MariaDB instead? (this has ARM support) https://hub.docker.com/r/yobasystems/alpine-mariadb/tags/

or MySQL has a RPI ARM image too available.

It's a shame because it would be a perfect match being able to host this locally on 4GB capable ARM boards/QNAPs/Synologys etc one of the big benefits of the self-hosted appeal of bitwarden!

Cheers

**Comment by kspearrin** [comment]
Only sql server is officially supported at this time. Feel free to implement your own database layer if that is something you are interested in.

**Comment by chasgames** [comment]
Ahh yes i'd definitely recommend moving to PostgreSQL or MariaDB when you can anyway, to support the open source momentum from the project !

I'll have a play see if I can get anything working, Thanks for your fast replies.
