### ISSUE TITLE
A network-related or instance-specific error occurred while establishing a connection to SQL Server

### ISSUE THREAD

**Issue by MartinDelille** [bitwarden/core#148]
I tried to install bitwarden locally on my mac using the following commands:

    curl -Ls -o bitwarden.sh https://bit.ly/bw-sh  && sudo chmod u+x bitwarden.sh
    ./bitwarden.sh install
    ./bitwarden.sh start
    ./bitwarden.sh updatedb

Unfortunately when creating the first user I have the following error: _An unhandled server error has occurred_

After looking at #121 I tried to run the following commands without success:

    ./bitwarden.sh update
    ./bitwarden.sh restart

I checked the log in `./bwdata/core/logs/Api` and found this:

```
...
2017-11-26 14:58:58.254 +00:00 [Error] A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.ResolveCallback(Object context)
...
```

Any chance to get an hint on that?

**Comment by kspearrin** [comment]
Please see this: https://help.bitwarden.com/article/install-on-premise/#adjust-resources

Likely not enough resources for docker.

**Comment by MartinDelille** [comment]
Awesome, thanks!

**Comment by mjeveritt** [comment]
> Please see this: https://help.bitwarden.com/article/install-on-premise/#adjust-resources
> 
> Likely not enough resources for docker.

for anyone who finds this issue and cannot see the above link, it's preserved via WBM at https://web.archive.org/web/20171123110418/https://help.bitwarden.com/article/install-on-premise/
