### ISSUE TITLE
URL Filter options

### ISSUE THREAD

**Issue by MattLParker** [bitwarden/core#149]
Ability to set a domain (ie contso.com) and have it be subdomain specific and/or Port match specific. That way the following only show if matched completly.

mail.contso.com   u:  User1 P: Password1
wiki.contso.com   U: User2 P: Password2
mail.contso.com:8080   U:Adminuser1 P: Password3

**Comment by kspearrin** [comment]
Mostly discussed here: https://github.com/bitwarden/browser/issues/77

**Comment by kspearrin** [comment]
This is done for next release.
