### ISSUE TITLE
Banned - PLEASE LOOK AT THIS - HI-PRIO!

### ISSUE THREAD

**Issue by erousr** [bitwarden/core#152]
I've been banned from accessing bitwarden. I appreciate you having automatic security measures in place, but this is ridiculous. I've spent a few hours today updating, importing and sorting my passwords and therefor had some impact on the server.

I am not able to access my new passwords at all, please whitelist me immediately so I can export everything from bitwarden and keep a backup in some other service in case this happens again.

Regards

**Comment by kspearrin** [comment]
This has been addressed via email.
