### ISSUE TITLE
[On premises] Account creation fails

### ISSUE THREAD

**Issue by djbuch** [bitwarden/core#153]
Hello,
I keep getting this error on a fresh install.

What could I do ?

![image](https://user-images.githubusercontent.com/5637724/33531994-6d84881a-d895-11e7-96f5-9d5c33794557.png)

Regards,
David

**Comment by kspearrin** [comment]
Likely your mssql instance is restarting. Please consult installation docs on resource requirements (RAM).

**Comment by djbuch** [comment]
Hello,
I'm running this docker on a Linux with 16GB of ram, and the mssql seems running : 
![image](https://user-images.githubusercontent.com/5637724/33542192-3d0e65a6-d8d2-11e7-97f8-b6db482627af.png)

**Comment by djbuch** [comment]
I found the reason, I had installed without any domain name
