### ISSUE TITLE
Nightly mssql backups are not being made

### ISSUE THREAD

**Issue by suprdave23** [bitwarden/core#156]
Self hosted of course, not sure how to troubleshoot.

bwdata/mssql/backups folder is empty. The containers have been running for a few days now.

Where can I begin troubleshooting? Thanks!

**Comment by kspearrin** [comment]
Hmm. That's no good.

Can you bash into the `mssql` container and try to execute the `/backup-db.sh` script?

**Comment by kspearrin** [comment]
Also, after bashing in, check `/var/log/cron.log` for any potential errors

**Comment by kspearrin** [comment]
I cannot reproduce. Seems to be working fine on my test installation each night. Is your server running 24/7 or does it go offline during the nightly cron for mssql backups (midnight)?

**Comment by kspearrin** [comment]
If the script works then we know the problem must be with the cron then but I wouldn't know why since I can see it working nightly on my test installation :-/

**Comment by suprdave23** [comment]
I got his resolved. The package "rsyslog" was not installed in the mssql container, so as a result logging was not working. I believe this was causing cron to not execute, as after installing rsyslog and then fixing the permissions of the log files under /var/log to be owned by syslog:adm, cron is now logging properly under /var/log/cron. For testing I changed the backup script to execute every minute and verified it ran and logged to /var/log/cron

**Comment by suprdave23** [comment]
Will a future version of the mssql container have rsyslog installed in it? I don't want to do upgrades that will potentially break cron again.

**Comment by kspearrin** [comment]
Yes, any update will reset your container changes. I'm not sure why you had to install `rsyslog` in the container to get it working whenever I don't have to. It's the same image? Did you happen to make any edits to this container prior?

**Comment by suprdave23** [comment]
Yes, exact same image, no changes at all to it.

I'm pulling an update right now, will report back shortly if this issue persists in the latest version.....

**Comment by kspearrin** [comment]
Only difference I suppose is that I am running from a Windows host, but that shouldn't make any difference to the image.

**Comment by kspearrin** [comment]
Maybe it has something to do with permissions on mapped volumes tot he host machine?

**Comment by suprdave23** [comment]
I'm a Linux sysadmin, but my familiarity with docker is minimal, so I'm learning as I'm going here.

Given that I can run the backup manually without errors, I don't think that's the issue.

I've changed the cronjob to execute every minute again on this new version. Waiting..

**Comment by suprdave23** [comment]
Executes fine now, must have been some weirdness in the older version I was running.

Good to go! Thanks for the quick responses!
