### ISSUE TITLE
Docker container naming

### ISSUE THREAD

**Issue by toanhoang** [bitwarden/core#159]
First of all, thanks for a great piece of software!
I'm wondering if there is possible to have docker container names that is easier to read which system they are a part of?
On my server I have many docker containers, having containers named web, icon, api, etc... makes it real hard to read. I have also problems when running multiple docker-compose files together where the service names are identical.

My suggestion is to append bitwarden to the names, e.g: web -> bitwarden-web

**Comment by kspearrin** [comment]
Good idea. Done for next release.

**Comment by toanhoang** [comment]
I would like that the service names also get appended with bitwarden too :-)

**Comment by kspearrin** [comment]
@toanhoang What benefit does changing the service names have?

**Comment by kspearrin** [comment]
@toanhoang I looked into naming the services but this won't be possible since there are too many pre-established dependencies on those for existing users that will update.

**Comment by toanhoang** [comment]
@kspearrin Sorry for the late reply. In my head, that may cause a problem, but if it's a big problem changing and nobody has any problems, it's not a problem. :-)
