### ISSUE TITLE
Error installing self-hosted : standard_init_linux.go:195: exec user process caused "exec format error" on armhf armv7 Odroid HC1

### ISSUE THREAD

**Issue by ChriKn** [bitwarden/core#161]
Hi everybody,
I am trying to get the bitwarden docker to run on a ODROID HC1 ( ARM v7l armhf architecture with Armbian Jessie image installed - docker ce and docker compose are installed fine) and I am getting a weird error when launching the installer script right after the (working) letsencrypt part:

Status: Downloaded newer image for certbot/certbot:latest
standard_init_linux.go:195: exec user process caused "exec format error"

Does anybody have an idea ? Did I miss something ? From what I gathered it could have to do with the architecture... Can I do something ? Bitwarden was the main reason for me to buy a HC1 in the first place. It would be great to get it running...

**Comment by kspearrin** [comment]
ARM is not officially supported since images are compiled as x86. Additionally, mssql will not run on ARM.

Related: https://github.com/bitwarden/core/issues/145

**Comment by n0rrin** [comment]
Is this still actual? 
There are some single-board-computers that have the minimum requirements of bitwarden (i.e. odroid xu4) and it would be great to use them as a bitwarden server.

**Comment by MichaelSchmidt82** [comment]
yup

**Comment by MichaelSchmidt82** [comment]
yup.
