### ISSUE TITLE
How to store non-website logins?

### ISSUE THREAD

**Issue by c0necto** [bitwarden/core#162]
Besides our standard website logins we also have many non-website logins (FTP, System Logins, etc.). 
We can store them just like any other logins, for example: 

![image](https://user-images.githubusercontent.com/12429545/33829886-58b371de-de72-11e7-974a-200d1bedf1d6.png)

The problem however is, that this login will be included on website `host.foo`'s login form. Current workaround would be to remove the URI and store the Host in the notes field... 

Am I missing something? Is there something like a "Website login" setting?

**Comment by kspearrin** [comment]
If you don't want it to show up for the website your best bet is to just leave the URI field blank, as you have already discovered. Then use the notes field.

**Comment by 3v1n0** [comment]
Suppporting HTTP authentication as Lastpass does (or did?) with Firefox would be cool too.
It's annoying to handle those browser dialogs.

**Comment by kspearrin** [comment]
@3v1n0 See https://github.com/bitwarden/browser/issues/116
