### ISSUE TITLE
Docker images cannot be downloaded from registry

### ISSUE THREAD

**Issue by turbomettwurst** [bitwarden/core#165]
When pulling the container it errors out with
> Error response from daemon: Get https://registry-1.docker.io/v2/bitwarden/setup/manifests/1.15.1:   unauthorized: incorrect username or password

**Comment by kspearrin** [comment]
Not sure how your docker installation is set up, but there should not be any authentication required to access the registry.

**Comment by turbomettwurst** [comment]
It does not seem to make a difference whether i am logged into docker.io or not.
The error persists, maybe its docker.io having hickups if you didn't set the container to anything but publicly available.

**Comment by turbomettwurst** [comment]
While i still have no idea what went wrong, it did work on a different box.
False Alert, sorry for making a mess :-)
