### ISSUE TITLE
Custom Domain Rule doesn't seem to work

### ISSUE THREAD

**Issue by flandraco** [bitwarden/core#166]
I have an entry for toyota.com; My user name and password are stored with the following URL:
[https://www.toyota.com/owners/login](https://www.toyota.com/owners/login)

So I go to the BitWarden icon in my Chrome browser, type in "Toyota" in the BitWarden search field, it shows me the entry, and I click on the "Launch Website" icon.

This ([https://www.toyota.com/owners/login](https://www.toyota.com/owners/login)) actually redirects to:
https://www.driverslogin.com/tmnab2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_SignupOrSigninToyota_Web&prompt=login&client_id=EDITED_OUT&redirect_uri=https://www.toyota.com/owners/federate-identity&scope=openid&state=EDITED_OUT&response_type=id_token&response_mode=form_post

So now the Password and Login that I had stored no longer are "accessible" through the Bitwarden extension.

Given the URL in the redirection, I was hoping that the following Custom Domain Rule would solve that problem:
toyota.com, driverslogin.com

I would assume that the feature would recognize that "driverslogin.com" is equivalent to "toyota.com", and bring the corresponding entry as active in BitWarden?

That is not the case.

**Comment by kspearrin** [comment]
Did you re-sync after adding the new rule?

**Comment by flandraco** [comment]
I had not. In the past, my vault changes always synced up over my different devices automatically and instantaneously. However, a manual sync indeed did the trick.
Not sure if the settings in the web browser should remind us to do this? My apologies for not thinking about that.
