### ISSUE TITLE
Password with [error: cannot decrypt] make apps fail

### ISSUE THREAD

**Issue by taynaud** [bitwarden/core#168]
Hello,

I do not know how, but I end up with a password in my vault with title '[error: cannot decrypt]' (related to my firefox account I think, the stored password was a big json, do not really understand where it comes from). Maybe the stored password was just too long ?

The main issue is that it makes searching in or opening the directory containing this password impossible from the android application. I was able to browse the directory from the web vault.

Deleting it from the web vault solves the issue (I can search and browse from android app now).

Sorry, I have no idea how to reproduce such password, and since I have deleted it I cannot reproduce the issue.

I post this in "core" repository since it seems related to the "cannot decrypt" issue, but I can post it in mobile app repository if you prefer

Best,

Android app 1.13.0 (1149) on android 7.0

**Comment by kspearrin** [comment]
Please post this in the mobile repo since it seems to be hard failing when crypto fails for one item, which is a problem.
