### ISSUE TITLE
failed to get default registry endpoint

### ISSUE THREAD

**Issue by windysurf** [bitwarden/core#169]

**Comment by windysurf** [comment]
after running ./bitwarden.sh install

Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/info: dial unix /var/run/docker.sock: connect: permission denied).

**Comment by kspearrin** [comment]
Sounds like your machine doesn't have proper access to the outside world. It's trying to connect to docker's website to download the images.
