### ISSUE TITLE
2FA using Google Authenticator

### ISSUE THREAD

**Issue by MaartenStaa** [bitwarden/core#17]
Would it be possible to add support for GA? I already use this for various other things, would be nice to not have to install a separate app.

With some Googling I found this GA implementation for C#: https://github.com/BrandonPotter/GoogleAuthenticator

**Comment by kspearrin** [comment]
Any OTP authenticator app will work today for 2fa on bitwarden already, including Google authenticator.

**Comment by MaartenStaa** [comment]
Ah nice, thanks! Maybe some textual adjustment is needed to clarify this in the Web UI?

**Comment by kspearrin** [comment]
Probably not a bad idea.
