### ISSUE TITLE
env files are world readable in on-prem installation

### ISSUE THREAD

**Issue by sethlyons** [bitwarden/core#170]
this exposes the sa password

```
(/opt/bitwarden/bwdata/env) % ls -l
total 8
drwxr-xr-x  2 root root   57 Dec 18 15:48 .
drwxr-xr-x 12 root root  131 Dec 18 15:50 ..
-rw-r--r--  1 root root 1580 Dec 19 16:40 global.override.env
-rw-r--r--  1 root root   77 Dec 18 15:48 mssql.override.env
```

**Comment by kspearrin** [comment]
If you remove those read permissions does it seem to cause any issues? I think we just need to update the setup installer when those files are initially created to only allow read for current userid.

**Comment by kspearrin** [comment]
these are now `chmod 600` for next release.
