### ISSUE TITLE
Logged out after creating a new account / On premise installation

### ISSUE THREAD

**Issue by Snowrisk** [bitwarden/core#173]
Hi,

i've installed bitwarden at docker at a synology nas.
The installation was fine, but when I fill out the "new account" form and 
hit "Submit" I'm getting this message directly:

![grafik](https://user-images.githubusercontent.com/7990156/34405044-59a1df08-ebb1-11e7-8be6-01343c89dbbe.png)

The new account isn't also created.

-Snowrisk

**Comment by kspearrin** [comment]
What is in your bwdata folder. Looks like you're missing certificates or something, which the installer normally handles for you.

**Comment by Snowrisk** [comment]
![grafik](https://user-images.githubusercontent.com/7990156/34413093-6d79639a-ebe1-11e7-864f-e8efdf2f4924.png)

/bwdata/core/aspnet-dataprotection/Key-**********.xml
/bwdata/core/logs/Jobs/20171228.txt

/docker:
![grafik](https://user-images.githubusercontent.com/7990156/34412938-852cd950-ebe0-11e7-9980-00eeff684f94.png)

/env:
![grafik](https://user-images.githubusercontent.com/7990156/34412947-950bc0de-ebe0-11e7-9240-4dfc98de058f.png)

/identity:
![grafik](https://user-images.githubusercontent.com/7990156/34412952-a0c52cbc-ebe0-11e7-9d9c-817f90b23fab.png)

/bwdata/mssql/data:
![grafik](https://user-images.githubusercontent.com/7990156/34412973-cbd6f05c-ebe0-11e7-840c-af4dc03246de.png)

/bwdata/nginx:
![grafik](https://user-images.githubusercontent.com/7990156/34412992-de28e490-ebe0-11e7-8bd4-932c9f2f72dd.png)

/bwdata/scripts:
![grafik](https://user-images.githubusercontent.com/7990156/34413007-f0383834-ebe0-11e7-8b30-d7acfe50f3e6.png)

/bwdata/ssl/*URL*:
![grafik](https://user-images.githubusercontent.com/7990156/34413018-0676f14e-ebe1-11e7-9fa6-7c324cec4b8c.png)

/bwdata/web:
![grafik](https://user-images.githubusercontent.com/7990156/34413034-220bc9ca-ebe1-11e7-9660-192b3472bf0c.png)

Any not listed folder is empty..

**Comment by kspearrin** [comment]
So you get that message when registering for a new account? Screenshot looks like the login page.

**Comment by Snowrisk** [comment]
Yes. I fill out the "New accoutn" form and hit "Submit". Then the screen changes to the login page with that message in the screenshot.

**Comment by kspearrin** [comment]
That weird. Can you look at dev tools in the browser and see what is happening in the network tab?

**Comment by Snowrisk** [comment]
Found this:
![grafik](https://user-images.githubusercontent.com/7990156/34413397-8e6151d8-ebe3-11e7-918b-cf2ee408ee37.png)

"You don't have permission to access /api/accounts/register"

**Comment by kspearrin** [comment]
Seems something in your configuration is denying access to that proxied request. I would look into your nginx configuration to see why.

**Comment by Snowrisk** [comment]
Can't find something weird (but i'm no pro...)
### 
`# Config Parameters
# Parameter:Ssl=True
# Parameter:SelfSignedSsl=False
# Parameter:LetsEncrypt=False
# Parameter:Domain=[URL]
# Parameter:Url=https://[URL]:444
# Parameter:DiffieHellman=True
# Parameter:Trusted=True

server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name [URL];
  return 301 https://[URL]:444$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name [URL];

  ssl_certificate /etc/ssl/[URL]/certificate.crt;
  ssl_certificate_key /etc/ssl/[URL]/private.key;

  ssl_session_timeout 30m;
  ssl_session_cache shared:SSL:20m;
  ssl_session_tickets off;

  # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
  # ssl_dhparam /etc/ssl/[URL]/dhparam.pem;

  # SSL protocols TLS v1~TLSv1.2 are allowed. Disabed SSLv3
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  # Disabled insecure ciphers suite. For example, MD5, DES, RC4, PSK
  ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:@STRENGTH";
  # enables server-side protection from BEAST attacks
  ssl_prefer_server_ciphers on;

  # OCSP Stapling ---
  # fetch OCSP records from URL in ssl_certificate and cache them
  ssl_stapling on;
  ssl_stapling_verify on;

  ## verify chain of trust of OCSP response using Root CA and Intermediate certs
  ssl_trusted_certificate /etc/ssl/[URL]/ca.crt;

  resolver 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=300s;

  # This will enforce HTTP browsing into HTTPS and avoid ssl stripping attack. 6 months age
  add_header Strict-Transport-Security max-age=15768000;

  # X-Frame-Options is to prevent from click-jacking attack
  #add_header X-Frame-Options SAMEORIGIN;

  # disable content-type sniffing on some browsers.
  add_header X-Content-Type-Options nosniff;

  # This header enables the Cross-site scripting (XSS) filter
  add_header X-XSS-Protection "1; mode=block";

  # This header controls what referrer information is shared
  add_header Referrer-Policy same-origin;

  # Content-Security-Policy is set via meta tag on the website so it is not included here

  location / {
    proxy_pass http://web/;
  }

  location = /app-id.json {
    proxy_pass http://web/app-id.json;
    proxy_hide_header Content-Type;
    add_header Content-Type $fido_content_type;
  }

  location /attachments/ {
    proxy_pass http://attachments/;
  }

  location /api/ {
    proxy_pass http://api/;
  }

  location /identity/ {
    proxy_pass http://identity/;
  }

  location /icons/ {
    proxy_pass http://icons/;
  }
}
`

**Comment by kspearrin** [comment]
try to access https://yourdomain.com/api/now in the browser window. Should print the current time.

**Comment by Snowrisk** [comment]
Works... "2017-12-28T14:35:33.6113786Z"

**Comment by Snowrisk** [comment]
Found it. The issue was on my side.
My firewall's (Sophos) webserver protection worked too good. Have changed it for
this service and now it works.
