### ISSUE TITLE
Can't send verification mail with SSL

### ISSUE THREAD

**Issue by Snowrisk** [bitwarden/core#174]
Hi,

everytime I'll send the verification mail the log shows the following error:

> 
> 2017-12-28 16:32:49.468 +00:00 [Error] Mail send failed.
> System.Net.Mail.SmtpException: Failure sending mail. ---> System.Security.Authentication.AuthenticationException: **The remote certificate is invalid according to the validation procedure.**
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
>    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
>    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticateCallback(IAsyncResult result)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
>    at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
>    at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
>    --- End of inner exception stack trace ---

What should I do to send the mail with ssl? 
The configuration for the mailserver is:

> globalSettings__mail__smtp__ssl=true
> globalSettings__mail__smtp__port=465
> globalSettings__mail__smtp__useDefaultCredentials=false

**Comment by kspearrin** [comment]
Is your mail server setup properly for SSL? Is it using some self signed cert or something?

**Comment by Snowrisk** [comment]
Yes, I think so. It's not mine. It is from my Webhoster and don't use self signed certs.
The smtp server is "sslout.df.eu"

**Comment by kspearrin** [comment]
Arte you sure you are using the correct port? Have you used this mail server elsewhere before?

**Comment by Snowrisk** [comment]
Yes. Using it with my mailclient....

**Comment by kspearrin** [comment]
Not sure, other than you have chosen to ignore an invalid cert on your mail client. Another possible problem could be that the servers system time is way off, creating an invalid cert scenario.

**Comment by biotecs** [comment]
@Snowrisk you should try to use port 587 because 465 is not RFC compliant anymore and there is no working STARTTLS on your providers side yet.

**Comment by kspearrin** [comment]
Is this still a problem or did you fix it?

**Comment by unquietwiki** [comment]
@kspearrin I have a similar problem to @Snowrisk , except that I know for a fact I'm using an internal CA with an SMTP relay. I figure an option in **GlobalSettings.cs** might be worth adding to disable CA-validation, and/or be able to specify the path when using an internal CA?

**Comment by kspearrin** [comment]
@unquietwiki I suppose that use case isn't supported at this time. You would need to have a globally trusted CA for the SMTP relay. Or use non-SSL ports.

**Comment by kspearrin** [comment]
In the next version there will be a `./bwdata/ca-certificates` directory. You can place any `*.crt` files in there and they will be automatically loaded into the trusted store on the docker containers upon start up.

```
cp /etc/bitwarden/ca-certificates/*.crt /usr/local/share/ca-certificates/ \
    && update-ca-certificates
```

This would allow you to use your mailserver without issue.

**Comment by papaxris** [comment]
@biotecs port 587 with my external email provider Worked.  After further analyzing my providers settings, the fine print stated the following:

If your client supports STARTTLS only, you can use port 587 with STARTTLS enabled.

Thank You for pointing me in the right direction.

**Comment by tjyang** [comment]
Hi 
Thanks for this issue thread and help from @kspearrin 
I am adding following notes for future references for myself or others.

[BW on Centos 7 gdoc](https://docs.google.com/document/d/1uYJyWP7Y5tBmr_80TQhyNQ5qfBgbTBUgzmId0_lqyd4/edit#heading=h.vbztno8brhue)

**Comment by edermi** [comment]
Hi
I'm currently trying to get bitwarden to talk to our internal mail relay via SMTP and STARTTLS.

I downloaded the Root and Issue CA and moved the pem-encoded certificate files with filename ending *crt into ~/bwdata/ca-certificates and according to bitwarden script, the certificates are found and put into the trust stores:

```
1.28.0: Pulling from bitwarden/setup
Digest: sha256:e159470596bb2c5531b28727f65ce590722c4c329c901477daa48c9ac61a1ceb
Status: Image is up to date for bitwarden/setup:1.28.0
Updating certificates in /etc/ssl/certs...
2 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.


Bitwarden is up and running!
===================================================

visit https://svpwsafe.hvs-consulting.net
to update, run `./bitwarden.sh updateself` and then `./bitwarden.sh update`

Pausing 60 seconds for database to come online. Please wait...
1.28.0: Pulling from bitwarden/setup
Digest: sha256:e159470596bb2c5531b28727f65ce590722c4c329c901477daa48c9ac61a1ceb
Status: Image is up to date for bitwarden/setup:1.28.0
Updating certificates in /etc/ssl/certs...
2 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

Migrating database.
Beginning transaction
Beginning database upgrade
Fetching list of already executed scripts.
No new scripts need to be executed - completing.
Migration successful.
Database update complete
```

Unfortunately, bitwarden still refuses to connect to the mail server:

```
2018-12-19 12:24:19.742 +00:00 [Error] Mail send failed.
System.Net.Mail.SmtpException: Failure sending mail. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticateCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
```

The weird part: attaching to one of the docker containers (admin in this case) via ` docker exec -i -t d4d5ea9d3a2f /bin/bash` and running `openssl s_client -connect mailserver.fqdn:587 -starttls smtp` works like a charm, so the certificate seems to be there but is ignored by bitwarden or the underlying certificate store.

**Comment by kspearrin** [comment]
> `docker exec -i -t d4d5ea9d3a2f /bin/bash`

which container is this?

**Comment by edermi** [comment]
In this case it was ` bitwarden/admin:1.28.0` (I didn't know which one to take and since I want to send an admin login mail this seemed a legit choice), but I can test in any container if you want to.

**Comment by williampiv** [comment]
Any update on this?

I too am having trouble getting this to work with an internal mail relay. Similar to @edermi , upon connecting to the container directly (bitwarden-api in this case) I get a bunch of errors related to the certificate on the mail server being invalid.

If I use `openssl s_client -starttls smtp -crlf -connect servername:25` I do see valid connectivity, and my certs are also in the bwdata/ca-certificates folder.

Upon running `update-ca-certificates` inside the container in question, I am told there are no new certificates to process, suggesting the root CA I am trying to import has been imported successfully.

**Comment by kspearrin** [comment]
@williampiv Maybe this issue can help? https://github.com/bitwarden/server/issues/451

**Comment by williampiv** [comment]
Hey @kspearrin, thank you for this! Working as desired now.
