### ISSUE TITLE
Self-hosted stopped working giving ERR_SSL_PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by sorcer1122** [bitwarden/core#177]
Hi,

I am running a self-hosted bitwarden on Ubuntu. It was working fine until today when I started getting 'unexpected error' during logging in. I tried to run ./bitwarden.sh update, it has updated web from 1.16 to 1.22 and of course erased my custom config with different nginx ports. I changed the ports back by editing docker-compose.yml, default.conf and run.sh but now I am constantly getting SSL error saying that it is not possible to establish secure connection to the server.

If I do docker ps, I get the following:

bitwarden/nginx:1.16.0         "/entrypoint.sh"         7 minutes ago       Up 7 minutes        80/tcp, 0.0.0.0:7070-7071->7070-7071/tcp

(7070 being HTTP port and 7071 is SSL port). I have no idea where does 80 port comes from, I have got another service there.

If I do docker logs nginx_container_id, I am getting the following:

"\x16\x03\x01\x00\xE5\x01\x00\x00\xE1\x03\x03/\x1C\x8D\xD7\xA1\xE9\x80\xD9y|\x07B\xCE\xCB\xFD\x07\x16\x94r\x9F\xF7-\x11\xF1\x04\xFE?z\xC0\xB7D\x07\x00\x00.\xC0,\xC0+\xC0$\xC0#\xC0" 400 166 "-" "-" "-"

Any ideas where to dig?

**Comment by kspearrin** [comment]
If you set your ports properly using the installer they will not get overwritten when doing updates.

Post your docker-compose.yml please. Looks like you are mapping the ports incorrectly since they should be internally mapped to 80 on the container.

**Comment by sorcer1122** [comment]
@kspearrin setting different ports via the installer did not work for some reason. Here is my docker-compose.yml

# https://docs.docker.com/compose/compose-file/
# Parameter:MssqlDataDockerVolume=False
# Parameter:HttpPort=7070
# Parameter:HttpsPort=7071
# Parameter:CoreVersion=1.16.0
# Parameter:WebVersion=1.22.0

version: '3'

services:
  mssql:
    image: bitwarden/mssql:1.16.0
    container_name: bitwarden-mssql
    restart: always
    volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../mssql/backups:/etc/bitwarden/mssql/backups
    env_file:
      - mssql.env
      - ../env/mssql.override.env

  web:
    image: bitwarden/web:1.22.0
    container_name: bitwarden-web
    restart: always
    volumes:
      - ../web:/etc/bitwarden/web

  attachments:
    image: bitwarden/attachments:1.16.0
    container_name: bitwarden-attachments
    restart: always
    volumes:
      - ../core/attachments:/etc/bitwarden/core/attachments

  api:
    image: bitwarden/api:1.16.0
    container_name: bitwarden-api
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
    env_file:
      - global.env
      - ../env/global.override.env

  identity:
    image: bitwarden/identity:1.16.0
    container_name: bitwarden-identity
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
    env_file:
      - global.env
      - ../env/global.override.env

  icons:
    image: bitwarden/icons:1.16.0
    container_name: bitwarden-icons
    restart: always

  nginx:
    image: bitwarden/nginx:1.16.0
    container_name: bitwarden-nginx
    restart: always
    ports:
      - '7070:7070'
      - '7071:7071'
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl

**Comment by kspearrin** [comment]
```
ports:
- '7070:7070'
- '7071:7071'
```

should be 

```
ports:
- '7070:80'
- '7071:443'
```

**Comment by sorcer1122** [comment]
@kspearrin yeah, I was about to write it. Changing ports to '7070:80' and '7071:443' gives me ERR_CONNECTION_REFUSED. Docker logs nginx_container_id command gives no output.

**Comment by sorcer1122** [comment]
Finally! Once I added the following to my default.conf

ssl_certificate ../letsencrypt/..
ssl_certificate_key ../letsencrypt..

it worked like a charm!

Is there a way to disable updating my config if I ran ./bitwarden.sh update?

**Comment by kspearrin** [comment]
no, but if you just move your certs to the locations that are generated int eh `default.conf` you shouldn't have to worry about modifying it.

**Comment by sorcer1122** [comment]
This is the problem. Certificates are in the correct location but when I run 'bitwarden.sh update', it replaces my default.conf with the default file, without any certificates. Anyway, I will backup my default.conf and will restore it after every update.

**Comment by kspearrin** [comment]
It sounds like the proper parameter comments arnt in place. This info should be at the top if you ran the installer:

```
# Config Parameters
# Parameter:Ssl={Ssl}
# Parameter:SelfSignedSsl={SelfSignedSsl}
# Parameter:LetsEncrypt={LetsEncrypt}
# Parameter:Domain={Domain}
# Parameter:Url={Url}
# Parameter:DiffieHellman={DiffieHellman}
# Parameter:Trusted={Trusted}
```

**Comment by sorcer1122** [comment]
@kspearrin thanks a lot, I had something different in my comments. I am closing this issue now.
