### ISSUE TITLE
Provide crypto disclosure white paper

### ISSUE THREAD

**Issue by code-noggin** [bitwarden/core#183]
Provide a written summary of the what and how encryption is used in bitwarden. It will be useful to share with colleagues to encourage use, and also to share with Steve Gibson.

Steve Gibson is a well recognized security expert and host of the [Security Now! netcast](https://twit.tv/shows/security-now). He has done an [in-depth review](https://www.grc.com/sn/sn-256.htm) of LastPass. His fans have requested that [he do a similar review of bitwarden](https://twitter.com/lebel/status/898618271112548352) to which he [replied](https://twitter.com/SGgrc/status/899888222997626881):

> I've reached out and asked for a crypto disclosure white paper. It's open source, but a summary would save time. :)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/help/issues/26
