### ISSUE TITLE
Feature Request: Shortcut for opening Bitwarden window or auto-type available

### ISSUE THREAD

**Issue by Turbobommel** [bitwarden/core#187]
Hello everybody,

it would be nice if I could trigger the Bitwarden window near the cursor (and choose the right credentials manually). 
Alternative: Auto-type credentials by pressing a custom shortcut.

Thanks!

Best regards.

**Comment by kspearrin** [comment]
Are you describing what is already possible in the context menu?

**Comment by kspearrin** [comment]
And there are keyboard shortcuts already as well; https://help.bitwarden.com/article/auto-fill-browser/

**Comment by Turbobommel** [comment]
No, thats not what I meant.
I know the auto-type feature while entering a website. But there are several websites which are going to fish up the credentials (with javascript) and track the user with these information. Its more meant as a security feature.

Second: While auto-type is off, by pressing the shortcut to open the Bitwarden window (e.g. not in the top right corner in Firefox instead) near the cursor to choose the credentials. It would save me a lot of mouse travelling :-)

**Comment by kspearrin** [comment]
Seems related to https://github.com/bitwarden/browser/issues/3

**Comment by Turbobommel** [comment]
Yes, this would be an alternate cool solution. :-)
