### ISSUE TITLE
Translation to German: Howto?

### ISSUE THREAD

**Issue by labor4** [bitwarden/core#189]
Hi,
how does one contribute localization?
Is there a preferred way to do translations?

I can offer german.
I'd like to see this project grow.

I'm swiss, native german speaking, with experience in tech (web dev), and would like to have a look at the strings, and maybe lean in, if it's doable for my time.

(I'm new to docker though, as for replacement of lang-files on my own on-premise server, to see if the style is correct, i'd need some help)

thanks
best
manu

**Comment by kspearrin** [comment]
Please see https://help.bitwarden.com/article/localization/ . There is no localization available for the web app at the moment. Only browser extension and mobile.

**Comment by labor4** [comment]
ok thanks, couldn't find that.
