### ISSUE TITLE
Multi-domain sites

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/core#19]
Some organizations have login credentials that are shared across multiple domains. For example, your apple id can be used to log into apple.com and icloud.com. The autofill services will only recommend logins for a single domain currently. Need to figure out a way to allow multiple domains to be associated with a site.

**Comment by kspearrin** [comment]
This is now available to be configured in the web vault. Will be available in browser with v1.9.x

**Comment by kruge002** [comment]
How can this be configured in the webvault, browser or mobile. I cannot find anything about this feature in the Help pages. Neither in the Tools section or the Options section. I would like to link two or more entries toegether so they share the same password.

**Comment by kspearrin** [comment]
@kruge002 Edit the item and select "+ Add URI".
