### ISSUE TITLE
Development environment setup?

### ISSUE THREAD

**Issue by cskwrd** [bitwarden/core#194]
Is there any guidance on setting up an environment for development? 

From the README, it looks as though we should be able to run it like any other application. However, it seems there are missing settings in the appsettings.json file found in the API project. The fact that the build scripts build docker images makes me think that maybe we are supposed to create docker images and deploy those like an on-prem deployment. Is that correct?

Is the database initialization supposed to be a manual process using the dacpac generated on build by the Sql project?

**Comment by kspearrin** [comment]
For development I do not use Docker. You will need to provide credentials for the various dependencies in appsettings.json (I use the user secrets file for ASP.NET). Or you can also just swap out some of those dependencies for their `Noop` implementations (see `Core/Services/NoopImplementations` and `Core/Utilities/ServiceCollectionExtensions` to avoid that altogether (probably best for just getting started).

**Comment by kspearrin** [comment]
As for SQL, you can use the Sql project to generate and seed a database either by dacpac or right click > Import > Database (this is the method I use).
