### ISSUE TITLE
Docker containers "bitwarden-api" and "bitwarden-identity" restarting

### ISSUE THREAD

**Issue by dpwv** [bitwarden/core#197]
The docker containers "bitwarden/api:1.16.0" and "bitwarden/identity:1.16.0" won't start while running `./bitwarden.sh install` - they are always restarting in a loop.
All other containers seem to be running.

`docker ps` gives this output:

```
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS                           PORTS                                      NAMES
9c959706a609        bitwarden/icons:1.16.0         "/entrypoint.sh"    13 seconds ago      Up 10 seconds                    80/tcp                                     bitwarden-icons
27ed314fa856        bitwarden/attachments:1.16.0   "/entrypoint.sh"    13 seconds ago      Up 12 seconds                    80/tcp                                     bitwarden-attachments
c15c4df8d377        bitwarden/api:1.16.0           "/entrypoint.sh"    13 seconds ago      Restarting (134) 2 seconds ago                                              bitwarden-api
200af9889c7e        bitwarden/nginx:1.16.0         "/entrypoint.sh"    13 seconds ago      Up 12 seconds                    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   bitwarden-nginx
198f89c9eb51        bitwarden/mssql:1.16.0         "/entrypoint.sh"    13 seconds ago      Up 11 seconds                    1433/tcp                                   bitwarden-mssql
7dac925ed3c1        bitwarden/identity:1.16.0      "/entrypoint.sh"    13 seconds ago      Restarting (134) 1 second ago                                               bitwarden-identity
9fdb73aca6d1        bitwarden/web:1.22.0           "/entrypoint.sh"    13 seconds ago      Up 13 seconds                    80/tcp                                     bitwarden-web
```

When I start the containers manually by `docker-compose -f ./bwdata/docker/docker-compose.yml up` I get the following logs (attached).

[bitwarden_docker_errors.log](https://github.com/bitwarden/core/files/1664261/bitwarden_docker_errors.log)

At first I was using a VServer with 1 core, 2GB RAM and 20TB storage. I upgraded to a VServer with 2 cores, 4GB RAM and 40GB storage, but the problem still exists.

**Comment by kspearrin** [comment]
Look in your environment variables file. You've got the value `no` somewhere that should be `false`.

**Comment by dpwv** [comment]
omg... No idea why I did this, but this was exact the problem: I used `no` except of `false` in `./bwdata/env/global.override.env` indeed...

Thanks Kyle for the fast solution 👍 

PS: great product btw & good work! The only thing I'm missing from KeePass is [Subdmain support #77](https://github.com/bitwarden/browser/issues/77) - though it didn't prevent me to buy a subscription for bitwarden ;)
