### ISSUE TITLE
Changes in global.override.env gets ignored

### ISSUE THREAD

**Issue by RogerSik** [bitwarden/core#198]
Hello,

after installation, setup and registration I wanted to change the SMTP variable and set disableUserRegistration to true.
It is changed but its get ignored. Example I can still register new accounts.
Did I something wrong or can I edit this only once?

**Comment by kspearrin** [comment]
Did you restart?

**Comment by RogerSik** [comment]
Ok my fault. The registration is disabled but the menu for Registration is still accessible. I thought it get hidden. Sorry!
