### ISSUE TITLE
Shared items appear in "No Folder"

### ISSUE THREAD

**Issue by scifire91** [bitwarden/core#201]
The Shared items from our Organisation appear in the users vault for one thing under "No Folder" and secondly under the collection which is shared.
So all items are doubled in the users vault. 
Would be nice when the items won´t appear under "No Folder" but don´t know if this is possible by design.

**Comment by kspearrin** [comment]
Folders and collections are two different things. This is by design. Perhaps we just need a better UI that doesn't display them side by side.

**Comment by scifire91** [comment]
i´ve opened a feature request in the forum for this. 
https://community.bitwarden.com/t/improve-ui-for-shared-items/96?u=scifire91

**Comment by VerisZG** [comment]
I also support the idea that shared items should not be mixed with personal items. Items in collections should not be visible in "no folders".
