### ISSUE TITLE
Store history of passwords

### ISSUE THREAD

**Issue by viertaxa** [bitwarden/core#202]
Currently, when a password is updated, you loose access to the previous password.  This is a major issue when your password is not accepted for some reason. (E.g. undisclosed password length limit)

I would like to request that a password history function be scoped for inclusion into bitwarden. I picture the functionality to look like the below (rough) mockup. This would be an extremely useful feature.

Edit: I can't get Github to take my images, so here's an imgur link: https://imgur.com/a/HXiY0

**Comment by nopynoop** [comment]
It's a good idea. Even Lastpass has the password history logs.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/core/issues/33
