### ISSUE TITLE
[QUESTION]What happens with shared items if user departed from Org

### ISSUE THREAD

**Issue by scifire91** [bitwarden/core#206]
Hey,
what happens with an item a user shared with the an Organization Collection after he leaves the Org? 
Is that right that this Item will disappear from the Collection?

**Comment by pauldalewilliams** [comment]
I've wondered about this as well.

**Comment by kspearrin** [comment]
Shared items belong to the org, not the user. If a user leaves or is deleted the items will stay in the org.
