### ISSUE TITLE
Disable registration future in the docker files

### ISSUE THREAD

**Issue by DenDeze** [bitwarden/core#216]
Global settings disable registration does not work.

**Comment by kspearrin** [comment]
It does.

**Comment by paescuj** [comment]
@kspearrin: You're right. But if I remember correctly, the registration link on the login page is still available, which is a bit confusing.

**Comment by kspearrin** [comment]
Yes, the setting will only affect the server API, not the website.

**Comment by paescuj** [comment]
In my opinion, it would definitly make sense to hide the registration link if the registration is disabled. As I already said it is a bit confusing. I'll try to create a PR.

**Comment by poblabs** [comment]
Any progress on this? Having that link available - even if registration is disabled - is very misleading. The UI should be in sync with the feature being enabled/disabled.
