### ISSUE TITLE
using appveyor for CI/T/R

### ISSUE THREAD

**Issue by stephengroat** [bitwarden/core#22]
has there been any thought to using [appveyor](www.appveyor.com) for continuous build/test/release? i've don some work for [unicorn engine](www.unicorn-engine.org) using appveyor, but i'd like to gauge interest before investing time for this project!

**Comment by kspearrin** [comment]
I've set up appveyor before on these repositories a while back, I just didn't keep it up. It would probably be a good idea to bring it back. I could set it up pretty quickly.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/core/commit/2d045859e7e3fe3b7ddcb15f292f19117e9f5dcc
