### ISSUE TITLE
Import from KeePass is missing attachments

### ISSUE THREAD

**Issue by dkunzler** [bitwarden/core#223]
**Environment**
Self hosted Docker environment.
Before importing I purchased premium and added the premium license file to my on-premise installation.
I then made sure that I am able to save attachments.

**What happened**
After that I imported my KeePass database from xml (the xml contains the binary attachments as base64 encoded strings) and everything worked but the attachments.
None of the imported entries has the attachment that was set on KeePass.

**What should happen**
When a KeePass file contains binary attachments and the user has a premium account these attachments should also be added to the bitwarden instance to the respective entry.

**Comment by kspearrin** [comment]
This should be opened on the web project, which is where the importer lives. https://github.com/bitwarden/web

**Comment by dkunzler** [comment]
Ok, didn't know the import is on the client side. Opened an issue there.

**Comment by kspearrin** [comment]
Yes, all logic involved with handling secrets has to be processed client side since no sensitive data is ever sent to the server.
