### ISSUE TITLE
Templates for secure notes

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/core#224]
LastPass (I don't use it, I just have one demo password in my vault to test the functionality) also has secure notes but LastPass has different types of secure notes.
Each Type has pre-defined data fields that I can fill (I do not have to add these fields manually).

So I can add for example:
- custom note (just one huge edit field)
- software licences 
- email accounts
- bank accounts
- servers
- WIFI passwords
- (many other types)

It would be fantastic when Bitwarden also has different types of secure notes.
So I can create a secure note of the type "Email Account" and have all required fields there.
But I also can add custom fields (if something is missing).

**Here is how this looks in LastPass.**

Selecting the type of secure note:

![lastpass_securenote_01_select_type](https://user-images.githubusercontent.com/8037790/37058020-7971858c-2189-11e8-87ae-2eec0efcb15f.png)

Adding an Email Account:

![lastpass_securenote_02_email-account](https://user-images.githubusercontent.com/8037790/37058089-a53b7bfa-2189-11e8-85f6-371e395a4b95.png)

Adding a Software License:

![lastpass_securenote_03_software-license](https://user-images.githubusercontent.com/8037790/37058117-b7d71378-2189-11e8-8d9d-bd793b206663.png)

Adding a Bank Account:

![lastpass_securenote_04_bank-account](https://user-images.githubusercontent.com/8037790/37058153-dc0ba0ba-2189-11e8-93ed-f87890d2d550.png)

**Comment by mackaaij** [comment]
Looks like this is the specific feature request on the forum:
https://community.bitwarden.com/t/enhance-secure-note-functionality/102/7

Although it looks like a better idea to vote for this sort of duplicate one (which gathered more votes):
https://community.bitwarden.com/t/add-more-pre-defined-item-types/228
