### ISSUE TITLE
Quick Add Folder

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/core#226]
When I edit an entry and select a target folder please add an entry "New Folder" to the drop down list.
When I select this entry, a popup is shown where I can enter the name of the new folder.
This increases the usability a lot (saves many mouse clicks).

**Comment by kspearrin** [comment]
This is an app specific feature, not core.

**Comment by OLLI-S** [comment]
So should I add this suggestion for each app (also the browser) now?

**Comment by kspearrin** [comment]
Sure. I think its been suggested already in some though so please check.
