### ISSUE TITLE
Hotkey(s) on Mac OS 10.13.3 not working

### ISSUE THREAD

**Issue by torstenb** [bitwarden/core#229]
I am using bitwarden in Safari 11.0.3 (13604.5.6) and Chrome 65.0.3325.146 (Official Build) and in neither do the hot keys Cmd+Shit+L or Cmd+/ work.

**Comment by kspearrin** [comment]
Please use the correct repo for whatever app you are experiencing this problem with. I believe you are looking for browser. https://github.com/bitwarden/browser
