### ISSUE TITLE
Server side licenses

### ISSUE THREAD

**Issue by a-m-s** [bitwarden/core#23]
Kudos for respecting users' freedom and choosing the GPL for your project.

However, may I suggest switching to the AGPL for the server-side components? It's the same but for code which is used but not "distributed" in the usual sense.

https://www.gnu.org/licenses/licenses.html#AGPL

**Comment by kspearrin** [comment]
Thanks for the suggestion. Can you explain what specifically AGPL will allow you to do that GPL will not? I am just trying to understand specific use cases for users.

**Comment by a-m-s** [comment]
The page I linked probably says it better than I can, but the basic point is that the regular GPL only requires you to give the sources to anybody who has the binaries. For client-side applications this works great, but for server-side applications the client _uses_ the software, but does not _have_ the binaries, so the GPL means nothing.

The Affero GPL has an extra clause that says that hosted services must offer their sources for download.

For you, there's no difference -- you plan to do so anyway -- but it becomes important if somebody chooses to clone your service and self-host, possibly even in competition. You can't stop them doing that, but with the AGPL you _can_ insist that they share their modified sources.

**Comment by kspearrin** [comment]
Ok, thanks. I will keep this in mind and revisit it after doing a bit of research.

**Comment by a-m-s** [comment]
Always caution with licenses! :-)

However, also bear in mind that it's easy to change the license when you are the only contributor, but you need approval from all copyright holders if you want to change it later.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/core/commit/7e5679784786f9b93009c65540b7f6050c7e5c63

Thanks for the suggestion.
