### ISSUE TITLE
Updated self host and passwords are empty

### ISSUE THREAD

**Issue by pdarcos** [bitwarden/core#236]
Hi all,

I just updated my self-hosted installation (was from October/November last year and was working fine).
Running debian VPS and after the update I can login but there's no logins in there anymore.

I really hope the DB didn't become corrupted and I lost all my passwords. How can I debug this and try to get my data back?

I see on the iOS client that all the passwords are still there (i put in into airplane mode so it doesn't sync and become blank) but how can I export them?

Thanks

**Comment by kspearrin** [comment]
Your update script likely failed to execute the `updatedb` command. Just run `updatedb` manually.

`./bitwarden.sh updatedb`

**Comment by pdarcos** [comment]
Thanks @kspearrin 

Unfortunately it's not so simple. The db updates as expected but when I login my data is all gone.


Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.16.1, build 6d1ac21

1.17.1: Pulling from bitwarden/setup
Digest: sha256:6bd038cd624309b11d85f31943ce401b15aed813faddffdcc616f3acea84ebd4
Status: Image is up to date for bitwarden/setup:1.17.1
Migrating database.
Beginning transaction
Beginning database upgrade
Fetching list of already executed scripts.
No new scripts need to be executed - completing.
Migration successful.
Database update complete


Where are logs can I look at to try and get my data back?

**Comment by kspearrin** [comment]
So no errors occurred during the entire upgrade process?

> I can login but there's no logins in there anymore.

Can you give a little more info on what you are actually seeing? Is this in the web vault? Have you tried clearing browser cache incase it's loading some old assets from the previous web vault? What does the dev tools in the browser show when its calling the server?

Server logs are in `./bwdata/core/logs`

**Comment by pdarcos** [comment]
Thanks @kspearrin 
This project has some of the best support in the FOSS world.
Very impressed.

indeed the problem was simple the browser's cache. After clearing it the data is back (yes this was all in webvault).

Thanks again!
