### ISSUE TITLE
Installing bitwarden issues with different ports behind proxy and missing folders

### ISSUE THREAD

**Issue by stevenhrabok** [bitwarden/core#244]
Hello,

I've been testing out deployment of bitwarden using the bitwarden.sh script on a Synology DSM. I've managed to complete an install by manually changing docker-compose.yml as well as creating missing folders.

I'm wondering if my understanding of the prompts is being interpreted wrong for my setup.

Currently I am attempting the following deployment:

**Synology Reverse Proxy in front of bitwarden**
bw.domain.com:80 -> localhost:8223 (hoping bitwarden redirects on x-forwarded-proto to https)
bw.domain.com:443 -> localhost:8223 (using certificate on synology for bw.domain.com for ssl offload)

**Run bitwarden.sh install**
Enter domain: bw.domain.com
Use Let's Encrypt: n
Do you have an SSL certificate to use: n
Do you want to use the default ports (80/443): n
HTTP port: 8223
Installation behind reverse proxy: y
Default ports (80/443) on your reverse proxy: y
Push notifications: y

From this point, ports in the docker-compose.yml end up being 80 and 443 which clash with synology's webservers, which I had to manually change to 8223 and 8243 as a workaround.
I'm under the impression 80 and 443 should have changed in the docker-compose.yml for the host ports. And really 443 should be removed if behind a reverse proxy with ssl-offload.

**Run bitwarden.sh start**
Pulls containers
Starting containers
Fails with bind mount errors for missing folders:
```
ERROR: for api  Cannot start service api: Bind mount failed: '/volume1/docker/bwdata/core' does not exists
ERROR: for attachments  Cannot start service attachments: Bind mount failed: '/volume1/docker/bwdata/core/attachments' does not exists
ERROR: for identity  Cannot start service identity: Bind mount failed: '/volume1/docker/bwdata/core' does not exists
ERROR: for mssql  Cannot start service mssql: Bind mount failed: '/volume1/docker/bwdata/mssql/backups' does not exists
```

seems not all the folders are being created. If I manually create the folder structure the containers will run. This is the current existing folders after setup:
```
root@nas:/volume1/docker# ll bwdata/
total 36
drwxr-xr-x+ 8 root root 4096 Mar 26 14:35 .
drwxr-xr-x+ 5 root root 4096 Mar 26 14:34 ..
drwxr-xr-x+ 2 root root 4096 Mar 26 14:36 docker
drwxr-xr-x+ 2 root root 4096 Mar 26 14:35 env
drwxr-xr-x+ 2 root root 4096 Mar 26 14:35 identity
drwxr-xr-x+ 2 root root 4096 Mar 26 14:35 nginx
drwxr-xr-x+ 2 root root 4096 Mar 26 14:34 scripts
drwxr-xr-x+ 2 root root 4096 Mar 26 14:35 web
```

Other issue found after the manual changes, the email sent still shows http:// instead of https:// for the application base url. As a result since the nginx config doesn't redirect on http to https it will be insecure in its connection.

Can anyone assist or help clarify if the process I'm using is wrong for bitwarden behind a reverse proxy with ssl offload. And the missing folders, could this be a result of an unsupported system (synology) or am I encountering something different.

Thank you

**Comment by kspearrin** [comment]
> Synology Reverse Proxy in front of bitwarden
> bw.domain.com:80 -> localhost:8223 (hoping bitwarden redirects on x-forwarded-proto to https)
> bw.domain.com:443 -> localhost:8223 (using certificate on synology for bw.domain.com for ssl offload)

Why are both going to the same port?

Can you provide the contents of your docker-compose.yml?

**Comment by stevenhrabok** [comment]
Hi @kspearrin 

From what i understood from the prompts, only one port was being used and I was under the impression the nginx container was looking for x-forwarded-proto and if it wasn't https it would redirect to https like this:

```
if ($http_x_forwarded_proto != "https") {
    rewrite ^ https://$http_host$request_uri? permanent;
}
```

If there was two ports requested I would assume a server block doing the redirect to https.
The prompts only requested a single port when replying "no" to any ssl. Here are the prompts:
```
root@nas:/volume1/docker# ./bitwarden.sh install
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2018, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================


Docker version 17.05.0-ce, build 9f07f0e-synology
docker-compose version 1.14.0, build c7bdf9e

(!) Enter the domain name for your bitwarden instance (ex. bitwarden.company.com): bw.domain.com
(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n
1.17.2: Pulling from bitwarden/setup
Digest: sha256:cf55e0288b6392ee9c35022089396c3c561773ddc963945f1afea8fce359757f
Status: Image is up to date for bitwarden/setup:1.17.2
(!) Enter your installation id (get it at https://bitwarden.com/host): <my_installation_id>
(!) Enter your installation key: <my_installation_key>
(!) Do you have a SSL certificate to use? (y/n): n
(!) Do you want to generate a self-signed SSL certificate? (y/n): n
!!!!!! WARNING !!!!!!
You are not using an SSL certificate. Bitwarden requires HTTPS to operate. You must front your installation with a HTTPS proxy. The web vault (and other Bitwarden apps) will not
work properly without HTTPS.
!!!!!!!!!!!!!!!!!!!!!
Generating key for IdentityServer.
Generating a 4096 bit RSA private key
....................................................................................++
......................................++
writing new private key to 'identity.key'
-----
(!) Do you want to use the default ports for HTTP (80) and HTTPS (443)? (y/n): n
(!) HTTP port: 8223
(!) Is your installation behind a reverse proxy? (y/n): y
(!) Do you use the default ports on your reverse proxy (80/443)? (y/n): y
(!) Do you want to use push notifications? (y/n): y
Building nginx config.
Building docker environment files.
Building docker environment override files.
Building app settings.
Building FIDO U2F app id.
Building docker-compose.yml.

Setup complete
```

And from this I assumed the docker-compose.yml would contain the 8223 port, but instead still shows 80 and 443.

docker-compose.yml
```yml
# https://docs.docker.com/compose/compose-file/
# Parameter:MssqlDataDockerVolume=False
# Parameter:HttpPort=80
# Parameter:HttpsPort=443
# Parameter:CoreVersion=1.17.2
# Parameter:WebVersion=1.24.1

version: '3'

### REMOVED Unnecessary Code ###
### See attachment ###

  nginx:
    image: bitwarden/nginx:1.17.2
    container_name: bitwarden-nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl
```

also some of those mounts (letsencrypt, ssl) fail because the folders do not get created (as per original post)


[docker-compose.yml.txt](https://github.com/bitwarden/core/files/1856244/docker-compose.yml.txt)

**Comment by kspearrin** [comment]
Did you mean to close this issue?

**Comment by stevenhrabok** [comment]
Bad click on my part, I did not want to close.

**Comment by kspearrin** [comment]
Can you try the latest beta version and see if it is fixed there? I just tested your exact prompts on it and it seemed to work correctly.

Just modify your bitwarden.sh script and set the versions as "beta" and do a new install.

**Comment by stevenhrabok** [comment]
Seems that worked for the docker compose port, but starting fails with missing directories still:

```
Creating bitwarden-nginx ... error

Creating bitwarden-mssql ... error

Creating bitwarden-admin ... error

Creating bitwarden-attachments ... error

Creating bitwarden-identity ... error

Creating bitwarden-api ... error

ERROR: for bitwarden-api  Cannot start service api: Bind mount failed: '/volume1/docker/bwdata/core' does not exists

ERROR: for attachments  Cannot start service attachments: Bind mount failed: '/volume1/docker/bwdata/core/attachments' does not exists

ERROR: for admin  Cannot start service admin: Bind mount failed: '/volume1/docker/bwdata/core' does not exists

ERROR: for nginx  Cannot start service nginx: Bind mount failed: '/volume1/docker/bwdata/logs/nginx' does not exists

ERROR: for api  Cannot start service api: Bind mount failed: '/volume1/docker/bwdata/core' does not exists

ERROR: for mssql  Cannot start service mssql: Bind mount failed: '/volume1/docker/bwdata/logs/mssql' does not exists

ERROR: for identity  Cannot start service identity: Bind mount failed: '/volume1/docker/bwdata/core' does not exists
ERROR: Encountered errors while bringing up the project.
```

current directories in bwdata
```
root@nas:/volume1/docker# ll bwdata/
total 44
drwxr-xr-x+ 10  999  999 4096 Mar 28 13:16 .
drwxr-xr-x+  5 root root 4096 Mar 28 13:15 ..
drwxr-xr-x+  2  999  999 4096 Mar 28 13:16 docker
drwxr-xr-x+  2  999  999 4096 Mar 28 13:16 env
drwxr-xr-x+  2  999  999 4096 Mar 28 13:16 identity
drwxr-xr-x+  2  999  999 4096 Mar 28 13:15 letsencrypt
drwxr-xr-x+  2  999  999 4096 Mar 28 13:16 nginx
drwxr-xr-x+  2  999  999 4096 Mar 28 13:15 scripts
drwxr-xr-x+  2  999  999 4096 Mar 28 13:15 ssl
drwxr-xr-x+  2  999  999 4096 Mar 28 13:16 web
```

**Comment by kspearrin** [comment]
I am not sure what issues may exist with bind mounting on a Synology device. Maybe you need to create all bound folders manually?

**Comment by stevenhrabok** [comment]
Because some of the directories exists i was under the impression these should be created by the scripts for setup? 
This could be synology related, but not sure why the same issues wouldn't be occurring on any linux build? 
I can always manually create these folders but wanted to be sure this wasn't something expected of the setup or installers.

**Comment by kspearrin** [comment]
Docker is suppose to create those folder automatically when the instances start up since they are bound volumes. This happens normally so it would seem specific to this device.

**Comment by stevenhrabok** [comment]
I'd agree, likely the synology provided docker probably is behind or just half baked like a lot of their customizations
```
root@nas:/volume1/docker# docker --version
Docker version 17.05.0-ce, build 9f07f0e-synology
root@nas:/volume1/docker# docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
```

I wanted to clarify after creating the directories needed the bitwarden service was running. I did notice (and I can create another ticket if you like) http does not redirect to https and the configs default to http:// instead of https://.

Is there any way to have the base url know the proto and for any incomming traffic on http to redirect to https. Or can I close the port 80 all together if using a proxy on 443.

**Comment by kspearrin** [comment]
Looks like those docker versions are pretty outdated.

This would have to be something you handle in your proxy. In the configuration you are using we simply expose port 80 and that's it.

**Comment by stevenhrabok** [comment]
With the synology proxy setup they have they only do direct pass through (which is not your problem to be honest) more just a consideration of something to consider.
As for how things work in that case, is everything defaulting to port 80?
If so I think thats a bit of a concern since every request goes to an insecure port to be redirected instead of just hitting the https service directly.

**Comment by stevenhrabok** [comment]
Or I guess another way to put it is, is there a way to set the base url to default to https:// instead of http when sending out verification links and other things like that?

**Comment by kspearrin** [comment]
I suppose that use case isn't handled at the moment. Since you are configured for an HTTP only installation we assume all things are handling at your front facing proxy. Feel free to open a new issue if you want to track that.

**Comment by stevenhrabok** [comment]
Thanks @kspearrin will do, before creating the new issue, does the https:// baseurl seem like another feature request?

**Comment by kspearrin** [comment]
That's really a development issue/bug, not a feature request. So you can open it here on GitHub.

**Comment by stevenhrabok** [comment]
Closing ticket and providing overview:
- Self hosted bitwarden behind proxy with ssl offload feature request found here: (https://community.bitwarden.com/t/when-providing-proxy-infront-of-self-hosted-deployment-redirect-http-to-https/524)
- Have base url set to https:// when behind proxy with ssl offloading (changed in latest beta)
- Bind mounts fail for directories that do not exist (likely synology docker version is out of date or does not support creating directories on bind mounts, manual creation of directories is the current workaround)

**Comment by jsalts** [comment]
I also ran into the bind mounts not existing. For maximum portability between all system, your setup scripts should probably be creating the bind mount directories and not relying on docker to create them. Additionally, bind mounts are inherently not portable. This issue would also be mitigated by just using volume mounts instead, which docker supports.
