### ISSUE TITLE
Bitwarden doesn't seem to recognize using a Dockerized SMTP instance

### ISSUE THREAD

**Issue by unquietwiki** [bitwarden/core#247]
I spent the better part of my workday trying to [rebuild a Dockerized Postfix instance](https://github.com/unquietwiki/docker-postfix-relay), to work around some of the other reported SMTP bugs. That being said; no matter how I configure **bwdata/env/global.override.env** (using localhost, or 172.x address), the Postfix instance doesn't detect attempts from Bitwarden. I can use netcat to verify connectivity on the same Docker host though. Using an updated [Photon 2.0 VM](https://github.com/vmware/photon) for Docker hosting.

**Comment by kspearrin** [comment]
Is there anything logged on Bitwarden's side about SMTP when you try?

**Comment by unquietwiki** [comment]
@kspearrin here's an attached logfile, with different addresses tried. And relevant config segment

[20180328.txt](https://github.com/bitwarden/core/files/1857136/20180328.txt)

```
globalSettings__mail__smtp__host=172.17.0.1
globalSettings__mail__smtp__username=REPLACE
globalSettings__mail__smtp__password=REPLACE
globalSettings__mail__smtp__ssl=false
globalSettings__mail__smtp__port=25
globalSettings__mail__smtp__useDefaultCredentials=true
```

**Comment by kspearrin** [comment]
It seems the api container is not able to reach the endpoint for your mail container. You likely need to add it to the docker network for the bitwarden containers.

**Comment by unquietwiki** [comment]
@kspearrin Thanks for the tip. After some debugging, I got the SMTP container to join the default bridge network on 172.18.x; can also ping it from the API container; **iptables -t nat -L** is good at indicating what IPs stuff ended up at, and the "smtp" ID works.

Interestingly enough, now Bitwarden can't be restarted without deleting & re-adding my SMTP container. Not sure if bug or feature?

**Comment by kspearrin** [comment]
The bridge is torn up/down each time the services come online. This is all managed by `docker-compose` (we just do `docker-compose up`). You can try modifying the compose file configuration by creating a `docker-compose-override.yml` in the docker dir.

**Comment by unquietwiki** [comment]
(nods) If it gets to be a problem, I'll do that. Rebooting the Docker VM appears to have both sets of software come up fine, so it's only an issue if yours has to be restarted / upgraded. Thinking about it, I could even probably make a bash script to handle a clean "rebuild". Thanks for helping me figure this out. 👍

**Comment by unquietwiki** [comment]
@kspearrin Follow-up on this: I reconstructed my Docker container attempt as https://github.com/unquietwiki/knobby-docker-postfix , and verified that Bitwarden delivers through it. 👍
