### ISSUE TITLE
Bitwarden behind proxy defaults to http:// for base url in emails etc

### ISSUE THREAD

**Issue by stevenhrabok** [bitwarden/core#248]
When self hosted bitwarden is behind a user hosted proxy and user sends email for verification, the default url provided in the verification link is http:// instead of https://.

Can the base url be changed to https:// in a configuration or can it detect the current user session proto and inject the proto into the url on email generation?

Example:

Connect to https://bw.domain.com, login and send verification email.

Emails contains url with http
```
Verify this email address for your Bitwarden account by clicking the following link. If you did not request this email to verify a Bitwarden account, you can safely ignore it.

http://bw.domain.com/#/verify-email?userId=<my_user_id>&token=
<token>
```

**Comment by kspearrin** [comment]
This only happens whenever you are only using HTTP. We assume people will configured the HTTPS redirect at the proxy at the moment, but I realize that isn't possible with your setup.

A workaround here would be to use a HTTPS configuration with a self signed cert. Then HTTPS urls would be used.

**Comment by stevenhrabok** [comment]
Ok so just for clarity and confirmation:

https://bw.domain.com -> https://localhost:8443 (self signed cert on bitwarden-nginx container)
baseurl is now https://bw.domain.com

**Comment by kspearrin** [comment]
Correct.

**Comment by kspearrin** [comment]
This is now properly supported in the latest beta. Give it a try.

**Comment by stevenhrabok** [comment]
Works great! Thanks @kspearrin
