### ISSUE TITLE
Hosting On-Premise?

### ISSUE THREAD

**Issue by willemdh** [bitwarden/core#25]
Is there any guide how to install Bitwarden on premise?

**Comment by kspearrin** [comment]
Currently there is no documentation on this, so you'll have to just figure it out if you want to do that now (shouldn't be too hard if you have any .NET experience). I can answer any specific questions if needed. 

I know this isn't ideal, however, so this is something we are working on for the future to make easy with a simple installer or container deployment that will give people options between platform (windows, unix) and database engine (sql server, mysql, etc).

**Comment by willemdh** [comment]
@kspearrin  My .NET knowledge is limited though, so I fear I won't be much help. Looking forward to container solution.

**Comment by bspradling8** [comment]
Is there an ETA on this? This is something I would be very interested in. A docker container would be amazing.

**Comment by kspearrin** [comment]
Unfortunately no ETA, but it is one of our top priorities since this is required for our enterprise offerings.

**Comment by missionrulz** [comment]
Some basic documentation on what is needed for installation or a Docker image would be greatly beneficial. I am eager to try this out, however without any install docs, it will be quite the struggle for those of us who operate in a unix environment.

**Comment by mongrelion** [comment]
I'm also interested in the possibility of running this on-premise.
Last time that I touched .NET was in 2009 so I'm quite rusty but I just tried installing the dependencies for most all the subprojects and all of them work but the `Sql` one.
This is the output:
```
dotnet restore
/usr/src/bitwarden/src/Sql/Sql.sqlproj(59,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/1.0.1/Microsoft/VisualStudio/v12.0/SSDT/Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

I see I need some SQL Server Data Tools? Not sure how to install this in the container where I'm running this

A little more info:
```
$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

So, any idea on how to get the SSDT in the container? Apparently there is no official Debian package for mssql-tools, which I guess is what's got the deps but I'm all over the place now.

**Comment by kspearrin** [comment]
@ mongrelion  You only need to run the API project in the solution which should not have a dependency on the Sql project.

**Comment by christianreiss** [comment]
All of this screams docker.

**Comment by kspearrin** [comment]
@christianreiss That's the plan.

**Comment by computer-spezialisten-de** [comment]
Since there is no possibility to add a custom serveradress in android and ios app it make no sense to use an own server. Or i'm wrong?

**Comment by kspearrin** [comment]
Without modifying those builds as well, that is correct. That will also be part of these updates.

**Comment by mongrelion** [comment]
@christianreiss @kspearrin I am running all this in a Docker container.
I tried out first with the `microsoft/dotnet:1.1.1-sdk` image but that didn't work out. Installing the dependencies with `dotnet restore` worked but when trying to run the app with `dotnet run` it fails.
Here's the error message:
```
$ cd /path/to/bitwarden/src/Api
$ dotnet run
/usr/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/usr/src/bitwarden/src/Api/Api.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for '/usr/src/bitwarden/src/Core/Core.csproj'. This can indicate a missing project reference. [/usr/src/bitwarden/src/Api/Api.csproj]

The build failed. Please fix the build errors and run again.
```

@kspearrin I guess I need to run this in the `microsoft/aspnetcore` image? The problem is that I'm on an OSX machine because the aspnetcore image is a Windows container if I got it right, and that doesn't run natively with Docker for Mac. So, yeah, waiting to get a little time to boot a Windows machine with Vagrant, install Docker and try it out there. Seems like a lot of hassle.

Maybe a good couple of questions to ask are: what are the specific requirements for building & running the app *and* how to build & run the app?

Cheers

**Comment by kspearrin** [comment]
@mongrelion Normally this would work, however, since you are trying to run on macOS, task #3 is blocking you.

**Comment by mongrelion** [comment]
Cheers!

I'm subscribing then to the other thread as well so that when that's done I can give this another go.

**Comment by Zakay** [comment]
Would be awesome to have a docker container! (subscribing)

**Comment by christianreiss** [comment]
.... ssssso? Any progress at all? Open Sourcing is nice, but without the ability to use it it's value is diminished...

**Comment by jimmyjam6916** [comment]
I'd like to second that sssso! I need a fully working solution soon that I can self host, was really hoping I could use this. One question that hopefully could be answered now, when we do get the ability to roll our own, will it be with full functionality and options immediately that the hosted version has at that time? And moving forward afterwards, will new features or enhancements be released to both at the same time? Or maybe even we could get the ability to beta test new features!?

**Comment by kspearrin** [comment]
Hey guys,
Yes, there has been progress. No, it's not ready yet. The goal is to have all of this ready by end of July.

**Comment by christianreiss** [comment]
With 2 weeks till end of July -- any news? Any work? Anything?
Or is this a sure bet that this wont happen (this month)?

-Chris.

**Comment by kspearrin** [comment]
@christianreiss 

I've continued to make progress to condition the codebase for on-premise hosting. Unfortunately it isn't going to be ready in July. The new target is end of August - early September.

**Comment by kspearrin** [comment]
@all I've been working on this for the past week or so and have got things running on docker containers with Linux.

Expect something to start beta testing with soon.

**Comment by kspearrin** [comment]
all:

We have launched a public beta for testing on-premise hosting w/ Docker. Please see the following issue for information related to that beta: https://github.com/bitwarden/core/issues/62

Please try things out and provide feedback there. Thanks!

**Comment by kspearrin** [comment]
On-prem hosting has now been available few several months.
