### ISSUE TITLE
Importing passwords from Lastpass with ampersand - Bitwarden not removing &amp;

### ISSUE THREAD

**Issue by Enviii** [bitwarden/core#250]
Lastpass export seems to report ampersands as `&amp;` in their export file -- Which I guess is okay. 

Problem with Bitwarden is that it copies the password as is, with `&amp;`, and when I try to login it errors and tells me the password is incorrect.

Lastpass export example: `4&amp;VFdkaSd3`
Bitwarden password after import: `4&amp;VFdkaSd3`
What Bitwarden password should be: `4&VFdkaSd3`

**Comment by kspearrin** [comment]
This is documented here: https://help.bitwarden.com/article/import-from-lastpass/

**Comment by ryanpcmcquen** [comment]
This tool should help: https://github.com/ryanpcmcquen/fix_lastpass_export_for_bitwarden
