### ISSUE TITLE
Has there been any movement on deploying core without Docker?

### ISSUE THREAD

**Issue by DeviantEng** [bitwarden/core#251]
Due to reasons outside of my control, Docker is a no go.  I know it's been asked before, and I hate to ask again, but has there been any movement on a manual deployment of core+web?  I really want to migrate to bitwarden, after testing, but with Docker being a requirement, it's currently a no go.  

Is there any guidance for deploying without Docker?

Thanks.

**Comment by kspearrin** [comment]
There are no plans at the moment for an official self hosted option outside of the docker images. That may change in the distant future, but nothing is planned for now.

**Comment by Mart124** [comment]
Here's the community request, for completeness :
https://community.bitwarden.com/t/install-bitwarden-without-docker/609
