### ISSUE TITLE
Failure sending mail

### ISSUE THREAD

**Issue by xSpeedy** [bitwarden/core#252]
Hi,

today i updated to Version 1.18. Now i have the problem, that i receive no email. 

![grafik](https://user-images.githubusercontent.com/38012029/38211852-1988a9a0-36bc-11e8-95a1-4f76fffbf187.png)

My email address is entered: adminSettings__admins=myemail@email.com  (global.override.env)

`Mail send failed.`
`System.Net.Mail.SmtpException: Failure sending mail. ---> System.UnauthorizedAccessException: Access to the path '/home/bitwarden/.dotnet/corefx/cryptography/x509stores/ca' is denied. ---> System.IO.IOException: Permission denied`

**Comment by stevenhrabok** [comment]
I have not upgraded yet (but was currently using beta), but have a feeling when the new docker containers no longer run as root the userid changed and no longer allows permission to the global.override.env file.

My files currently show user and group 999:
-rw-------   1 999 999 1592 Mar 30 10:53 global.override.env
-rw-------   1 999 999   77 Mar 28 21:35 mssql.override.env

and that user doesn't exist in my system so I believe thats the docker container user.
you might want to try `chown 999:999 global.override.env` to see if the ownership helps correct the issue. If it does help, chown recursively the entire bwdata folder might help going forward.

**Comment by stevenhrabok** [comment]
I also logged into the docker container and checked /etc/group and /etc/passwd and found:
/etc/passwd
bitwarden:x:999:999::/home/bitwarden:
/etc/group
bitwarden:x:999:

So a `chown -r 999:999 bwdata` should probably correct the ownership issue encountered on all the files within. You may want to make a copy of the bwdata directory if you want some sort of restore point.

**Comment by xSpeedy** [comment]
I executed `chown -R 999:999 bwdata`
Still the same error.


My Files : 
-rwxrwxrwx+ 1 999 999 1726 Apr  2 17:43 global.override.env
-rw-------  1 999 999   77 Apr  2 16:12 mssql.override.env

**Comment by kspearrin** [comment]
Are you only having mail errors from the Admin container? What about Api?

**Comment by xSpeedy** [comment]
Same error for API

**Comment by kspearrin** [comment]
Can you bash into the Admin and/or Api containers and see who owns `/home/bitwarden/.dotnet/corefx/cryptography/x509stores/ca`?

**Comment by xSpeedy** [comment]
I'm connected as root to the API, but i cannot find the path, because /home is empty.

**Comment by kspearrin** [comment]
Try creating a home directory for user `bitwarden` and see if that changes anything?

**Comment by stevenhrabok** [comment]
I'm noticing all the containers have empty /home directories, should this be the case?

**Comment by xSpeedy** [comment]
> Try creating a home directory for user bitwarden and see if that changes anything.
bitwarden restarted. Still the same.

**Comment by kspearrin** [comment]
What user is your container running the dotnet process as?

**Comment by kspearrin** [comment]
Never mind, stupid question.

Did you chown the home dir after creating it?

**Comment by stevenhrabok** [comment]
@kspearrin whats the container to check for this path.
I just updated to 1.18 and tested the admin portal and received an email, and none of my home folders exist.

**Comment by xSpeedy** [comment]
@kspearrin I have just made it. Now i'm receiving email messages.

**Comment by kspearrin** [comment]
Admin or api I suppose. I haven’t got the error either so I’m not sure what is causing it. That path is managed by .NET core framework under some condition, not our code.

We don’t create the home for for the user, but it sounds like we might need to.

**Comment by stevenhrabok** [comment]
My thoughts are in my globalSettings all my base paths are contain /etc/bitwarden, @xSpeedy in your globalSettings do you have any paths that show /home/bitwarden?

**Comment by kspearrin** [comment]
Steven, that’s not it. The dot net framework is trying to create that user dir under some condition. Likely some type of smtp server that is different that what we are using.

**Comment by xSpeedy** [comment]
@kspearrin created the homedirectory both (API and Admin). 
I'm using strato as my smtp server: 
https://www.strato.com/faq/en_us/article/259/The-STRATO-Email-Server.html

**Comment by xSpeedy** [comment]
@kspearrin yes 👍

**Comment by kspearrin** [comment]
I’m curious, what types of files are you seeing created in that home dir now?

**Comment by xSpeedy** [comment]
Now the path existing
`/home/bitwarden/.dotnet/corefx/cryptography/x509stores/ca`
file.pfx (filename replaced)

**Comment by kspearrin** [comment]
Try updating to 1.18.1. Just released.

**Comment by xSpeedy** [comment]
Updated to 1.18.1. Receving email messages. There is no error in API log, but in the log of the admin docker i have this error:

```

Error sending mail with primary service, using backup.
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)
at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)
at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__4.MoveNext()

```

**Comment by kspearrin** [comment]
@xSpeedy 

That's a known problem that happens sometimes. It should eventually stop.
