### ISSUE TITLE
Reverse Proxy will not direct me to BW install

### ISSUE THREAD

**Issue by tscibilia** [bitwarden/core#254]
This is my first time with bitwarden but it's far from my first VM. I've configured BW to run on a Proxmox Ubuntu container with privileges to allow Docker to run. (P.S. add me as a +1 to issue #251, docker is hard to work with in my environment). I also had to modify the docker-compose up to include COMPOSE_HTTP_TIMEOUT=1000 because the 60 second default kept giving errors. 

Now i have it finally setup: its configured as localhost, self signed ssl, no letsencrypt, default ports, and behind a reverse proxy. However, I cannot for the life of me, get my existing nginx reverse proxy to redirect me to the BW installation. 

I've setup https://bw.mydomain.com to redirect to the ip address of the BW installation. Please let me know what else you need to troubleshoot this keep in mind when i browse to the local ip address via http (i see the BW vault) when i browse to it via https (i get ERR_CONNECTION_REFUSED)

### Below is my proxy config file
```
server {
        listen 80;
        server_name bw.mydomain.com;
        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl http2;
        server_name bw.mydomain.com;

        include /etc/nginx/snippets/strong-ssl.conf;
        ssl_certificate /etc/letsencrypt/live/bw.mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/bw.mydomain.com/privkey.pem;
        root /var/www/html;

        location ^~ /.well-known/acme-challenge/ {
                auth_basic off;
                autoindex on;
                allow all;
        }

        location / {
                try_files $uri $uri/ =404;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass https://192.168.5.140;
        }
}
```

**Comment by tscibilia** [comment]
nevermind, I read over some older issues and reinstalled it with non-standard ports and it works now. but the emails still are coming from localhost. is there a setting or rewrite rule I'm missing?

**Comment by kspearrin** [comment]
Which emails? All of them?
