### ISSUE TITLE
Verification email not sending with ssl enabled

### ISSUE THREAD

**Issue by SBECK-github** [bitwarden/core#256]
I am working with a completely fresh on-premise bitwarden install using the instructions at:

https://help.bitwarden.com/article/install-on-premise/

I got it installed, and created a new user and tried to send a verification email and it didn't arrive.  I thought I had found the answer here:

https://github.com/bitwarden/core/issues/171

but the email is still not arriving.

My global.override.env file looks like:

<pre>
  globalSettings__mail__replyToEmail=no-reply@bitwarden.mydomain.com
  globalSettings__mail__smtp__host=mail.mydomain.com
  globalSettings__mail__smtp__username=bitwarden
  globalSettings__mail__smtp__password=*mypassword*
  globalSettings__mail__smtp__ssl=true
  globalSettings__mail__smtp__port=587
  globalSettings__mail__smtp__useDefaultCredentials=false
</pre>

I also modified the docker-compose.yml file:

<pre>
  api:
    hostname: bitwarden.mydomain.com
</pre>

and confirmed it worked:

<pre>
  % docker exec -it 8... hostname
  bitwarden.mydomain.com

  % docker exec -it 8... ip addr
  228: eth0@if229: <BROADCAST,MULTICAST,UP,LOWER_UP> ...
    inet 172.18.0.7/16 scope global eth0
</pre>

However, the mail logs look like:

<pre>
   postfix/submission/smtpd[3370]:
     connect from bitwarden.mydomain.com[172.18.0.7]

   postfix/submission/smtpd[3370]:
     NOQUEUE: reject: RCPT from bitwarden.mydomain.com[172.18.0.7]:
     554 5.7.1 <bitwarden.mydomain.com[172.18.0.7]>:
     Client host rejected: Access denied;
     from=<no-reply@bitwarden.mydomain.com>
     to=<myemail@mydomain.com> proto=ESMTP
     helo=<bitwarden.mydomain.com>

   postfix/submission/smtpd[3370]:
     lost connection after RCPT from bitwarden.mydomain.com[172.18.0.7]

   postfix/submission/smtpd[3370]: disconnect from
     bitwarden.mydomain.com[172.18.0.7] ehlo=2 starttls=1 mail=1
     rcpt=0/1 commands=4/5
</pre>

and from the Api log file:

<pre>
2018-04-05 19:55:02.548 +00:00 [Error] Mail send failed.
System.Net.Mail.SmtpException: Transaction failed. The server response was: 5.7.1 <bw.sullybeck.com[172.18.0.7]>: Client host rejected: Access denied
   at System.Net.Mail.RecipientCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.RecipientCommand.EndSend(IAsyncResult result, String& response)
   at System.Net.Mail.SendMailAsyncResult.SendToCollectionCompleted(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Mail.SendMailAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpClient.SendMailCallback(IAsyncResult result)
</pre>

postfix is running on the same server hosting the bitwarden container, and my mail client is configured to use it as my SMTP server (also using port 587) and it works fine, so I believe it is configured correctly.

I ran across another post of someone who fixed the problem by turning off ssl, so I set overrides:

<pre>
  globalSettings__mail__smtp__ssl=false
  globalSettings__mail__smtp__port=25
</pre>

(with no other changes) and then the email was delivered, but I'd prefer to use SSL if possible (even though as far as I can tell, it's not strictly necessary since the mail server is on the same host).

Any suggestions?

**Comment by kspearrin** [comment]
Is your mail server actually set up for SSL?

**Comment by SBECK-github** [comment]
Sorry for the slow reply.  It took a while to get back to this.  It turned out to be a mailserver config issue.  I apologize for bothering you.
