### ISSUE TITLE
Failed to start Bitwarden.

### ISSUE THREAD

**Issue by sh5525** [bitwarden/core#257]
I followed https://help.bitwarden.com/article/install-on-premise/.
Docker and docker compose are installed without error.
Bitwarden is installed without error.
But when I start it by "./bitwarden.sh start", here is what comes.

root@my:~# ./bitwarden.sh start
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2018, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 18.03.0-ce, build 0520e24
docker-compose version 1.20.1, build 5d8c71b

Removing bitwarden-web         ... done
Removing bitwarden-identity    ... done
Removing bitwarden-mssql       ... done
Removing bitwarden-nginx       ... done
Removing bitwarden-api         ... done
Removing bitwarden-attachments ... done
Removing bitwarden-admin       ... done
Removing bitwarden-icons       ... done
Removing network docker_default
Pulling mssql (bitwarden/mssql:1.18.1)...
1.18.1: Pulling from bitwarden/mssql
Digest: sha256:88ce294c03fdef45990e109eee93573652379a2e263ca7e5f9213634b5177e93
Status: Image is up to date for bitwarden/mssql:1.18.1
Pulling web (bitwarden/web:1.25.1)...
1.25.1: Pulling from bitwarden/web
Digest: sha256:dd6a0666ac5d07f680dc74bf8dfa035154b84a039ffa87d8ac91eaa231fdb9dc
Status: Image is up to date for bitwarden/web:1.25.1
Pulling attachments (bitwarden/attachments:1.18.1)...
1.18.1: Pulling from bitwarden/attachments
Digest: sha256:61bd2ef2695cdc5bb3a201e37ff7745a419cfd86c7b55efb03fa267169a94813
Status: Image is up to date for bitwarden/attachments:1.18.1
Pulling api (bitwarden/api:1.18.1)...
1.18.1: Pulling from bitwarden/api
Digest: sha256:a3d733db8bcd5b724c0b6dcb9010ca28966c2fdbffae0e6b0bbe73b2e2f0d404
Status: Image is up to date for bitwarden/api:1.18.1
Pulling identity (bitwarden/identity:1.18.1)...
1.18.1: Pulling from bitwarden/identity
Digest: sha256:9b1f45d392cbbe575b4ba26b2f911c5893b1d6f34c4e531be5cef0a96ca1c11e
Status: Image is up to date for bitwarden/identity:1.18.1
Pulling admin (bitwarden/admin:1.18.1)...
1.18.1: Pulling from bitwarden/admin
Digest: sha256:b0bd9da1a02d84b20e9be0f33832290bd7903a3685233cd642a51ecbc9fff531
Status: Image is up to date for bitwarden/admin:1.18.1
Pulling icons (bitwarden/icons:1.18.1)...
1.18.1: Pulling from bitwarden/icons
Digest: sha256:f260cb1233d7248e271087aa3929f01b1f886c6f15eeee62698595406e4f7a50
Status: Image is up to date for bitwarden/icons:1.18.1
Pulling nginx (bitwarden/nginx:1.18.1)...
1.18.1: Pulling from bitwarden/nginx
Digest: sha256:747e01550f82fd4d53fd4f5962a082817c1409b8f2b9ae4c18edda36ac90b99d
Status: Image is up to date for bitwarden/nginx:1.18.1
Using default tag: latest
latest: Pulling from certbot/certbot
Digest: sha256:6acd4cc678e936c300df40704ee76979da480e5f7515a0d335e7a722d7b2fd53
Status: Image is up to date for certbot/certbot:latest
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log

-------------------------------------------------------------------------------

Processing /etc/letsencrypt/renewal/(my domain name).conf

-------------------------------------------------------------------------------

Cert not yet due for renewal

-------------------------------------------------------------------------------

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/(my domain name)/fullchain.pem expires on 2018-07-05                                                                                                                                                              (skipped)
No renewals were attempted.

-------------------------------------------------------------------------------

Creating network "docker_default" with the default driver
Creating bitwarden-icons ...
Creating bitwarden-admin ...
Creating bitwarden-attachments ...
Creating bitwarden-nginx       ...
Creating bitwarden-mssql       ...
Creating bitwarden-api         ...
Creating bitwarden-web         ...
Creating bitwarden-identity    ...
/root/bwdata/scripts/run.sh: line 37: 15561 Killed                  docker-compose -f $DOCKER_DIR/docker-compose.yml up -d

Thank you!

**Comment by kspearrin** [comment]
I see no problem.

**Comment by sh5525** [comment]
Yes, but when I input "docker ps", there is nothing there. And when I try again, here comes error:


Docker version 18.03.0-ce, build 0520e24
docker-compose version 1.20.1, build 5d8c71b

Removing bitwarden-mssql       ... done
Removing bitwarden-identity    ... done
Removing bitwarden-icons       ... done
Removing bitwarden-attachments ... done
Removing bitwarden-web         ... done
Removing bitwarden-api         ... done
Removing bitwarden-admin       ... done
Removing bitwarden-nginx       ... done
Removing network docker_default
Pulling mssql (bitwarden/mssql:1.18.1)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.                                                                                                                                                             io on 127.0.0.53:53: read udp 127.0.0.1:50437->127.0.0.53:53: read: connection r                                                                                                                                                             efused

**Comment by sh5525** [comment]
I may found the reason. Changed to a host with more RAM and it worked.
