### ISSUE TITLE
Admin portal redirects won't work with non-standard ports

### ISSUE THREAD

**Issue by alexhk** [bitwarden/core#258]
In addition to #248  and #253 I'd like to report that logging in to the admin portal won't forward correctly if Bitwarden is on a non-standard port.

Mine is configured at https://bw.domain.com:8443. In addition to  defaulting to http: instead of https:// it strips the port number. 

By manually editing the port and https back to the URL I could eventually login. I had to do that to get to the admin login page as well as for the link sent via email.

**Comment by kspearrin** [comment]
Fixed in next release.
