### ISSUE TITLE
Letsencrypt connection error

### ISSUE THREAD

**Issue by Julime** [bitwarden/core#260]
On initial Setup, i cat get Letsencrypt to get any cert. 

On clean Ubuntu 16.04 i did:
- install docker
- install docker-compose

```
curl -s -o bitwarden.sh \
    https://raw.githubusercontent.com/bitwarden/core/master/scripts/bitwarden.sh \
    && sudo chmod u+x bitwarden.sh
./bitwarden.sh install
```

and this happens:

```
[...]
Status: Image is up to date for certbot/certbot:latest
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
/usr/local/lib/python2.7/site-packages/josepy/jwa.py:107: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(self.padding, self.hash)
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for <mydomain>
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. <mydomain> (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://<mydomain>/.well-known/acme-challenge/b9btsx89nB2i81yLXeZW-RM7O_rYsxO-OPgt8Z0t3mo: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: <mydomain>
   Type:   connection
   Detail: Fetching
   http://<mydomain>/.well-known/acme-challenge/b9btsx89nB2i81yLXeZW-RM7O_rYsxO-OPgt8Z0t3mo:
   Timeout

 - To fix these errors, please make sure blabla...
```

if i curl on my domain during `Waiting for verification...`:
`curl: (56) Recv failure: Connection reset by peer`

As far as i can say, IPv6 is set up correctly.

If i skip any ssl setup, bitwarden setup runs correctly and is reachable via browser

**Comment by kspearrin** [comment]
According to the error acme cannot reach your domain at http://<mydomain>/.well-known/acme-challenge/... . There is a timeout. Is DNS set up for that domain? Has it propagated?

**Comment by georgedorn** [comment]
I opened this as an issue on the wrong repo, so I'll add my findings here as a comment:

> When installing with certbot enabled, certbot always uses 443 when checking whether the cert needs renewing, even if bitwarden has been configured to run on a different port.

> During `bitwarden.sh install`, certbot runs before the port is asked for, so it's necessary to shut down anything else running on that port during initial installation.  After, every startup also runs certbot to check whether renewal is needed, and that fails as well.

> A workaround for the startup problem is to edit `bwdata/scripts/run.sh` by hand to change the port, but `bitwarden.sh update` clobbers edits to that file.

**Comment by Julime** [comment]
i can't look after this problem before next month.
