### ISSUE TITLE
Bitwarden update from 1.18.0 to 1.18.1 faile

### ISSUE THREAD

**Issue by kereza** [bitwarden/core#261]
Hello

Running Bitwarden on premise with the docker. It fails to update with the following:

`ERROR: The Compose file '/root/bwdata/docker/docker-compose.yml' is invalid because:
services.nginx.ports contains an invalid type, it should be an array
`
I did firs run selfupdate

`Docker version 17.05.0-ce, build 89658be
docker-compose version 1.16.1, build 6d1ac219

Updated self.
`
Checking the docker-compose.yml  file I see:

nginx:
    image: bitwarden/nginx:1.18.1
    container_name: bitwarden-nginx
    restart: always
    ports:
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl
      - ../logs/nginx:/var/log/nginx
    env_file:
      - ../env/uid.env

Any suggestions ?

Thank you in advance

**Comment by kspearrin** [comment]
For some reason you have no ports set. Did you modify the compose file manually at some point?

**Comment by kspearrin** [comment]
Can you paste your full compose file?

**Comment by kereza** [comment]
Here it is:

`
# https://docs.docker.com/compose/compose-file/
# Parameter:MssqlDataDockerVolume=False
# Parameter:HttpPort=0
# Parameter:HttpsPort=0
# Parameter:CoreVersion=1.18.1
# Parameter:WebVersion=1.25.1

version: '3'

services:
  mssql:
    image: bitwarden/mssql:1.18.1
    container_name: bitwarden-mssql
    restart: always
    volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../logs/mssql:/var/opt/mssql/log
      - ../mssql/backups:/etc/bitwarden/mssql/backups
    env_file:
      - mssql.env
      - ../env/uid.env
      - ../env/mssql.override.env

  web:
    image: bitwarden/web:1.25.1
    container_name: bitwarden-web
    restart: always
    volumes:
      - ../web:/etc/bitwarden/web
    env_file:
      - ../env/uid.env

  attachments:
    image: bitwarden/attachments:1.18.1
    container_name: bitwarden-attachments
    restart: always
    volumes:
      - ../core/attachments:/etc/bitwarden/core/attachments
    env_file:
      - ../env/uid.env

  api:
    image: bitwarden/api:1.18.1
    container_name: bitwarden-api
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/api:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  identity:
    image: bitwarden/identity:1.18.1
    container_name: bitwarden-identity
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/identity:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  admin:
    image: bitwarden/admin:1.18.1
    container_name: bitwarden-admin
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/admin:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env

  icons:
    image: bitwarden/icons:1.18.1
    container_name: bitwarden-icons
    restart: always
    env_file:
      - ../env/uid.env

  nginx:
    image: bitwarden/nginx:1.18.1
    container_name: bitwarden-nginx
    restart: always
    ports:
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl
      - ../logs/nginx:/var/log/nginx
    env_file:
      - ../env/uid.env
`

**Comment by kspearrin** [comment]
In the comments at the top, try setting `HttpPort=80` and `HttpPort=443` (assuming you are using default ports). And then run `./bitwarden.sh update` again.

**Comment by kereza** [comment]
Hello,

Before the first update I made a snapshot of the VM and now reverted it back.

I have again now tried to fist "updateself" and than "update", but the  same issue  again.  

I have also tried to update the HTTP port and HTTPS ports at the top  and running the update again and ti fails with the same error:

"ERROR: The Compose file '/root/bwdata/docker/docker-compose.yml' is invalid because:
services.nginx.ports contains an invalid type, it should be an array"

Here is how the compose file looks:

**# https://docs.docker.com/compose/compose-file/
# Parameter:MssqlDataDockerVolume=False
# Parameter:HttpPort=80
# Parameter:HttpsPort=443
# Parameter:CoreVersion=1.18.1
# Parameter:WebVersion=1.25.1

nginx:
    image: bitwarden/nginx:1.18.1
    container_name: bitwarden-nginx
    restart: always
    ports:
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl
      - ../logs/nginx:/var/log/nginx
    env_file:**

Strange ! :)

**Comment by kspearrin** [comment]
You need to run the `update` command after fixing the compose file.

**Comment by kereza** [comment]
Uhmm...yeah of course I did that ! :) 

The issue is the same. 

"ERROR: The Compose file '/root/bwdata/docker/docker-compose.yml' is invalid because:
services.nginx.ports contains an invalid type, it should be an array
"
I even upgraded Docker Compose on the host to:

"docker-compose version 1.21.0, build 5920eb0"

Any other ideas ? :)

Regards.

**Comment by kereza** [comment]
OK so I did manually add it like:

nginx:
image: bitwarden/nginx:1.18.1
container_name: bitwarden-nginx
restart: always
ports:
- "443"
volumes:
- ../nginx:/etc/bitwarden/nginx
- ../letsencrypt:/etc/letsencrypt
- ../ssl:/etc/ssl
- ../logs/nginx:/var/log/nginx

and the update was able to run without errors.
