### ISSUE TITLE
Hardcoded GID 999 collides with existing GID

### ISSUE THREAD

**Issue by shartge** [bitwarden/core#262]
On my system the GID 999 is already taken by a different system group and Docker-CE allocated the GID 998 during installation.

Because of this, all files for bitwarden now belong to the wrong group, causing problems.

**Comment by kspearrin** [comment]
What is the groupid of your docker group?

**Comment by shartge** [comment]
It was 998.

But looking at the postinst of the docker-ce Debian package you can see that the GID is not static, it just uses `groupadd --system docker` and that could end up as any GID.

Relying on it being 999 seems problematic to me.

**Comment by kspearrin** [comment]
This should fix it with next release: https://github.com/bitwarden/core/commit/b7a2e47bd92bb05d6111140a4dae7b451bc26482

It will look map the local/host `docker` groupid to the container's `bitwarden` group. The same as it currently does for user id.
