### ISSUE TITLE
no external logs for mssql when using MssqlDataDockerVolume

### ISSUE THREAD

**Issue by shartge** [bitwarden/core#263]
Because of the current problem with the mssql container on Linux (see https://github.com/bitwarden/core/issues/155#issuecomment-381227745) I switched to using a docker volume for the data part.

Unfortunately the logs are no longer visible externally because the logs dir is not mounted when using that option.

**Comment by kspearrin** [comment]
I am not sure if the same problems would arise if you map the logs to a local volume. You can try it. Just edit docker-compose and add the following under mssql -> volumes:

```
      - ../logs/mssql:/var/opt/mssql/log
```

**Comment by shartge** [comment]
I used an override file to add that log directory mapping.

```
version: '3'

services:
  mssql:
    volumes:
      - ../logs/mssql:/var/opt/mssql/log
```

 Works without problems.

It seems mssql-linux only has problems with its database files on mapped directories.

**Comment by kspearrin** [comment]
fixed for next version
