### ISSUE TITLE
Cannt download attachments

### ISSUE THREAD

**Issue by qlles** [bitwarden/core#264]
I'm unable to download any attachments from my logins on my self hosted Bitwarden installation.
Tried web vault, ios app, firefox extension.
Ther's no error, just keeps loading after pressing download button.
Deleting and uploading of attachments is possible, but after uploading again, download still does not work.

**Comment by kspearrin** [comment]
What's the dev tools console show in the web vault? Does it make a network call?

**Comment by qlles** [comment]
sorry for late reply.
On web consoleit shows that :grinning: 
Blocked loading mixed active content “http://localhost/attachments/........

I'm running my Bitwarden behind Nginx reverse proxy if that helps.

**Comment by kspearrin** [comment]
Seems like your env settings are not correct. make sure proper base service urls are set in ./bwdata/env/global.override.env

**Comment by qlles** [comment]
Thanks, that was the problem. Just had to change for the correct domain and https from the env file, somehow missed it before.
Case closed.
