### ISSUE TITLE
Icons that don't work

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/core#268]
Known websites where icons are not working:

- live.com
- imgur.com

**Comment by Mart124** [comment]
Some others :
- miray.de
- login.teamviewer.com
- www.dellpartnerincentives.com

Strangely enough they have a `/favicon.ico` file, so...
First example could be a certificate issue.

**Comment by kspearrin** [comment]
@Mart124 These all seem to work for me, except the dell website which has no favicon.

**Comment by kspearrin** [comment]
Closing this issue now since the original reported problems have been fixed.

**Comment by benrubson** [comment]
@kspearrin with which Icons version ? 1.20 ? beta ?
I'm running 1.20.
Thx !

**Comment by Mart124** [comment]
I then have to investigate a little bit further.

**Comment by Mart124** [comment]
The dell website has favicon if you follow redirections :
`https://incentives.dellpartnerincentives.com/favicon.ico`

**Comment by kspearrin** [comment]
It's trying to get the favicon from here: http://dellpartnerincentives.com/

**Comment by Mart124** [comment]
Ah yes you sounds like you crop the subdomain part.
Then first try `https://dellpartnerincentives.com` which does not answer.
And then try `http://dellpartnerincentives.com` which answers but does not have a favicon file.

Strangely, `https://www.dellpartnerincentives.com` redirects to `https://incentives.dellpartnerincentives.com` which has a favicon.
