### ISSUE TITLE
Certbot renewal script uses port 443 regardless of configuration

### ISSUE THREAD

**Issue by georgedorn** [bitwarden/core#271]
When installing with certbot enabled, certbot always uses 443 when checking whether the cert needs renewing, even if bitwarden is configured to run on a different port.

During `bitwarden.sh install`, certbot runs before the port is asked for, so it's necessary to shut down anything else running on that port during initial installation.  After, every startup also runs certbot to check whether renewal is needed, and that fails as well.

A workaround for the startup problem is to edit `bwdata/scripts/run.sh` by hand to change the port, but `bitwarden.sh update` clobbers edits to that file.

(Error message to aid searchers:  `bind failed: address already in use` )

**Comment by kspearrin** [comment]
Perhaps we can also pass an `.env` file to certbot if it exists which will allow you to overload the defaults?

**Comment by multiwebinc** [comment]
This can be done easily with a proxy on the web server installed on port 443. Here is an example with Apache. If you're using Nginx or another web server you will have to consult the documentation. Add the following to `/etc/apache2/conf.d/letsencrypt.conf` substituting `12345` for whatever port you're running it on locally:

```
ProxyPass /.well-known/acme-challenge/ http://localhost:12345/.well-known/acme-challenge/
ProxyPassReverse /.well-known/acme-challenge/ http://localhost:12345/.well-known/acme-challenge/
ProxyPreserveHost On
```

Then execute:

```
sudo a2enmod proxy
sudo service apache2 restart
```

**Comment by Mart124** [comment]
I'm thinking about a quick fix for this, however, if installation does not use the default ports, should we assume that :
- this is because there is a proxy, so Let's Encrypt should also be behind the proxy ;
- this is because user wants to "hide" its installation, thus Let's Encrypt will have to run on the default 80/443 ports (as certificate creation/renew must use these external ports).

**Comment by Mart124** [comment]
#308 should help for both install and renew 👍

**Comment by kspearrin** [comment]
We don't intend to use other ports for the automated LE certbot config that is managed for you by `./bitwarden.sh`. If you need a more custom configuration you will need to managed certbot and LE certs on your own.
