### ISSUE TITLE
Bitwarden not running on designated ports

### ISSUE THREAD

**Issue by mbh-dev** [bitwarden/core#273]
Hi,

I have just installed Bitwarden and followed the process set out by you, however when running ./bitwarden.sh start i receive the message that the service is running and accessible at: https://mydomain:7072 (custom port configured), however when browsing to this address I cannot connect and receive a "took too long to respond" error message.

I have already setup the ports correctly in UFW and router but still no luck, can anyone shed any light.

Many thanks

**Comment by kspearrin** [comment]
Are all docker containers running? What is output of `docker ps`

**Comment by mbh-dev** [comment]
Ok, how do I rectify this, apologies but I'm new to docker

**Comment by mbh-dev** [comment]
I also have Apache running so I don't want to nginx to interfere with it
