### ISSUE TITLE
Bitwarden self-hosting "Mail send failed"

### ISSUE THREAD

**Issue by Catskan** [bitwarden/core#275]
Hi all,

I installed my bitwarden server on my Synology (Bitwarden self-hosting) and works great.

But, I can't send email with this. I can't, for exemple, send a verification email to verify my account.

I tryied to use Google's smtp server but doesn't works.

My smtp config : 
```
globalSettings__yubico__clientId=REPLACE
globalSettings__yubico__key=REPLACE
globalSettings__mail__replyToEmail=myemail@gmail.com
globalSettings__mail__smtp__host=smtp.google.com
globalSettings__mail__smtp__username=myemail@gmail.com
globalSettings__mail__smtp__password=myemailpassword
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__useDefaultCredentials=false
globalSettings__disableUserRegistration=true
```

And in attachment, my bitwarden server log when I try to send email.
[bitwarden-api.zip](https://github.com/bitwarden/core/files/1976734/bitwarden-api.zip)

Thanks you in advance for your help !

Regards,

Catskan

**Comment by kspearrin** [comment]
Your SMTP host is incorrect. Should be `smtp.gmail.com`
