### ISSUE TITLE
[Self-host] mssql container continually restarting

### ISSUE THREAD

**Issue by RichJeanes** [bitwarden/core#276]
When I started everything up directly with docker-compose via
`docker-compose -f ./bwdata/docker/docker-compose.yml up`

I eventually ended up with it just looping on the mssql server rebooting.
Here's one of the mssql log segments that just kept repeating: https://gist.github.com/RichJeanes/f6636ecfd23778acfaf175b17c406ca0

This is the third time I've tried to get up and running from a completely new VM (Ubuntu 16.04.2 64-bit).
The first one I had interrupted the install to move to a different location which I thought might have messed something up, so I tried again. Then I thought the problem might be only having 2GB of RAM, so I started again with 3GB and got here.

Any insights that can be provided would be appreciated.

**Comment by kspearrin** [comment]
Are you using ext4 or something else?

**Comment by RichJeanes** [comment]
Apparently my hosting provider uses ext2 in their images...

**Comment by kspearrin** [comment]
From what I have read ext4 is required for mssql.

**Comment by RichJeanes** [comment]
I guess I will have to contact my hosting provider about that. Thank you!
