### ISSUE TITLE
Unable to use bitwarden behind reverse proxy using a subfolder

### ISSUE THREAD

**Issue by jfrank1845** [bitwarden/core#277]
Despite updating all config variables to utilize a subfolder for bitwarden install the system will not accept it. Nothing works unless you take over the root of the http server which is not desired. my server is used for a few uses and I need to keep each item in its own place / I dont have multiple IPs to use subdomains for everything.

**Comment by kspearrin** [comment]
Sorry, but I do not understand the issue. What subfolder? I don't understand what HTTP server you are taking over root of. More details are needed to understand this issue.

**Comment by jfrank1845** [comment]
I apologize for the confusion. I was just a bit frustrated (mostly thanks
to when things dont line up the page just shows blank so it took me a bit
to realize it was a url mapping issue)  Regardless the install I was going
for was something like https:www.example.com/bitwarden/ I had docker set up
to listen on 8443 and had apache on the host set to do a reverse proxy for
the /bitwarden/ location to port 8443.  Everything worked fine certificate
wise / etc except the page was always blank.  When I did a /admin/ folder
and mapped it to the /admin/ folder on docker that of course worked.  So it
seems that even when you set the env info to include a subdirectory such as
/bitwarden/ ahead of the app everything doesn't get adjusted.  I hope that
is a bit clearer.  For now I've just resorted to opening another firewall
port and letting bitwarden just run on 8443 directly with no apache reverse
proxy

**Comment by kspearrin** [comment]
Yes, running Bitwarden under a domain subfolder is not a supported scenario. None of the installer paths are set up for that. It needs to run under a host, as a subdomain or additional port.

**Comment by kspearrin** [comment]
Premium can take a while to propagate to all of your apps. All licenses have a 7 day trial so you will need to generate a new one after your trial ends.

**Comment by mustaphazorgati** [comment]
> Yes, running Bitwarden under a domain subfolder is not a supported scenario. None of the installer paths are set up for that. It needs to run under a host, as a subdomain or additional port.

I am a little confused about the current status. Is it still not supported? Will it be supported someday?

**Comment by kcris** [comment]
I can run it in a subpath, I followed the instructions here (`Nginx with sub-path (by BlackDex)`)
https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples

behing my nginx reverse proxy I run bitwarden_rs as a docker container, 
I just had to pass the DOMAIN env variable to make it work

sudo docker run -d --name bitwarden -v /srv/docker-containers/bitwardenrs/data/:/data/ -p 19080:80 -p 3012:3012 -e DOMAIN=https://domain.tld/vault/ bitwardenrs/server:latest

**Comment by baku104788** [comment]
> 
> 
> > Yes, running Bitwarden under a domain subfolder is not a supported scenario. None of the installer paths are set up for that. It needs to run under a host, as a subdomain or additional port.
> 
> @kspearrin I am a little confused about the current status. Is it still not supported? Will it be supported someday?

Another approach is to put bitwarden onto its own IP address and then in your main http hosting (I use apache) have it redirect the subdomain of your choice back to the bitwarden instance as desired. For this I am using an HTTPS site in apache (the outward facing host) and letting it do a reverse proxy to the http instance of bitwarden on the local machine.
