### ISSUE TITLE
Is there a way to manually verify my email?

### ISSUE THREAD

**Issue by brandonsturgeon** [bitwarden/core#278]
I'm self hosting bitwarden, and I'll be the only person to use this instance. I don't want to set up an smpt server on this machine - is there any way to manually verify my email? Is it in the database somewhere? (I had to run my mssql instance in a Docker Volume to fix #155 )

Thank you!

**Comment by kspearrin** [comment]
You don't need to set up a SMTP server. You could just use a free gmail account's SMTP settings.

**Comment by brandonsturgeon** [comment]
Right, I was just hoping to avoid the whole thing because I only expect to set this up one time ever.

Thanks for the reply

**Comment by kspearrin** [comment]
No, there is not another way at this time.
