### ISSUE TITLE
Issue adding user to a 'family' organization 

### ISSUE THREAD

**Issue by jfrank1845** [bitwarden/core#279]
I purchased a license and got it installed ok. Am able to create a family organization however I'm not able to see the organization on the user I just created.  I see them in the list however the app/plugings/web all show no organization when that user logs in.  Am I missing something?

Thank you!

**Comment by kspearrin** [comment]
Has the user been confirmed to the organization?

**Comment by jfrank1845** [comment]
Yeah.  Accepted and it shows as such on the organization page.

**Comment by kspearrin** [comment]
After being accepted, you now need to "Confirm" the invite from the admin page.
