### ISSUE TITLE
Can't Join Organization

### ISSUE THREAD

**Issue by meatballz** [bitwarden/core#285]
I can't join an organization. 

After clicking the invitation link, the webpage immediately redirects to the login page, and says "invalid parameters". 

I tried using three different browsers both on desktop and mobile.

I tried the copy and paste workaround from [this issue](https://github.com/bitwarden/core/issues/55), but it didn't work for me.

**Comment by kspearrin** [comment]
Are you using a different email for your user account than the invite was sent to?

**Comment by meatballz** [comment]
No Sir. The same email address is used for the account, and the invite link.

Maybe, it's an issue with the email suffix being ".email"? That's the only thing out of the ordinary I can think of.

**Comment by kspearrin** [comment]
Perhaps the link is just expired? Have the org admin send it again.

**Comment by meatballz** [comment]
I just gave that a try, and unfortunately it did the same thing. I can for a split second see the invite page before it redirects me to the login page.

**Comment by meatballz** [comment]
I deleted the invitation, invited the email address again, it failed. I then deleted the invitation, invited a different email from a different domain, it worked. I then deleted that invite, and invited another email from the original domain, it worked. Then, I finally deleted that invite, and re-invited the problematic email, and it failed again.

There's something about that particular account that doesn't want to work.

I think I'll just delete the account, and start over.

**Comment by meatballz** [comment]
I deleted the account, signed back up, and now it won't let me verify that account. It's giving me the "invalid parameters" warning after clicking the verify email link.

**Comment by kspearrin** [comment]
It's likely that whatever email client you are using for the one that doesn't work is incorrectly encoding the link since it contains things like `%`. We'e seen this before. What if you actually copy/paste the link that is shown on screen (by highlighting, not right clicking the link)?

**Comment by meatballz** [comment]
It appears that it was the email client. The copy paste trick didn't work with the original client, but signing in through another email client, then copying and pasting worked.

For future reference the sogo web client did not work, but the geary desktop client did work.

Thanks.

**Comment by kspearrin** [comment]
Could you email me the two different links being different by the clients so I can compare them? hello@bitwarden.com

**Comment by kspearrin** [comment]
Copy and paste them rather than forwarding the emails

**Comment by meatballz** [comment]
Sure, I see what happened, now that I'm looking at them side by side. It's the ampersand prior to the word token.

**Comment by kspearrin** [comment]
Thanks.
