### ISSUE TITLE
"Anonymous" data sent to Microsoft ?

### ISSUE THREAD

**Issue by Mart124** [bitwarden/core#286]
Hi,

Using `tcpdump`, I noticed that self-hosted installation sends data to `40.77.226.250:443`, which has a SSL certificate for `*.vortex.data.microsoft.com`.
Do the docker images send so called "anonymous" data to Microsoft ?
Could this be disabled ?

Thank you !

**Comment by kspearrin** [comment]
When do you see it happening? Perhaps it is part of the .NET Core CLI telemetry mentioned here? https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry

Try setting environment variable `DOTNET_CLI_TELEMETRY_OPTOUT` to `1` and see if it stops.

**Comment by Mart124** [comment]
When I browse a vault (using the web vault for instance), it may take some minutes, but discussion with `*.vortex.data.microsoft.com` will start.

I then set the following for each Docker service in `docker/docker-compose.yml` file :
```
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
```
Unfortunately it does not help.

`export DOTNET_CLI_TELEMETRY_OPTOUT=1` in `bitwarden.sh`, and restarting the whole application does not help either.

**Comment by Mart124** [comment]
So, I tried to set env var `ASPNETCORE_preventHostingStartup=True`, as above, for each Docker service in `docker/docker-compose.yml`, but it did not help.

According to [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.0), Application Insights are enabled with production environment.
I then set `ASPNETCORE_ENVIRONMENT=Development` in `docker/global.env` (and restarted the app, of course). Did not help either.

According to [this](https://github.com/aspnet/Home/issues/2051#issuecomment-318513988) and [this](https://github.com/aspnet/Home/issues/2051#issuecomment-323967265), `ASPNETCORE_preventHostingStartup=True` should be set in the `launchSettings.json` files, a modification as you stated I can't do myself (but could be done in next version, good news 👍).

Btw, we could then wonder if `ASPNETCORE_ENVIRONMENT` in `docker/global.env` has any effect, as it's already set in `launchSettings.json` files (and `ASPNETCORE_preventHostingStartup` in `docker/global.env` has no effect).

According to [this](https://github.com/aspnet/Home/issues/2051#issuecomment-335641346), there could be another solution, which is to set `TelemetryConfiguration.DisableTelemetry=true` in `Startup.Configure()`. Of course this also needs to rebuild the app.

And a [third one](https://github.com/aspnet/Home/issues/2051#issuecomment-363495498), directly in Visual Studio. I'm not sure however if this solution will modify projects files, or if it's a "local" setting only (which everyone working on the project would have to manually tick also).

> How are you testing/seeing this from the host machine?

On a Linux machine.
Let's assume you're accessing the vault from IP `1.2.3.4`.
Your Linux public network interface is `eth0` (`ifconfig -a` or `ip addr show` to show all interfaces).
Then you can do :
`tcpdump -i eth0 -n port 443 and host not 1.2.3.4`

**Comment by Mart124** [comment]
I run `./bitwarden.sh start`, login, browse / refresh an organization vault and a user vault several times, and then communication starts. This is how I can reproduce the issue each time.

**Comment by kspearrin** [comment]
Issue has been opened with mssql team: https://github.com/Microsoft/mssql-docker/issues/312

**Comment by gt2416** [comment]
Any solution to this on the user's end ? Its a shocking amount of times it tries to send back data, more than my Windows server machine :/ 

![Bitwarden](https://user-images.githubusercontent.com/34902894/68176112-862c6100-ff51-11e9-934b-0bd856f4dbc6.png)

**Comment by milosvvv** [comment]
I just noticed this happening while looking through docker debug logs:

> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="[resolver] query vortex.data.microsoft.com. (A) from 172.19.0.5:36313, forwarding to udp:thednserver"
> 
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="[resolver] received A record \"65.55.44.109\" for \"bn2.vortex.data.microsoft.com.akadns.net.\" from udp:thednserver"
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="Name To resolve: vortex.data.microsoft.com."
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="[resolver] query vortex.data.microsoft.com. (A) from 172.19.0.5:53857, forwarding to udp:thednserver"
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="[resolver] received A record \"65.55.44.109\" for \"bn2.vortex.data.microsoft.com.akadns.net.\" from udp:thednserver"
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="Name To resolve: vortex.data.microsoft.com."
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="[resolver] query vortex.data.microsoft.com. (A) from 172.19.0.5:46163, forwarding to udp:thednserver"
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="[resolver] received A record \"65.55.44.109\" for \"bn2.vortex.data.microsoft.com.akadns.net.\" from udp:thednserver"
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="Name To resolve: vortex.data.microsoft.com."
> Nov 18 09:08:48 thebitwardenserver docker.dockerd[21925]: time="2019-11-18T09:08:48" level=debug msg="[resolver] query vortex.data.microsoft.com. (A) from 172.19.0.5:37205, forwarding to udp:thednserver"

I've since manually blocked the domain resolving in /etc/hosts as provided in #293

**Comment by Mart124** [comment]
Strangely enough @kspearrin #293 seems to have no (more) effect at all !
Looking at `/etc/hosts` file in `mssql` containers, it does not contain the blackhole hard-coded entries...
Any issue ?

**Comment by Mart124** [comment]
OK, here's a workaround, in `docker-compose.override.yml` :
```
services:
  mssql:
    extra_hosts:
      - "settings-win.data.microsoft.com:127.0.0.1"
      - "vortex.data.microsoft.com:127.0.0.1"
```
@kspearrin I think you could put this directly into `docker-compose.yml` and revert #293, which has moved here : https://github.com/bitwarden/server/blob/5d047d52c39a6cd8839b47ace71b92a04b8d83b1/util/MsSql/Dockerfile#L21-L23

**Comment by Mart124** [comment]
I also think that `mssql` container, as certainly some others, don't need a public network access.
They should only be able to communicate with the other containers.
So they also don't need DNS servers.
Reminds me @silverwind idea : https://github.com/bitwarden/server/issues/495#issuecomment-510565933

**Comment by kspearrin** [comment]
Correct. The database container doesn't need any outside network connectivity.

**Comment by Mart124** [comment]
To globally control networks, we could go to something like this :
https://devops.stackexchange.com/questions/4514/internal-network-between-container-docker-compose-with-outgoing-connection

So :
```
networks:
  frontend:
    internal: false
  backend:
    internal: true
```

Then give backend network to all containers, and frontend to containers which need external connectivity, for example :
```
  mssql:
    networks:
      - backend
  icons:
    networks:
      - backend
      - frontend
```

**Comment by Mart124** [comment]
The proper approach I think is to deny public network by default.

So, in `docker-compose.yml` :
```
networks:
  default:
    internal: true
  public:
    internal: false
```

And for services needing public network, and only for them :
```
    networks:
      - default
      - public
```

@kspearrin, could we go for this please ?
Many thanks 👍

**Comment by kspearrin** [comment]
@Mart124 See https://github.com/bitwarden/server/commit/c27b72e019efbd9f763f6453cab6d4cb6e7ae71c

You can test this on the dockerhub `dev` tag if you like.

**Comment by Mart124** [comment]
Many thanks @kspearrin, let's give this a try 👍
By curiosity, don't you prefer the above method, to configure default network as internal, and only give public access to services needing it ?
I'm surprised 7 containers out of 10 need public access ? I would have though most of the traffic would have gone through the nginx service...
Thank you again !

**Comment by Mart124** [comment]
In addition, unfortunately, your commit does not work.
The 3 services assigned to the _private_ network can't communicate with the other services, as they are isolated in their own _private_ network.
I think you should rather do like above (https://github.com/bitwarden/server/issues/286#issuecomment-555915360), making the default network as private, and adding a public network to the services needing it.

**Comment by kspearrin** [comment]
@Mart124 Try https://github.com/bitwarden/server/commit/fe3378b483d7e27d0be0networks:- default- publicbfb8c2a58737154668f whenever it finishes building.

**Comment by Mart124** [comment]
Yes, like this it works @kspearrin 👍
Perfect, sounds good !
I think you can now revert the following which is useless :
https://github.com/bitwarden/server/blob/5d047d52c39a6cd8839b47ace71b92a04b8d83b1/util/MsSql/Dockerfile#L21-L23

**Comment by Mart124** [comment]
We should be safe now :)
To finish with this, do you plan a new release anytime soon @kspearrin ?
Thank you again !

**Comment by netstat-peanut** [comment]
Is there a tl;dr posted somewhere covering why BW uses mssql in favor of the alternatives? I'm sure it exists, as I can't be the only person put off by it.
