### ISSUE TITLE
Add support for Duo Security 2FA

### ISSUE THREAD

**Issue by sethlyons** [bitwarden/core#29]
Please!

https://duo.com/product/every-application/supported-applications/apis
https://github.com/duosecurity

**Comment by kspearrin** [comment]
@sethlyons We are starting to look at this now.

Do you happen to have any connections at Duo that we could reach out to? We'd like to work with them about making this integration as seamless as possible.

**Comment by sethlyons** [comment]
i'll see what i can find.  i have a sales rep, so i'll ask him for a technical contact.

if it helps in the meantime, the documentation [here](https://duo.com/docs/duoweb) is very good.

**Comment by kspearrin** [comment]
@sethlyons It looks rather simple if you are only protecting a web application, however, we things like mobile apps we also have to account for. I think we need to be looking at these as well: https://duo.com/docs/authapi

**Comment by sethlyons** [comment]
ah, yeah...makes sense.  i just fired off the email to my sales rep.  i'll let you know when he replies.

**Comment by sethlyons** [comment]
just got a reply from my sales rep.  he said you should reach out to techpartners@duo.com.

**Comment by kspearrin** [comment]
Thanks!

**Comment by kspearrin** [comment]
ref https://github.com/bitwarden/core/commit/314d591f362a4e7557c68cfb123de958288593db

We're going to add Duo support for individual premium accounts as a first iteration. Duo for organizations will follow.

**Comment by sethlyons** [comment]
nice!  out of curiosity, how come you limit the 2FA options on free accounts?

**Comment by kspearrin** [comment]
@sethlyons We've got to add value somewhere to make money. Open to feedback.

**Comment by sethlyons** [comment]
i'll admit i'm biased because i have a free account, but my gut is that the added value should be in features (priority tech support, file attachments, etc.) and not in security.

**Comment by kspearrin** [comment]
Free users will continue to have the option to use TOTP 2FA.

**Comment by erikvg01** [comment]
Just adding color to the conversation...  I would expect to pay an additional fee for anything that extends the solution beyond a single user context.  If I need to share a password, give a break-glass option to someone, AD integration, and so on, I'll pay for that.  In my humble opinion, any flavor of 2fa should be included in the 'free' solution, as it is in the single user context.  You guys need to make it viable for yourselves to continue working, but I feel this is the wrong place to look for that.  Just my 2c. Thanks!

**Comment by kspearrin** [comment]
Duo is now working in latest dev build for the web vault. Still some work to do on the other apps, but most of the hard work is now done. I'm also working with their tech partners team to add bitwarden as a application in the Duo admin panel for easy integration.

**Comment by kspearrin** [comment]
This is done for next release.
