### ISSUE TITLE
Bitwarden is giving invited new users that need to create an account a registration error.

### ISSUE THREAD

**Issue by rfelsburg** [bitwarden/core#291]
To note. This is not a feature request. This is a bug.

We have a self-hosted bitwarden install. When disableUserRegistration=true, is set, new users that are sent an invite, can not create a new account.

1.) Invite new user.
2.) The User follows the link and is sent to the self-hosted instance page.
```
Join Company

user@company.tldr

You've been invited to join the organization listed above. To accept the invitation, you need to log in or create a new Bitwarden account.
```
3.) User clicks 'Create Account' and is taken to the 'Create new account' page.
4.) User fills out all required fields, and clicks 'Submit'.
5.) Account creation fails, and the user is presented with the error below.
```
Errors have occurred

    Registration has been disabled by the system administrator.
```

**Comment by Mart124** [comment]
See #219 & https://community.bitwarden.com/t/allow-invited-people-to-register-even-if-registrations-are-disabled/211

**Comment by kspearrin** [comment]
This is the currently intended functionality, so it's not a bug. Feature request is being tracked at https://community.bitwarden.com/t/allow-invited-people-to-register-even-if-registrations-are-disabled/211

**Comment by rfelsburg** [comment]
I'm sorry, but it's never worked this way in the past. So was the functionality of disableUserRegistration=true intentionally changed, and no one told, or it this a problem with the new version.

Just to clarify, you're stating that disableUserRegistration=true is meant to stop even admin's from invited new users to the org? The only option being anyone can create an account, or no one, not even invited users can not create accounts?

We've even gone so far as to enable registration, and get the same error. So this is a problem, with registration as a whole for us.

**Comment by kspearrin** [comment]
This has always been the function of `disableUserRegistration=true`. If you are getting errors even with `disableUserRegistration=false`, then the problem is something unrelated to `disableUserRegistration` altogether.
