### ISSUE TITLE
bitwarden.sh update reports error in run.sh script that getent command not found

### ISSUE THREAD

**Issue by stevenhrabok** [bitwarden/core#295]
Hello,

I updated on my synology bitwarden to the latest version (using `./bitwarden.sh updateself` and `./bitwarden.sh update`). The update was *successful* but there was an error reported on `./bitwarden.sh update` as follows:

```
/volume1/docker/bwdata/scripts/run.sh: line 35: getent: command not found
```

I see the update was successful and looking at the run.sh script I'm confused on how it was possible.

I see it defined here

```
LGID="LOCAL_GID=`getent group docker | cut -d: -f3`"
```

And its used in numerous docker commands such as:

```
function updateDatabase() {
    pullSetup
    if [ $OS == "lin" ]
    then
        docker run -i --rm --name setup --network container:bitwarden-mssql \
            -v $OUTPUT_DIR:/bitwarden -e $LUID -e $LGID bitwarden/setup:$COREVERSION \
            dotnet Setup.dll -update 1 -db 1 -os $OS -corev $COREVERSION -webv $WEBVERSION
```

I assume this would inject `LOCAL_GID=` or append error output to that value.

Currently there is no docker group in synology, I believe everything is running as root, which could possibly be the reason for the successful outcome.

I thought I would bring this up for visibility since it might be confusing or misleading.
Would it be worth considering to check for the docker group and if it doesn't exist default to 0 (root)? Or default to the current users group? 

Also since getent isn't on the system either, wonder if something like grep (which is more common) and a default value of root

```
DOCKER_GROUP=$(grep ^docker /etc/group | cut -d: -f3)
LGID="LOCAL_GID=${DOCKER_GROUP:-0}"
```
or default to the user running the script using id -g ?

```
DOCKER_GROUP=$(grep ^docker /etc/group | cut -d: -f3)
LGID="LOCAL_GID=${DOCKER_GROUP:-$(id -g)}"

```

**Comment by kspearrin** [comment]
This will be fixed with https://github.com/bitwarden/core/pull/292
