### ISSUE TITLE
.NET Core Runtime

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/core#3]
Move to .NET Core runtime for all projects so that the APIs can run cross platform. This will require that library dependencies all support the .NET Standard.

Currently this list includes:
- [x] OtpSharp (https://bitbucket.org/devinmartin/otp-sharp/issues/19/net-core)
- [x] DataTableProxy (https://github.com/tdietrich513/DataTableProxy/issues/2)
- [x] Sendgrid (https://github.com/sendgrid/sendgrid-csharp/issues/221)
- [ ] PushSharp (https://github.com/Redth/PushSharp/issues/730)

Once these libraries are either 1) replaced with something else that supports the .NET Standard or 2) adopt it themselves, this project can also move to the .NET Standard for .NET Core.

**Comment by Reanmachine** [comment]
You also may have to solve #10 if you're expecting to ease the cross-platform woes. MSSQL isn't a picnic on linux.

**Comment by Jericho** [comment]
Regarding SendGrid: I would like to mention that I released a library called [StrongGrid](https://www.nuget.org/packages/StrongGrid/) that targets multiple .Net frameworks, including .Net Standard. The library covers the entire SendGrid API (not just sending emails). This means that it also helps you maintain lists, contacts and segments, it also helps you generate API Keys, manage subscription groups, templates, etc.

**Comment by kspearrin** [comment]
OTPSharp replaced with https://github.com/kspearrin/Otp.NET

**Comment by Jericho** [comment]
Would you accept a PR to replace SendGrid's C# which still is not compatible with .NET Core with StrongGrid?

**Comment by kspearrin** [comment]
According to SendGrid, they have a new strongly typed, .NET Core compatible version releasing soon so I think I'll just wait for that official one.

**Comment by Jericho** [comment]
I know, they've been saying that for a year now!!!

**Comment by kspearrin** [comment]
NET Standard 2.0 is due to release soon (maybe March?) and should make all of our dependencies compatible with .NET Core. Cross platform coming soon!

**Comment by kspearrin** [comment]
SendGrid library has now been updated to 9.x, which includes support for .NET Standard.

**Comment by kspearrin** [comment]
Knocked another one off the list (DataTableProxy). One more to go (PushSharp, which I plan to replace with Azure Notification Hubs soon).

**Comment by kspearrin** [comment]
This is done for next release which will include self-hosted options in Linux docker containers.

`master` branch is now cross-platform compatible through the netcoreapp2.0 framework. .NET Core 2.0 runtime is required.

**Comment by kspearrin** [comment]
See the updated main README for build/run instructions.

**Comment by mongrelion** [comment]
@kspearrin great!

I just took this for a spin (on macOS) but there seems to be some missing images in the Docker Hub.
Check the attached log:

```
 x ./bitwarden.sh install
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2017, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

Docker version 17.06.0-ce, build 02c1d87

(!) Enter the domain name for your bitwarden instance (ex. bitwarden.company.com): localhost
(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n
Unable to find image 'bitwarden/setup:latest' locally
docker: Error response from daemon: repository bitwarden/setup not found: does not exist or no pull access.
See 'docker run --help'.
```

I think we are either missing some steps to build the `bitwarden/setup` image locally or the image should be pushed by you to the Hub before any of this can happen.

Thanks again for the effort! I'm looking forward to seeing this moving on!

**Comment by kspearrin** [comment]
@mongrelion Yes, the images are not yet available on Docker Hub. This is issue was for being able to build and run for .NET Core runtime, not deploying (Docker). You can follow this issue for that https://github.com/bitwarden/core/issues/25 . I plan to announce sometime here soon for Docker deployments once i button everything up.
