### ISSUE TITLE
Bitwarden Docker doesn't seem to read global.override.env

### ISSUE THREAD

**Issue by niwiniwi** [bitwarden/core#301]
I am running Bitwarden 1.19.0 with Docker-Version:

```
Docker version 18.03.0-ce, build 0520e24
docker-compose version 1.21.2, build a133471
```
on a machine running Debian 9.3.
I have made some changes to `bwdata/env/global.override.env` (Changing the SMTP-Settings and disabling the registration and restarted Bitwarden with `./bitwarden.sh restart`. The listing `Create a new account` is still available on the web-page and the verification-mails are not send.  I have even tried rebooting the machine where BitWarden is running. 

What could be the cause of this issue? Thanks in advance.

**Comment by Mart124** [comment]
> The listing Create a new account is still available on the web-page

Same on my installation, but if you try to register, you'll then get :
_Open registration has been disabled by the system administrator._

**Comment by niwiniwi** [comment]
>Same on my installation, but if you try to register, you'll then get :
>Open registration has been disabled by the system administrator.

Alright, i am also getting that when i try to register. Good. Thank you! Now i will try to find the error with the mails.

**Comment by cooperaj** [comment]
The email thing is fixed in the next release
https://github.com/bitwarden/core/commit/72e95e2a98d8342b8e9be3149f4038f5bf2ae33c

**Comment by niwiniwi** [comment]
>The email thing is fixed in the next release
72e95e2

So no chance to use the admin interface until then?

**Comment by niwiniwi** [comment]
@kspearrin If i use `ssmtp` with the same credentials and server i can send mails no problem but it doesn't work with Bitwarden.

I configured Bitwarden like this:

```
globalSettings__mail__replyToEmail=no-reply@----.de
globalSettings__mail__smtp__host=smtp.server.de
globalSettings__mail__smtp__username=--@-----.de
globalSettings__mail__smtp__password=------
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=465
globalSettings__mail__smtp__useDefaultCredentials=false
```
I don't see anything obviously wrong with that. I have used the same settings for `ssmtp`

Are there logs i can check for mail? Thanks!

**Comment by kspearrin** [comment]
Is your mail account protected with 2fa? You can’t just use the password if that’s the case.

**Comment by niwiniwi** [comment]
>Is your mail account protected with 2fa? You can’t just use the password if that’s the case.
It is not.

**Comment by Mart124** [comment]
By curiosity, did you try port `587` with your working credentials ? Perhaps your provider supports it too.

**Comment by niwiniwi** [comment]
@Mart124 Just tried, doesn't work either. Same behavior as before

**Comment by Mart124** [comment]
Same platform / same versions as yours, no issue.

```
# dpkg -l | grep dock
ii  docker-ce                      18.03.1~ce-0~debian            amd64
# docker-compose --version
docker-compose version 1.21.2, build a133471
# cat /etc/debian_version 
9.4
```

Perhaps as a test try another mail provider, just to be sure ?
Could give some clues.

**Comment by niwiniwi** [comment]
I just tried my self-hosted smtp-server (Works otherwise), doesn't work, and i've tested two other providers including Gmail. None of them work.

**Comment by kspearrin** [comment]
@niwiniwi Sounds like something is blocking outbound requests to your mail server then. Perhaps you have some sort of firewall on the server or something?

**Comment by niwiniwi** [comment]
@kspearrin Just double checked. No, nothing blocking. `ssmtp` still works.

**Comment by niwiniwi** [comment]
Very weird. I've just tested one thing that doesn't work. Using localhost as the `smtp_host`, so definitely no firewall issue. I would be happy using Gmail, do you have an example configuration?

**Comment by ByteNetworks** [comment]
Check your log file when sending the admin login mail. 
For example, my firewall (even if you don't have one) has shown this error:

2018-05-26 23:46:36.148 +00:00 [Error] Mail send failed.
System.Net.Mail.SmtpException: Failure sending mail. ---> System.Security.Authentication.AuthenticationException: **The remote certificate is invalid according to the validation procedure.**

**Comment by niwiniwi** [comment]
@ByteNetworks That is a very useful tip! Thank you! Of course there are errors:

`2018-06-01 15:15:48.375 +00:00 [Error] Error sending mail with primary service, using backup.
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Services.RazorMailService.<SendPasswordlessSignInAsync>d__15.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/RazorMailService.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Services.BackupMailService.<SendPasswordlessSignInAsync>d__14.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/BackupMailService.cs:line 160
`

Nothing i really can work with

**Comment by kspearrin** [comment]
That error doesn't deal with the actual sending of mail and is expected. Look for any SMTP errors.

**Comment by niwiniwi** [comment]
@kspearrin Thats all the file `bwdata/logs/admin/Admin/20180601.txt` has to offer when I try to send a mail.

**Comment by ByteNetworks** [comment]
No problem. 
At first it looks like an SQL error to me, but kspearrin can certainly help a lot more than I can.

**Comment by cooperaj** [comment]
What does the log output of the api container show?

**Comment by niwiniwi** [comment]
@cooperaj 
Logs via `docker-compose logs -f`:


## Send Verifictation Mail:

```
bitwarden-api  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
bitwarden-api  |       Request starting HTTP/1.0 POST http://xxxxxxxxxxxxxxx/accounts/verify-email application/json;charset=utf-8 0
bitwarden-api  | info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
bitwarden-api  |       Policy execution successful.
bitwarden-api  | info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
bitwarden-api  |       Successfully validated the token.
bitwarden-api  | info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[8]
bitwarden-api  |       AuthenticationScheme: BearerIdentityServerAuthenticationJwt was successfully authenticated.
bitwarden-api  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[8]
bitwarden-api  |       AuthenticationScheme: Bearer was successfully authenticated.
bitwarden-api  | info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
bitwarden-api  |       Authorization was successful for user: not-sure-if-secret-xxxxxxxx.
bitwarden-api  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
bitwarden-api  |       Executing action method Bit.Api.Controllers.AccountsController.PostVerifyEmail (Api) with arguments ((null)) - ModelState is Valid
bitwarden-api  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
bitwarden-api  |       Executed action Bit.Api.Controllers.AccountsController.PostVerifyEmail (Api) in 20.0385ms
bitwarden-api  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
bitwarden-api  |       Request finished in 36.1412ms 200
```

## When trying to log in to admin-panel

```
bitwarden-admin | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
bitwarden-admin |       Request starting HTTP/1.0 POST http://xxxxxxxxxxxxxxxx/admin/login application/x-www-form-urlencoded 227
bitwarden-admin | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
bitwarden-admin |       Executing action method Bit.Admin.Controllers.LoginController.Index (Admin) with arguments (Bit.Admin.Models.LoginModel) - ModelState is Valid
bitwarden-admin | fail: Bit.Core.Services.BackupMailService[0]
bitwarden-admin |       Error sending mail with primary service, using backup.
bitwarden-admin | System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
bitwarden-admin |    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
bitwarden-admin |    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
bitwarden-admin |    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
bitwarden-admin |    at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
bitwarden-admin |    at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
bitwarden-admin |    at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
bitwarden-admin |    at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
bitwarden-admin |    at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)
bitwarden-admin |    at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)
bitwarden-admin |    at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__4.MoveNext()
bitwarden-admin | --- End of stack trace from previous location where exception was thrown ---
bitwarden-admin |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-admin |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-admin |    at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__10.MoveNext()
bitwarden-admin | --- End of stack trace from previous location where exception was thrown ---
bitwarden-admin |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-admin |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-admin |    at RazorLight.RazorLightEngine.<CompileRenderAsync>d__9.MoveNext()
bitwarden-admin | --- End of stack trace from previous location where exception was thrown ---
bitwarden-admin |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-admin |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-admin |    at Bit.Core.Services.RazorMailService.<SendPasswordlessSignInAsync>d__15.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/RazorMailService.cs:line 221
bitwarden-admin | --- End of stack trace from previous location where exception was thrown ---
bitwarden-admin |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-admin |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-admin |    at Bit.Core.Services.BackupMailService.<SendPasswordlessSignInAsync>d__14.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/BackupMailService.cs:line 160
bitwarden-admin | info: Microsoft.AspNetCore.Mvc.RedirectToActionResult[1]
bitwarden-admin |       Executing RedirectResult, redirecting to /admin/login?success=If%20a%20valid%20admin%20user%20with%20this%20email%20address%20exists,%20we%27ve%20sent%20you%20an%20email%20with%20a%20secure%20link%20to%20log%20in..
bitwarden-admin | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
bitwarden-admin |       Executed action Bit.Admin.Controllers.LoginController.Index (Admin) in 229.4856ms
bitwarden-admin | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
bitwarden-admin |       Request finished in 231.3868ms 302
bitwarden-admin | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
bitwarden-admin |       Request starting HTTP/1.0 GET http://xxxxxxxxxxxxxxxx/admin/login?success=If%20a%20valid%20admin%20user%20with%20this%20email%20address%20exists,%20we%27ve%20sent%20you%20an%20email%20with%20a%20secure%20link%20to%20log%20in.
bitwarden-admin | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
bitwarden-admin |       Executing action method Bit.Admin.Controllers.LoginController.Index (Admin) with arguments (, , If a valid admin user with this email address exists, we've sent you an email with a secure link to log in., False) - ModelState is Valid
bitwarden-admin | info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
bitwarden-admin |       Executing ViewResult, running view at path /Views/Login/Index.cshtml.
bitwarden-admin | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
bitwarden-admin |       Executed action Bit.Admin.Controllers.LoginController.Index (Admin) in 7.4623ms
bitwarden-admin | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
bitwarden-admin |       Request finished in 10.384ms 200 text/html; charset=utf-8
```

Nothing that looks like smtp-errors to me.

**Comment by Mart124** [comment]
A DNS issue ? Can you ping your SMTP hostname from your containers ?

**Comment by niwiniwi** [comment]
@Mart124 
```
# docker exec bitwarden-admin ping mail.domain.de
PING mail.domain.de (xxx.xxx.xxx.xxx): 56 data bytes
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=0 ttl=54 time=1.277 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=1 ttl=54 time=0.857 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=2 ttl=54 time=1.197 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=3 ttl=54 time=1.449 ms

# docker exec bitwarden-api ping mail.domain.de
PING mail.domain.de (xxx.xxx.xxx.xxx): 56 data bytes
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=0 ttl=54 time=1.342 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=1 ttl=54 time=1.052 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=2 ttl=54 time=1.428 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=3 ttl=54 time=1.268 ms
```

If i did that (The Docker-Part) correctly i would say that works.

**Comment by Mart124** [comment]
```
docker exec -ti bitwarden-api bash
apt-get update
apt-get install telnet
telnet <smtp_host> 465
telnet <smtp_host> 587
```
(`CTRL+$` to exit an opened telnet session)

**Comment by niwiniwi** [comment]
@Mart124 

```
root@567b2e703670:/app# telnet mail.domain.de 465
Trying xxx.xxx.xxx.xxx...
Connected to mail.domain.de.
Escape character is '^]'.

root@567b2e703670:/app# telnet mail.domain.de 587
Trying xxx.xxx.xxx.xxx...
Connected to mail.domain.de.
Escape character is '^]'.
220 mail.domain.de ESMTP Postfix
```
