### ISSUE TITLE
Database update failed

### ISSUE THREAD

**Issue by xSpeedy** [bitwarden/core#310]
Today i tried to update bitwarden to Version 1.20. The the following error occurs:

> Pausing 60 seconds for database to come online. Please wait...
> 1.20.0: Pulling from bitwarden/setup
> Digest: sha256:42c20f5c5aaf2ab90619ba41a100c7ac258ab412d439cbbf43185d573eadd35c
> Status: Image is up to date for bitwarden/setup:1.20.0
> 
> Migrating database.
> Database is in script upgrade mode. Trying again (attempt # 2)...
> Migrating database.
> Database is in script upgrade mode. Trying again (attempt # 3)...
> Migrating database.
> 
> Unhandled Exception: System.Data.SqlClient.SqlException: Login failed for user 'sa'. Reason: Server is in script upgrade mode. Only administrator can           connect at this time.
>    at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 285
>    at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 281
>    at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 281
>    at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 57

What did i try:

./bitwarden.sh updatedb
./bitwarden.sh update

Still the same issue

**Docker version 17.05.0-ce, build 9f07f0e-synology
docker-compose version 1.14.0, build c7bdf9e**

**Comment by kspearrin** [comment]
Give it a few minutes, then run `./bitwarden.sh updatedb` again.

**Comment by xSpeedy** [comment]
Thanks! Solved 👍

**Comment by Obre** [comment]
thank you! worked for me
