### ISSUE TITLE
bitwarden.sh fails without internet

### ISSUE THREAD

**Issue by jerheij** [bitwarden/core#320]
When I run the `bitwarden.sh start` command without internet connection I get the following errors:

> Docker version 18.03.1-ce, build 9ee9f40
> docker-compose version 1.21.2, build a133471
> 
> Removing network docker_default
> WARNING: Network docker_default not found.
> Pulling mssql       ... error
> Pulling web         ... error
> Pulling attachments ... error
> Pulling api         ... error
> Pulling identity    ... error
> Pulling admin       ... error
> Pulling icons       ... error
> Pulling nginx       ... error
> 
> ERROR: for identity  Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> ERROR: for nginx  Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> ERROR: for api  Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> ERROR: for attachments  Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> ERROR: for admin  Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> ERROR: for icons  Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> ERROR: for mssql  Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> #docker ps
> CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

As you can see after that no containers are started while I have all the required containers downloaded and everything setup.

> #docker images
> REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
> certbot/certbot         latest              aee207f30a81        2 weeks ago         116MB
> bitwarden/web           1.27.0              58a90dd0d0bc        4 weeks ago         337MB
> bitwarden/setup         1.20.0              92cf588d9809        4 weeks ago         227MB
> bitwarden/admin         1.20.0              75bdfb65c0bb        4 weeks ago         349MB
> bitwarden/icons         1.20.0              7e428b5e9a08        4 weeks ago         333MB
> bitwarden/identity      1.20.0              2d7a8e6c1d6d        4 weeks ago         365MB
> bitwarden/api           1.20.0              2a6fc370972f        4 weeks ago         418MB
> bitwarden/mssql         1.20.0              00f82eb00bbe        4 weeks ago         1.43GB
> bitwarden/attachments   1.20.0              29d47575712a        4 weeks ago         333MB
> bitwarden/nginx         1.20.0              3a686270aab0        4 weeks ago         111MB

When I do exactly the same when an internet connection is available everything runs without a problem. 

Is there a way to run the bitwarden.sh script without an internet connection in an isolated environment?

**Comment by kspearrin** [comment]
The script is trying to check for updates each time you start it. You can start the container without the script.


```
cd ./bwdata/docker
docker-compose up -d
```

**Comment by jerheij** [comment]
I figured it would make more sense if the "start" command of a docker environment would just start it without being dependent on an internet connection. 

Does the docker-compose command do the same as the run.sh script the bitwarden.sh script runs? If I recall the run.sh scripts has regular docker commands in it to start up the containers. I am a still a "newb" at docker and containerization.

**Comment by kspearrin** [comment]
Right now the run command will check for container updates, if using lets encrypt it will try to renew any certs, and then does a `docker-compose up`.

**Comment by jerheij** [comment]
I don't use their certificates, I have my own chain going on. Would you happen to know how to make docker containers auto start at boot of the host?

**Comment by kspearrin** [comment]
You can just create a script to execute `docker-compose up` on system startup.
