### ISSUE TITLE
Unhandled System.Data.SqlClient.SqlException

### ISSUE THREAD

**Issue by cig0** [bitwarden/core#328]
Docker version 18.03.1-ce, build 9ee9f40
docker-compose version 1.21.1, build 5a3f1a3

1.20.0: Pulling from bitwarden/setup
Digest: sha256:42c20f5c5aaf2ab90619ba41a100c7ac258ab412d439cbbf43185d573eadd35c
Status: Image is up to date for bitwarden/setup:1.20.0

Migrating database.

Unhandled Exception: System.Data.SqlClient.SqlException: Login failed for user 'sa'.
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 285
   at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 57

----

Host: macOS 10.13.6

**Comment by kspearrin** [comment]
I'm guessing you installed it before? You probably need to delete the old database's docker volume.

```
docker volume ls
docker volume rm docker_mssql_data
```

Then run

```
./bitwarden.sh updatedb
```
