### ISSUE TITLE
Install behind Firewall, no information what ports has to be open

### ISSUE THREAD

**Issue by Schroeffu** [bitwarden/core#329]
I am trying to install Bitwarden behind a firewall, its not validating id/key.
What is the host:port destination which is required to be open to validate?

Error while trying install Bitwarden:

(!) Enter your installation id (get at https://bitwarden.com/host): a(...)
(!) Enter your installation key: D(...)
Unable to validate installation id. Problem contacting Bitwarden server.

thx :- )!

**Comment by kspearrin** [comment]
You should open:

- api.bitwarden.com
- identity.bitwarden.com (if used push notifications)
- push.bitwarden.com (if used push notifications)

**Comment by Schroeffu** [comment]
thank you so much. all of these endpoints port 443 only, i guess? @kspearrin

**Comment by kspearrin** [comment]
Yes.
