### ISSUE TITLE
Clean install on Raspian 

### ISSUE THREAD

**Issue by swaaws** [bitwarden/core#331]
Using default tag: latest
latest: Pulling from certbot/certbot
f2f9cebd2755: Pulling fs layer 
3208125f5e26: Pulling fs layer 
9f0945eafb48: Pulling fs layer 
dacb0486d4f1: Pulling fs layer 
3453daca847d: Pulling fs layer 
49a640871eb8: Pulling fs layer 
a99f1c135d1f: Pulling fs layer 
18e657d931fc: Pulling fs layer 
1b497e91a9bb: Pulling fs layer 
049b1950292c: Pulling fs layer 
c85ecbaba1ed: Pulling fs layer 
ac9e5cc18d77: Pulling fs layer 
45ad360a3107: Pulling fs layer 
0b2215b84327: Pulling fs layer 
d2cb931c5137: Pulling fs layer 
325a630787d9: Pulling fs layer 
08b641c26ef3: Pulling fs layer 
b47b192b28ee: Pulling fs layer 
b8319fb6cd07: Pulling fs layer 
ecc026d32c43: Pulling fs layer 
d9454535697f: Pulling fs layer 
Pulling repository docker.io/certbot/certbot
Tag latest not found in repository docker.io/certbot/certbot

**Comment by kspearrin** [comment]
Not enough details. No idea what the problem is.

**Comment by swaaws** [comment]
Pulling repository docker.io/certbot/certbot
Tag latest not found in repository docker.io/certbot/certbot
