### ISSUE TITLE
Logins in organisations not showing up in Apps anymore

### ISSUE THREAD

**Issue by PeterLustig** [bitwarden/core#336]
Hello,

We share an organisation, but since the last update to the system all applications we use (Firefox App, OS X App) only show the user saved logins and the logins shared or saved in the organisation disappeared. In the web application you can still see them with the same user.
Core Version is 2.0.0 but Applications don't seem to go over 1.4.0 for the OS X release and 1.2.8 for the Firefox AddOn.
I guess this is the problem? When will a new version come out?

**Comment by kspearrin** [comment]
Is the organization still active? Check under organization -> billing.

**Comment by PeterLustig** [comment]
I can't find the billing option.
It seems to be active though, I can still access and configure it in the web application?

**Comment by kspearrin** [comment]
You can always manage the org from the web vault, even if deactivated.

Look here:

![image](https://user-images.githubusercontent.com/1190944/43833904-55074b4e-9ada-11e8-9bfe-7cab4ac7ed8a.png)

**Comment by kspearrin** [comment]
You can only access this if you are an organization owner.

**Comment by PeterLustig** [comment]
Ah yes, I talked to the owner and it is indeed inactive. It somehow deactivated while updating.
How can we reactivate it?

**Comment by kspearrin** [comment]
You can download your license file from vault.bitwarden.com and re-apply it back to the organization using the "Update License" button.
