### ISSUE TITLE
Searches are broken

### ISSUE THREAD

**Issue by luispabon** [bitwarden/core#344]
Looks like all of a sudden searches are broken. I'm seeing this on the firefox extension and the website. The android app works fine. For instance, I have number of logins in google. I cannot find any of them anymore.

This worked on friday just two days ago.

For instance, stuff that can't be found looking for `google` (these are login names in BW):
```
accounts.google.com
drive.google.com
```

However if I search for `accounts` or `drive` they do show up.

 In general, it seems that it will only find stuff by name as long as what you're searching is not in the middle of the name.

**Comment by kspearrin** [comment]
This should be fixed in next versions.

**Comment by luispabon** [comment]
Thank you 👍
