### ISSUE TITLE
self-hosted /etc/cron.d/bitwarden-cron not executed 

### ISSUE THREAD

**Issue by boschkundendienst** [bitwarden/core#351]
Hi,
there seems to be an issue with the execution of `/etc/cron.d/bitwarden-cron`.

After a fresh start of the container(s) the mssql backup script in the bitwarden-mssql container never executes. For troubleshooting I ran

```
docker exec -it bitwarden-mssql /bin/bash
```

Manual execution of the backup script worked from within the container.

What also works (from the host system) is:

```
/usr/bin/docker exec -u bitwarden bitwarden-mssql /backup-db.sh
Processed 1272 pages for database 'vault', file 'vault' on file 1.
Processed 3 pages for database 'vault', file 'vault_log' on file 1.
BACKUP DATABASE successfully processed 1275 pages in 0.184 seconds (54.114 MB/sec).
```

So the problem must be related to cron as someone already pointed out here: https://github.com/bitwarden/core/issues/156

For troubleshooting purpose I also installed `rsyslog` and started it manually with `rsyslogd` to be able to look at `/var/log/syslog`.

It shows something like this:

```
Sep  1 01:37:01 e8e2630eb4ee cron[24]: (*system*bitwarden-cron) NUMBER OF HARD LINKS > 1 (/etc/cron.d/bitwarden-cron)
```
So cron complains about more than 1 hardlink for `/etc/cron.d/bitwarden-cron`. The following command veriies that:

```
root@e8e2630eb4ee:/# stat -c %h /etc/cron.d/bitwarden-cron 
6
root@e8e2630eb4ee:/# stat -c %h /etc/crontab 
8
```

I fixed it by touching the files:

```
root@e8e2630eb4ee:/etc/cron.d# touch /etc/cron.d/bitwarden-cron 
root@e8e2630eb4ee:/etc/cron.d# stat -c %h /etc/cron.d/bitwarden-cron 
1
root@e8e2630eb4ee:/etc/cron.d# touch /etc/crontab               
root@e8e2630eb4ee:/etc/cron.d# stat -c %h /etc/crontab 
1
```

The syslog now no longer complains it just reloads the crontabs:

```
Sep  1 01:50:01 e8e2630eb4ee cron[24]: (*system*bitwarden-cron) RELOAD (/etc/cron.d/bitwarden-cron)
Sep  1 01:51:01 e8e2630eb4ee cron[24]: (*system*) RELOAD (/etc/crontab
```

So I found a solution but not the initial cause of the problem which might be related to the docker container creation.

I think this problem could be similar like: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=647193 or https://github.com/phusion/baseimage-docker/issues/198 or https://stackoverflow.com/a/38850273

Maybe one of the pro's can find out how to fix this permanently.

For a workarround I backup via a cron job within my hosts crontab but of course the implemented solution should be fixed.

Thanks in advance

**Comment by boschkundendienst** [comment]
I wrote this small bash script to fix the problem manually after every update:

```
#!/bin/bash
echo "before"
/usr/bin/docker exec bitwarden-mssql stat -c %h /etc/cron.d/bitwarden-cron
/usr/bin/docker exec bitwarden-mssql stat -c %h /etc/crontab
echo "fixing"
/usr/bin/docker exec bitwarden-mssql touch /etc/cron.d/bitwarden-cron 
/usr/bin/docker exec bitwarden-mssql touch /etc/crontab 
echo "after"
/usr/bin/docker exec bitwarden-mssql stat -c %h /etc/cron.d/bitwarden-cron
/usr/bin/docker exec bitwarden-mssql stat -c %h /etc/crontab
echo "backup should now work because we changed the number of hard links to 1"
```

**Comment by kspearrin** [comment]
So all we need to do is touch the crontab files? I don't believe we are using `/etc/crontab` though. Only `/etc/cron.d/bitwarden-cron` is used for the backups.

**Comment by kspearrin** [comment]
Should be fixed with https://github.com/bitwarden/core/commit/fceef7133ed3351f747b9f786c1a68b5cb2f9a02
