### ISSUE TITLE
Missing Message-ID header for SMTP mail

### ISSUE THREAD

**Issue by 0mni** [bitwarden/core#352]
```
Return-Path: <no-reply@xxxxxx>
Delivered-To: xxxxxx@xxxxxx
Received: from xxxxxx
	by xxxxxx with LMTP id WCSIMvzpk1tVTQAAQhSVmw
	for <xxxxxx@xxxxxx>; Sat, 08 Sep 2018 11:25:48 -0400
Received: from e8b77f0d65ac (unknown [192.168.128.9])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by xxxxxx (Postfix) with ESMTPS id 9D893A0161
	for <xxxxxx@xxxxxx>; Sat,  8 Sep 2018 11:25:47 -0400 (EDT)
MIME-Version: 1.0
From: "Bitwarden" <no-reply@xxxxxx>
To: xxxxxx@xxxxxx
Date: 8 Sep 2018 15:25:47 +0000
Subject: [Admin] Continue Logging In
Content-Type: multipart/alternative;
 boundary=--boundary_0_3577c190-6fdb-4769-b21a-708431873377
X-Spamd-Bar: ++++++++++++++
X-Spam-Level: **************
Authentication-Results: xxxxxx;xxxxxx
	dmarc=fail reason="No valid SPF, No valid DKIM" header.from= (policy=reject);
	spf=permerror smtp.mailfrom=no-reply@xxxxxx
X-Spam: Yes
```

I am having an issue where e-mail sent from the docker image is marked as spam, as it is using my SMTP server as a relay, as opposed to using the actual e-mail account used to authenticate as an e-mail client.  I am hosting my own e-mail, and have several servers using my main e-mail server as a client as opposed to a relay when sending e-mail, and thus do not have issues with sending mail as it is passed through the my server properly to not be marked as spam.  Is there a configuration I can change on the docker image so that it will use my SMTP server as a client as opposed to having the docker image attempt to work as its own e-mail server?

**Comment by kspearrin** [comment]
The application does not act as it's own email serve. It should just connect as an SMTP client to whatever server information you provide in the settings.

I don't know a lot about SMTP and how relays work, so maybe there is something off in our settings for this type of setup.

You can see the .NET code here:
https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/SmtpMailDeliveryService.cs#L30

**Comment by 0mni** [comment]
I did some digging, looking at the logs of how the messages are sent, and I think I found the problem.

The messages being sent by the docker server is missing the message-id header:
```
Sep  8 12:39:27 xxxxxx postfix/smtpd[13313]: connect from unknown[192.168.192.2]
Sep  8 12:39:28 xxxxxx postfix/smtpd[13313]: 127A8A0162: client=unknown[192.168.192.2]
Sep  8 12:39:28 xxxxxx postfix/cleanup[13318]: 127A8A0162: message-id=<>
Sep  8 12:39:29 xxxxxx postfix/qmgr[4285]: 127A8A0162: from=<no-reply@xxxxxx>, size=22725, nrcpt=1 (queue active)
Sep  8 12:39:29 xxxxxx postfix/smtpd[13313]: disconnect from unknown[192.168.192.2] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 commands=6
Sep  8 12:39:29 xxxxxx dovecot: lmtp(13327): Connect from local
Sep  8 12:39:29 xxxxxx dovecot: lmtp(xxxxxx@xxxxxx): QBnhLkH7k1sPNAAAQhSVmw: sieve: msgid=unspecified: stored mail into mailbox 'Junk'
Sep  8 12:39:29 xxxxxx postfix/lmtp[13326]: 127A8A0162: to=<xxxxxx@xxxxxx>, relay=server000.danlee.ca[private/dovecot-lmtp], delay=1.7, delays=1.7/0.01/0.01/0.01, dsn=2.0.0, status=sent (250 2.0.0 <xxxxxx@xxxxxx> QBnhLkH7k1sPNAAAQhSVmw Saved)
Sep  8 12:39:29 xxxxxx postfix/qmgr[4285]: 127A8A0162: removed
Sep  8 12:39:29 xxxxxx dovecot: lmtp(13327): Disconnect from local: Successful quit
Sep  8 12:39:29 xxxxxx dovecot: indexer-worker(xxxxxx@xxxxxx): Indexed 1 messages in Junk (UIDs 99..99)
```

Because of this, the spam filter is registering it as spam as it does not exist.

**Comment by 0mni** [comment]
The message id header is not required currently, but is used by several spam filters.

As for what it needs to be set to, something unique.  For instance  you can use the unix time code for the first part of the message id, followed by the process id of the thread doing the work, followed by the md5, doesn't have to be md5, of the senders email plus the destination email

So an e-mail sent Sep 09 17:28:37 2018 EDT would have a unix time of 1536528517.
An example process id would be 789.
Sender's email would be no-reply@mydoman.com
Destination e-mail would be me@mydomain.com
The MD5 hash of the combination of the e-mails would be f3f6ad31b7282f520d027e9f6de3f213

Combine them together and separate with a - and you get:
1536528517-789-f3f6ad31b7282f520d027e9f6de3f213

**Comment by kspearrin** [comment]
Can it be just any random value or does it need to follow that specific format?

**Comment by 0mni** [comment]
No specific format, just unique ie no two emails anywhere with same value.

**Comment by kspearrin** [comment]
Should be fixed with https://github.com/bitwarden/core/commit/0fda72c6b04e9627b4a42da1f8de1acbc6b3f6ad
