### ISSUE TITLE
Cannot restart BitWarden in an offline environment

### ISSUE THREAD

**Issue by cstodd** [bitwarden/core#353]
Is it necessary to always run BitWarden in an internet-connected environment?

I am deploying BitWarden to a site that by necessity will not have internet access. I made an image of the BitWarden server I composed and transferred it to this environment - but when running ./bitwarden.sh start, BitWarden blew away all the existing containers and automatically tried to pull new ones from docker hub, which failed, of course. 

There are many environments which prohibit internet access or are off-line / enclaved. Is there anyway to prevent BitWarden from blowing away the containers and trying to pull from docker hub?

**Comment by kspearrin** [comment]
Hi,
In this type of environment you wouldn't want to use `./bitwarden.sh` at all since it does a lot of still that requires an internet connection. Just use `docker-compose` manually.

```
cd ./bwdata/docker
docker-compose up -d
```
