### ISSUE TITLE
ValidateUsersJob wasn't executed after license refresh on self-hosted system

### ISSUE THREAD

**Issue by svewap** [bitwarden/core#357]
My trial license expired. So my user was deactivated this morning. 
```
2018-09-19 06:00:00.010 +00:00 [Information] Starting job "ValidateUsersJob" at 09/19/2018 06:00:00.
2018-09-19 06:00:00.070 +00:00 [Information] Validating premium for 1 users.
2018-09-19 06:00:00.071 +00:00 [Information] User 33333-3333-3333-33333-333333333("user@mail.com") has an invalid license and premium is being disabled.
2018-09-19 06:00:00.117 +00:00 [Information] Checking to restore premium for 1 users.
2018-09-19 06:00:00.119 +00:00 [Information] Finished job "ValidateUsersJob" at 09/19/2018 06:00:00.
```
I uploaded the new license. Now in my admin panel the organisation and my user is active, but my user, which is the Owner at the same time, is not a premium user. How can this be? I think the ValidateUsersJob should be started immediately after uploading the new license. There is nothing in the log file.

**Comment by kspearrin** [comment]
It will run again in a few hours and correct the issue.

**Comment by svewap** [comment]
Yes, but until this I cannot access to my passwords! Unacceptable!

**Comment by kspearrin** [comment]
Just because you are not premium does not mean you cannot access your passwords. Why cant you access your passwords?

**Comment by svewap** [comment]
Because the passwords are stored in my organisation as shared passwords. Until I'm no premium user, I cannot access them.
In the meantime, the job has been running and I am again a premium user. Now I can access again. However, this was not a good time.
Also, the web interface says that my organization is still disabled, even though it is working again. Another bug.

**Comment by svewap** [comment]
I think to run the job after license upload is still a thing, that should be done. So nobody have to wait a few hours.

**Comment by kspearrin** [comment]
Premium status has nothing to do with being able to access shared passwords from an organization. You can access shared passwords even if you are not premium.

What does your organization say under the Billing page?

**Comment by svewap** [comment]
Abo
Enterprise (Annually)
Ablaufdatum
07.11.2019

But on the top in Red:  "Organisation ist deaktiviert"

**Comment by kspearrin** [comment]
The organization is still deactivated is the problem. Not that you arn't premium.

What happens if you update your license again?

**Comment by svewap** [comment]
Thank you for your support.
The facts are:
- My organisation was deactivated, because the trial license expired
- I couldn't access to the passwords of my organisation anymore
- I uploaded the new license. Valid until next year.
- I had to wait until the job was started a few hours later (not good)
- Now I can access to the shared passwords (via browser plugin) again.
- On my personal account of my https://bitwarden.domain/ my organisation is still disabled with the warning.
- If I check this on the https://bitwarden.domain/admin/ page, my organisation is "Enabled, expires X/X/X".
- I reuploaded the license file
- So there is sill a discrepancy between the admin page and the organisation in my personal account.
- I restarted the docker container, but nothing changed
![auswahl_263](https://user-images.githubusercontent.com/1734738/45754321-a305b800-bc1b-11e8-88d4-a6c0908dbb3d.png)
![auswahl_265](https://user-images.githubusercontent.com/1734738/45754340-b749b500-bc1b-11e8-8a25-1875e4bbd9b4.png)
I think that's another bug. Maybe a new ticket?

**Comment by kspearrin** [comment]
Can you try logging out and back into the web vault to see if the disabled goes away then?

**Comment by svewap** [comment]
Ok, this "fixed" it :+1: . I had to make a real log off and not just to make browser reload and login again. Strange. Thank you for your support.
