### ISSUE TITLE
Deleting accounts with large vault times out with error

### ISSUE THREAD

**Issue by ingenuitor** [bitwarden/core#36]
Hello, I'm trying to remove my vault data as well and receive an error. It seems to run for a long time @ 1m 40s before displaying the error.

Errors have occured
An unexpected error has occured.

Maybe it's a simple script timeout, due to parsing size limits?

**Comment by kspearrin** [comment]
This is a known issue still when deleting large vaults. Contact us and we can do it for you manually for now. https://bitwarden.com/contact/

**Comment by ingenuitor** [comment]
Thanks for the great support, I sent a request via your contact form. Keep up the great work, the foundation is very nice with a clean simple UI.  Best regards.....

**Comment by kspearrin** [comment]
This is now resolved.
