### ISSUE TITLE
Understanding ssl_certificate_path directory mapping

### ISSUE THREAD

**Issue by FoxBJK** [bitwarden/core#367]
I'm struggling to understand something from the config.yml file:

```
# The actual certificate. (Required if using SSL without managed Let's Encrypt)
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_certificate_path: /etc/ssl/self/domain/cert.pem
```

I can't figure out where this would be mapped to. If the bwdata directory is under /root/ for example, what's the path to the certificate (/root/bwdata/ssl/self/domain/cert.pem) that I would put into the config file?

**Comment by kspearrin** [comment]
The path is relative to the mapped volume in the container. So `/etc/ssl/self/domain/cert.pem`

**Comment by FoxBJK** [comment]
Thank you! That's all I needed.

**Comment by methmouth** [comment]
do you guys make this thing as unintuitive as possible to discourage self-hosting?  asking for a friend...
