### ISSUE TITLE
Running behind reverse proxy

### ISSUE THREAD

**Issue by wuha** [bitwarden/core#371]
I'm trying to install bitware on a new server.
On my old server the setup asked me if I want to use a proxy.
When installing on the new Serevr this question is no longer asked:

Status: Downloaded newer image for bitwarden/setup:1.24.0
(!) Enter your installation id (get at https://bitwarden.com/host): xxxxxx
(!) Enter your installation key: xxxxxxxx
(!) Do you have a SSL certificate to use? (y/n): n
(!) Do you want to generate a self-signed SSL certificate? (y/n): n
Generating key for IdentityServer.
Generating a 4096 bit RSA private key
...............................................++
................................................................................++
writing new private key to 'identity.key'
-----
!!!!!!!!!! WARNING !!!!!!!!!!
You are not using a SSL certificate. Bitwarden requires HTTPS to operate.
You must front your installation with a HTTPS proxy or the web vault (and
other Bitwarden apps) will not work properly.
Building nginx config.
Building docker environment files.
Building docker environment override files.
Building FIDO U2F app id.
Building docker-compose.yml.
Installation complete

How can I run Bitwarden behind a reverse proxy?

**Comment by kspearrin** [comment]
You can make whatever port adjustments you need for your proxy in the `./bwdata/config.yml` file.
