### ISSUE TITLE
Why not more than 1 Million KDF Iterations

### ISSUE THREAD

**Issue by Pingggg** [bitwarden/core#375]
Hey,why is there a limit on how many KDF Iterations we can use?Shouldnt the limit be a billion or so?

Any particular reason why it is only 1 Million?

**Comment by kspearrin** [comment]
The only real reason is to stop someone from bricking their account that doesn't know what they are doing.

**Comment by kspearrin** [comment]
It's possible we could support. Feel free to open it as a feature request on the forums.
