### ISSUE TITLE
SSL & nginx for self-hosted installations

### ISSUE THREAD

**Issue by NerdDiffer** [bitwarden/core#376]
Hello, I'm having trouble getting my SSL certs picked up by nginx and I don't know what I'm doing wrong.
I've already used Certbot to supply SSL certs for my domain, so during installation on the second question prompt about using Certbot to install + manage certs, I selected no.

I've made links from the `bwdata` installation directory to the certificates on the host, like so:

```sh
HOST_DIR="/etc/letsencrypt/live/my-domain"
LINK_DIR="/path/to/bwdata/ssl/my-domain"

sudo ln -svf $HOST_DIR/fullchain.pem $LINK_DIR/certificate.crt
sudo ln -svf $HOST_DIR/privkey.pem   $LINK_DIR/private.key
sudo ln -svf $HOST_DIR/chain.pem     $LINK_DIR/ca.crt
```

I can `./bitwarden.sh start`. However when I `docker ps`, the nginx container is continually restarting:

```
b6db3d08a4f0        bitwarden/nginx:1.24.0           "/entrypoint.sh"    13 minutes ago      Restarting (1) 40 seconds ago                       bitwarden-nginx
```

The error logs at `bwdata/logs/nginx/error.log` say:

```
[emerg] 1#1: BIO_new_file("/etc/ssl/my-domain/certificate.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/my-domain/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

What is the correspondence between the basenames of Certbot-generated files (`fullchain.pem`, `chain.pem`, `cert.pem`) and the names expected by bitwarden?

Do I even need to sym-link from the bitwarden installation directory to the host ssl certificates?

I don't really understand the comment in `config.yml` saying: "The `./ssl` host directory is mapped to `/etc/ssl` within the container". In this situation, what values would I put in for the  `ssl_certificate_path`, `ssl_ca_path` keys in `config.yml`?

Thank you!

**Comment by kspearrin** [comment]
The containers use docker volume mapping. `./bwdata/ssl` on the host machine is mapped to the nginx container's `/etc/ssl` directory. So if you place a file in `./bwdata/ssl/cert.pem`, inside the container it is available at `/etc/ssl/cert.pem`.

I am not sure symlinks work on the host machine in relation to docker volume mapping. You will probably need to research this.

For LE, you can use:

ssl_certificate_path = fullchain.pem
ssl_key_path = privkey.pem
ssl_ca_path= fullchain.pem

**Comment by NerdDiffer** [comment]
Great, I got it working. Thanks for clearing that up.

I had incorrectly mapped the value for `ssl_ca_path` in my config file.
Also, symlinks definitely did not work for me, so I copied the files from `/etc/letsencrypt/live/my-domain/` over to `./bwdata/ssl/my-domain/`. Is that the recommended practice?
