### ISSUE TITLE
mozilla.org and firefox.com should not be equivalent domains

### ISSUE THREAD

**Issue by mhammond** [bitwarden/core#38]
mozilla.org and firefox.com are listed as equivalent domains. However, accounts.firefox.com is used to access Firefox Account (ie, Sync) credentials, so bitwarden will offer to fill any mozilla.org page with a password that will allow access to all your synced information.

While the root of firefox.com will redirect to mozilla.org, there are no other accounts on firefox.com, so there's no good reason to keep them as equivalent, and doing so risks a user accidentally entering a very important password into the wrong site (or just as bad, encourage them to reuse their Firefox Accounts password on mozilla.org). Users can re-add them if they so choose, but I think that default should be removed.

**Comment by kspearrin** [comment]
Good point. Thanks.

**Comment by kspearrin** [comment]
fixed for next release
