### ISSUE TITLE
delete old bitwarden docker images

### ISSUE THREAD

**Issue by GPConnect** [bitwarden/core#381]
anyway to add in the script the ability to remove the unused bitwarden images after upgrade ? 
Thanks

**Comment by kspearrin** [comment]
I believe that the bitwarden script should already do this for you on updates.

It runs `docker image prune -f --filter="label=com.bitwarden.product=bitwarden"`

**Comment by kspearrin** [comment]
I would have throught the prune option would have cleared those out. Can you try running `docker image prune`?

**Comment by GPConnect** [comment]
"docker image prune" didn't help but "docker system prune -a" did the clean up ! 
<img width="746" alt="capture d ecran 2018-10-20 a 22 00 23" src="https://user-images.githubusercontent.com/25872687/47262334-0cdfde80-d4b4-11e8-846e-2c95a17762ff.png">

**Comment by kspearrin** [comment]
Should be fixed in next version. Thanks.
