### ISSUE TITLE
Logout doesn't really do anything

### ISSUE THREAD

**Issue by detunized** [bitwarden/core#383]
I noticed that after logout I can still use the auth cookie to request the vault content with `curl`. It's not very critical since it's encrypted. But I assume after I logged out the session should be gone and the auth token should no longer be valid. I noticed you have the code to handle this but for some reason it doesn't seem to do anything (judging by the side effects).

https://github.com/bitwarden/core/blob/826b4a430f5297e038a7eb23ff4678ab51fec6f3/src/Api/Controllers/DevicesController.cs#L109

**Comment by kspearrin** [comment]
Logging out clears the session token from the local device. It does not invalidate the token from the server. The code you linked is for clearing a push token, not a session token.

**Comment by detunized** [comment]
So, it works as designed you're saying. Ok, then I close the ticket. I would expect the token to get invalidated after I logged out though.
