### ISSUE TITLE
Setup image is deleted / pulled at every restart

### ISSUE THREAD

**Issue by Mart124** [bitwarden/core#388]
Hello,

Setup image is deleted / pulled at every restart.
At restart, `setup` is not used so pruned by `run.sh`, and then pulled again to print environment...

Could we avoid this ?

Thank you !

**Comment by Mart124** [comment]
Of course feel free to close this if you think this is not an issue, I can simply comment-out the prune command 👍

**Comment by kspearrin** [comment]
I removed the `--all` option from the `prune` command which should fix it.

**Comment by Mart124** [comment]
Yes it helps, thanks.
However now, only dangling images will be removed, so the ones running auto-update will certainly run out of space one day.
Not sure what was the first goal of the `prune` command though :)
Note that there is a `--filter` option which could perhaps simply be used with `--all` to exclude images at current version level.

**Comment by Mart124** [comment]
Well I tried to do such things but we can't as we can only filter on `labels` :
https://docs.docker.com/engine/reference/commandline/image_prune/
This would require a version number label, as we did for `"com.bitwarden.product": "bitwarden"`.

**Comment by kspearrin** [comment]
Looks like we can do an `AND` filter with multiple `--filter`s.

ref: https://stackoverflow.com/questions/53066701/do-multiple-docker-filter-options-perform-a-local-and-or-or-operation

I've added another label for the next version that we can use to exclude the setup project.

ref: https://github.com/bitwarden/core/commit/5136b191f142124431f6c760ee0220f16881bf82

**Comment by Mart124** [comment]
Perfect 👍
We'll still keep old setup images across the updates, but they are not so big, so should not be an issue.

**Comment by kspearrin** [comment]
Should be pruning all with a setup filter now with 1.26.0
