### ISSUE TITLE
Migrations cannot be executed on a non-dockerised database via the `updatedb` command

### ISSUE THREAD

**Issue by Szasza** [bitwarden/core#389]
I try to host Bitwarden on AWS, using SQL Server on RDS as a database.

I managed to set up the infrastructure without a problem, however I cannot run the migrations using the command `./bitwarden.sh updatedb` - if I run that command, a connectivity error pops up.

After taking a look at [https://github.com/bitwarden/core/blob/976869c9686a7af5090664030b9d5acea1b217ca/util/Setup/Program.cs#L150-L153](https://github.com/bitwarden/core/blob/976869c9686a7af5090664030b9d5acea1b217ca/util/Setup/Program.cs#L150-L153) I noticed that the migration script contains a hard-coded hostname instead of getting it from an env or settings file, similarly to the connection string in the case of the rest of the stack.

Is there a chance to fix the migration execution, or to provide a workaround which is not "run the migration files one by one via mssql-cli"?

Thank you in advance for the help, it is much appreciated.

**Comment by szasza-oneaffiniti** [comment]
In the meantime I worked around the issue by:
* cloning the repo to my local machine
* changing the hostname in the aforementioned lines
* building a new docker image
* uploading it to my host
* replacing the stock image
* removing the pull call from `bwdata/scripts/run.sh` for the setup container
* running `./bitwarden.sh updatedb`

It worked, but it is not necessarily sustainable.

**Comment by Szasza** [comment]
In the meantime I worked around the issue by:
* cloning the repo to my local machine
* changing the hostname in the aforementioned lines
* building a new docker image
* uploading it to my host
* replacing the stock image
* removing the pull call from `bwdata/scripts/run.sh` for the setup container
* running `./bitwarden.sh updatedb`

It worked, but it is not necessarily sustainable.

**Comment by kspearrin** [comment]
Should be resolved in next version by reading connection string from env file rather than reconstructing it.

**Comment by Szasza** [comment]
Awesome, thank you @kspearrin , it is much appreciated.
