### ISSUE TITLE
Update password problem

### ISSUE THREAD

**Issue by oldenboom** [bitwarden/core#391]
Consider a site where I can login using a username-password-combo. Then, at a certain point I want to  login using another username-password-combo. I enter those manually. The browser extension wrongly recognizes a password change and offers me to update the password in Bitwarden. It is wrongly recognized as the usernames don't match. Therefore Bitwarden should offer me to add a new record to the vault instead of updating the current one.

The site involved concerns a Dolibarr installation.

**Comment by kspearrin** [comment]
That should already be the case, so whenever you are entering the second username-password combo for whatever reason it is detecting your first username still. Is this a pubic website?

**Comment by oldenboom** [comment]
This is not a public website. It's a Dolibarr setup.
I've setup an instance at bitwarden.floating-point.nl

login: admin
password: stroopwafel1

I tried to replicate the issue but wasn't able to do so with this 
instance?!?

I'll keep the instance for a while for you to play around with.

Rembert.

**Comment by kspearrin** [comment]
I logged in, but I do not see where I complete a secondary login at to try to reproduce the issue.

**Comment by oldenboom** [comment]
Hah, yes, I created some additional accounts:

admin2 - stroopwafel2
another - stroopwafel


-- 
*Rembert Oldenboom /* Floating Point <https://www.floating-point.nl/>
tel: 06 - 3195 9633 <callto:0631959633>
Cruquiusweg 1 | 2102 LS Heemstede

**Comment by kspearrin** [comment]
> Consider a site where I can login using a username-password-combo. Then, at a certain point I want to login using another username-password-combo. I enter those manually. 

So you login with `admin2`, save it, then log out and then back in with `another`?

**Comment by oldenboom** [comment]
yep, that's the idea. But I wasn't able to replicate the issue for some 
reason. It seems Bitwarden is working fine. Better close the issue. I'll 
find it back when it reoccurs.
-- 
*Rembert Oldenboom /* Floating Point <https://www.floating-point.nl/>
tel: 06 - 3195 9633 <callto:0631959633>
Cruquiusweg 1 | 2102 LS Heemstede
