### ISSUE TITLE
1password import imports trashed items with no differentiation

### ISSUE THREAD

**Issue by mahyar** [bitwarden/core#397]
The 1pif file does tag trashed items with a `"trashed":true,` tag.  Maybe bitwarden can automatically put them in one category for easy categorization, such as a '1password import trashed items'.  Another alternative would be to implement a trashbin feature and put those imported items into the new trashbin.

**Comment by kspearrin** [comment]
This is not the correct repo for the password importers. Please open a single issue under the web repo for any issue you are having with the 1password importer.
