### ISSUE TITLE
1 password import does not import the password part of password items

### ISSUE THREAD

**Issue by mahyar** [bitwarden/core#398]
In a 1pif import `"typeName":"passwords.Password"` items do not have their passwords fields imported, but instead show up as weird stub items:

<img width="510" alt="screen shot 2018-11-14 at 12 23 59 am" src="https://user-images.githubusercontent.com/22130/48469509-f0c61900-e7a3-11e8-946c-cdf3d5eec3e5.png">

`"typeName":"webforms.WebForm` do seem to get imported properly

This came from a 1password 6.8.9 export

**Comment by kspearrin** [comment]
This is not the correct repo for the password importers. Please open a single issue under the web repo for any issue you are having with the 1password importer.
