### ISSUE TITLE
Where are the tests?

### ISSUE THREAD

**Issue by mahyar** [bitwarden/core#399]
I tried finding unit tests, integration tests or anything else in a few repos.  Are they kept somewhere private or does most of the codebase have zero tests?  The only thing I could find were a couple of tests in the mobile app.

**Comment by javenschuetz** [comment]
Is there really nobody who can confirm or deny the existence of automated tests?

**Comment by Routhinator** [comment]
Looking through the build logs, it does appear that this repository lacks any automated testing.

In fact, none of the bitwarden repositories have automated testing.

This is concerning. Maybe not enough to deter free users, but I know my company saw this issue and immediately said no way to BitWarden, opting to give their dollars to LastPass.

It is in BitWarden's best interests to address this topic.

**Comment by JamesMcMahon** [comment]
This concerns me as I think it will affect the future viability of Bitwarden.

I don't know how you can add features while balancing Pull Request merges and not have reliable automated tests. The ability to add features is going to greatly decrease over time as it will become difficult to add features without breaking anything.

(Either that or the tests are in another repo)

**Comment by kspearrin** [comment]
The core project does not currently have automated testing in place. I have opened an issue to track this here: https://github.com/bitwarden/core/issues/419

@Routhinator Client applications share several hundred tests, mostly around sensitive crypto operations, through the jslib repo.
