### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by olafura** [bitwarden/core#4]
Hi thanks for the project it looks interesting but there is no licence file.

**Comment by unquietwiki** [comment]
Saw the discussion on https://www.reddit.com/r/programming/comments/56ojub/after_1_full_year_of_late_night_development_ive/ , and the author is looking at GPLv3. 

https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses This might help with a final decision. I've used MIT and MPL for my own projects in the past.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/core/commit/8c14b2b177aeaf03206c6c4685a3976a1fa3e732

**Comment by aloisdg** [comment]
@unquietwiki MPL united!
