### ISSUE TITLE
Cannot delete account (Vault)

### ISSUE THREAD

**Issue by labor4** [bitwarden/core#411]
I found a logical loop!

- I locked myself out
- my account contains a test organization
- i cannot delete my account

It says to me:
"You must leave or delete any organizations that you are the only owner of first."

**Comment by kspearrin** [comment]
Yes, we do this to prevent people to accidentally orphaning users in their organization, leaving it ownerless. Email support@bitwarden.com and we can delete it for you.

**Comment by labor4** [comment]
Did that, thanks!
