### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by SteffenBarthel** [bitwarden/core#413]
Why are these questions no longer there?
```
(!) Do you want to use the default ports for HTTP (80) and HTTPS (443)? (y/n): n
(!) HTTP port: 80
(!) HTTPS port: 443
```

**Comment by SteffenBarthel** [comment]
rebuild?
How?

**Comment by kspearrin** [comment]
Please read the comments in the file you are editing:

> # 
> # Note: After making changes to this file you need to run the `rebuild` or `update`
> # command for them to be applied.
> #

**Comment by SteffenBarthel** [comment]
Does rebuild delete the data?

**Comment by kspearrin** [comment]
No

**Comment by SteffenBarthel** [comment]
502 Bad Gateway
nginx
