### ISSUE TITLE
Self Hosted - Verification mail not sent

### ISSUE THREAD

**Issue by cippaciong** [bitwarden/core#416]
Hello, I know there are quite a lot of similar issue by now but even though I've read through all of them I wasn't able to get verification email working.
I have a self hosted instance running on docker and everything seems to be working fine except for verification emails which are not sent.

I'm using an external account managed by my hosting provider (aruba.it) and I'm following their instructions to configure smtp connections.

The mail portion of my `global.override.env` is as follows:
```
globalSettings__mail__replyToEmail=myemail@mydomain.it
globalSettings__mail__smtp__host=smtps.aruba.it
globalSettings__mail__smtp__username=myemail@mydomain.it
globalSettings__mail__smtp__password=mypassword
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=465
globalSettings__mail__smtp__useDefaultCredentials=false
```
When I send a verification email I don't see any relevant log in `bwdata/logs` but the verification email never arrives.

Trying to figure out if these settings worked outside of bitwarden I wrote this simple python script and it works
```
import smtplib
from email.mime.text import MIMEText

msg = MIMEText(f"Test body")

to_addr = "recipient@gmail.com"
from_addr = "myemail@mydomain.it"

msg['Subject'] = "Test subject"
msg['To'] = to_addr
msg['From'] = from_addr

#put your host and port here 
s = smtplib.SMTP_SSL('smtps.aruba.it:465')
s.login(from_addr,'mypassword')
s.sendmail(from_addr, to_addr, msg.as_string())
s.quit()

print("done")
```
Any idea?
Thanks

**Comment by cippaciong** [comment]
I made a test with the demo account from Mailgun and I was able to receive the email, I would exclude a firewall issue (I used port 587 rather than 465 for that test though) since all outgoing connections are allowed in my setup.

**Comment by kspearrin** [comment]
I am not sure. Maybe they use a different authentication type or something. Where did you get the SMTP config settings information from?

**Comment by cippaciong** [comment]
Hmm, I tested both "Login" and "Basic" but they didn't work

**Comment by kspearrin** [comment]
Unfortunately I am out of ideas.

**Comment by cippaciong** [comment]
Me neither... I guess this is strictly related to some weird configuration from my hosting provider. I can easily use mailgun/sendgrid/others so I wouldn't spend too much time on this. Thanks anyway :slightly_smiling_face:

**Comment by treefish** [comment]
A very late reply. I think I struck this issue with another Docker application needing to send e-mail (Django/Wagtail). I was also able to write a Python script on the Docker server and it worked. Have a think on the exposed ports of your Docker container. I think I was forced to expose port 587 on the container doing the sending (Celery actually), although there is probably a better way. I have this in my docker-compose.yml file for the Celery container:     

ports:
      - 8589:587
     
It doesn't matter what the exposed port is (8589), as long as it doesn't clash with another port on the Docker host (i.e. another Container).

If there is a better way, I'd love to learn!
