### ISSUE TITLE
Does bitwarden work over tor?

### ISSUE THREAD

**Issue by wontruefree** [bitwarden/core#418]
I want to host my own BitWarden instance but do not want it hosted in the cloud.  Does BitWarden and its client support tor connections or Socks5 connections and can I host a server and have clients connect over tor?

**Comment by kspearrin** [comment]
I am not familiar with what the requirements are for this type of setup, so unfortunately I do not know. Please report back if you discover any issues.

**Comment by wontruefree** [comment]
I am looking to self host. Was this ever fixed?

**Comment by PhoenixDiscord** [comment]
https://tryitands.ee/
