### ISSUE TITLE
Breached passwords alert

### ISSUE THREAD

**Issue by ikoutone** [bitwarden/core#44]
Dashlane has this feature and I think it would be good to have it in bitwarden as well.

https://www.dashlane.com/features/security-alerts

**Comment by kspearrin** [comment]
We could likely introduce some similar features using the HIBP API. https://haveibeenpwned.com/API/v2

**Comment by kspearrin** [comment]
Breach report added to web vault.

**Comment by gkrawiec** [comment]
Unless I am misunderstanding the "Good News, Nothing Found!" mssage, the current implementation seems to only check the bitwarden login email against HIBO. Thats just saving you from going to the HIBO site. Why don't you sweep all the stored sites in the vault, find emails and then provide a checkbox based interface where you ask which of those emails you would like to check and then check each one?

**Comment by kspearrin** [comment]
@gkrawiec That's correct. The report is really just there to make people aware of HIBP.

Automatically checking every unique email in your vault against HIBP database would be a violation of their API terms since that would result in an excessive amount API calls to their system.

**Comment by gkrawiec** [comment]
thanks for the info. Didnt know that.

**Comment by kspearrin** [comment]
Yea, their API only allows to check 1 email at a time, so we'd have to spam them.

**Comment by StephenBrown2** [comment]
Seconded for checking individual username/emails, as I often use the '+string' feature of gmail (and some others) to filter my email logins and protect against spam/breaches.

**Comment by Kesmy** [comment]
@kspearrin  OBO the people in [this Twitter thread](https://twitter.com/troyhunt/status/1085866665651388416), including Troy Hunt himself, HIBP has no issue with this usage.

**Comment by kspearrin** [comment]
@Kesmy We comments back here: https://twitter.com/bitwarden_app/status/1085883055682666496

**Comment by Kesmy** [comment]
Excellent, I caught the wrong thread end in that conversation, so missed the official account's reply.
