### ISSUE TITLE
Shared logins no longer appear in Firefox extension

### ISSUE THREAD

**Issue by ahal** [bitwarden/core#47]
After sharing a few sites, those specific sites no longer appear in the Firefox extension. Both when searching via the vault tab, and when visiting the site and looking at the current tab.

The affected logins are all there when logging into vault.bitwarden.com. They are also present in the Android app. I haven't tested any other apps or extensions.

**Comment by kspearrin** [comment]
This is because we are still waiting for Mozilla to approve the 1.12.0 update that supports sharing.

**Comment by kspearrin** [comment]
I just talked with the Mozilla team and v1.12.3 has now been reviewed and is available. Updating should bring in your shared logins.

https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/
