### ISSUE TITLE
TOTP Generation support for added sites

### ISSUE THREAD

**Issue by trobotham** [bitwarden/core#48]
I do apologize if there is already a feature request for this, I was not able to find it.

1Password includes TOTP support to generate the TOTP codes right in the App for sites which support TOTP (such as GitHub) so that I can pull both my password and TOTP code right out of the app, can this be added to bitwarden? No selfhosted password managers seem to include this.

**Comment by kspearrin** [comment]
This is planned as a premium user feature when that becomes available (maybe this summer?).

**Comment by kspearrin** [comment]
This is done.  https://blog.bitwarden.com/premium-features-file-attachments-2fa-options-totp-priority-support-d4c12e2d9018
