### ISSUE TITLE
Email 2-step Authentification

### ISSUE THREAD

**Issue by Dafnik** [bitwarden/core#5]
It would be nice to see an email 2-step authentification. Thank you for your great app.

**Comment by MooreGuy** [comment]
Also TOTP for two factor

**Comment by kspearrin** [comment]
We can definitely add email. That was on my TODO.

**Comment by Dafnik** [comment]
Thank you!

**Comment by kspearrin** [comment]
This is mostly done and now working in latest dev build on web vault.

**Comment by kspearrin** [comment]
This is done for next release.
