### ISSUE TITLE
Structured Form Fill (Address / Credit Card / etc)

### ISSUE THREAD

**Issue by msitt** [bitwarden/core#52]
It would be nice to have structured storage for some common form fill situations, such as entering addresses or credit card information.

### Contact Info
- Name
- Email
- Address
- Phone number

### Credit Card
- Name on card
- Credit card number
- Expiration date
- CVV code

**Comment by kspearrin** [comment]
We have plans for this.

**Comment by slobo** [comment]
Is there a rough ETA for this?

**Comment by kspearrin** [comment]
End of October is the goal.

**Comment by slobo** [comment]
Awesome, just before my LastPass subscription expires :)

**Comment by dev-manager-uk** [comment]
+1 for this, to move away from LastPass

**Comment by jeremytiki** [comment]
To add to the approval, I'm very excited for this feature as well.

**Comment by rolliradi8** [comment]
That's the feature I need in order to move (entirely) away from LastPass!

**Comment by jyavenard** [comment]
+1

**Comment by Hampfred** [comment]
This would be awesome

**Comment by mredaelli** [comment]
+1

**Comment by kspearrin** [comment]
done for next release

**Comment by jyavenard** [comment]
Will you have an import option from LastPass ?

**Comment by kspearrin** [comment]
@jyavenard We already import from LastPass. https://help.bitwarden.com/article/import-from-lastpass/

LastPass does not export **form fills** though. We will import address and credit card **secure notes** from LastPass to bitwarden though, since those are exported.

**Comment by roccolord** [comment]
@kspearrin Lastpass have export of form fills, not in the web vault, but in there extension. 
"More options->Advanced->Export->Form Fills"

Header of file is:
profilename,profilelanguage,title,firstname,firstname2,firstname3,middlename,lastname,lastname2,lastname3,username,gender,birthday,ssn,company,address1,address2,address3,city,county,state,state_name,zip,country,country_cc3l,country_name,timezone,email,mobileemail,phone3lcc,phone,phoneext,fax3lcc,fax,faxext,evephone3lcc,evephone,eveext,mobilephone3lcc,mobilephone,mobileext,ccname,ccnum,ccstart,ccexp,cccsc,ccissuenum,bankname,bankacctnum,bankroutingnum,notes

**Comment by kspearrin** [comment]
@roccolord https://github.com/bitwarden/web/issues/122
