### ISSUE TITLE
[Bug] This organization cannot use attachments.

### ISSUE THREAD

**Issue by dabura667** [bitwarden/core#54]
Trying to share a password with a collection in a free organization from a free account gives me this error even though the password itself does not contain any attachments.

**Comment by kspearrin** [comment]
We have fixed this and are pushing out an update this evening. Thanks.

**Comment by dabura667** [comment]
Thanks

**Comment by kspearrin** [comment]
@dabura667 Can you try now please?

**Comment by kspearrin** [comment]
Make sure you refresh.

**Comment by dabura667** [comment]
@kspearrin Works great!

I'm evaluating bitwarden for possible use with our small company (<20 people) by using it with my wife to share some passwords using free organization and free accounts.

So far I'm seeing a lot of UX bumps and would love to continue giving you feedback, as I think we really need this product to help secure our company.

**Comment by kspearrin** [comment]
@dabura667 Great. You caught us in the middle of a big release where we were still ironing out a few issues. Hopefully things are better now with our hotfix this evening. Feel free to let me know any feedback you have.
