### ISSUE TITLE
[Bug] Organization invitation link fails after redirect

### ISSUE THREAD

**Issue by dabura667** [bitwarden/core#55]
My wife clicked the invitation link on her hotmail webmail portal, which apparently replaces the link's actual href with some tracking nonsense URL that forwards to the given link.

Upon being forwarded to the site, a red error pops up saying invalid link.

Workaround was to copy the link text from the mail body and enter it into a new tab.

**Comment by kspearrin** [comment]
Could you forward me the email from hotmail so I can see what was done to it? Send to hello@bitwarden.com and it will pipe into the support ticket system.

**Comment by dabura667** [comment]
Sent.

She accessed the hotmail webmail from her Safari app on her iPhone 7. The link opened a new tab in Safari that came up with a red invalid link warning even though she had yet to accept it or do anything with it.

I also would suggest the ability to accept organization invites just by logging in. Requiring the email link to be clicked would seem like something that could be missed, but a little popup asking if they want to accept on next login would be easier, especially if the mobile app could send a push notification or something.

**Comment by kspearrin** [comment]
Fixed. Urls were getting double encoded which broke the query string parameters in some cases.

**Comment by dabura667** [comment]
Thanks!

**Comment by meatballz** [comment]
I'm having an issue with this too, except that copy and paste doesn't work for me. I've tried using three different browsers (desktop and mobile). The page immediately redirects to the login page and says "invalid parameters".
