### ISSUE TITLE
Store and fill additional fields

### ISSUE THREAD

**Issue by pannal** [bitwarden/core#58]
For my banking login for example I need more than just a username/password combination.
With lastpass I was able to store additional fields inside the vault for one site.

Can this be implemented in Bitwarden?

**Comment by kspearrin** [comment]
Not currently. Planned for future.

**Comment by elopez** [comment]
Hi, has there been any progress on this front? This feature is the only thing keeping me on Lastpass at the moment. Thanks!

**Comment by kspearrin** [comment]
It is scheduled to be Released soon.

**Comment by kspearrin** [comment]
This is now available: https://blog.bitwarden.com/custom-fields-43db187a1256

**Comment by pannal** [comment]
Works great! Thank you!
