### ISSUE TITLE
Uncheck "Remember me" checkboxes

### ISSUE THREAD

**Issue by Gitoffthelawn** [bitwarden/core#59]
Most login pages include a "Remember me" checkbox.

I am considering trying bitwarden, but it is important that it unchecks these boxes.

Can you implement this?

Related: https://github.com/bitwarden/core/issues/58

**Comment by Dechcaudron** [comment]
As a Premium member, personally I believe this should be the default. Allowing your computer to store your passwords in a likely unsafe environment goes against what I as a user want to achieve with this software.

**Comment by 5nafu** [comment]
@Dechcaudron : Most of the time, the "Remember me" checkbox does not trigger a storage of credentials but rather the storage of a (session) cookie with longer validity. 
You can argue that this might be an undesirable state, but it will not (in any normal implementation) expose your credentials.

On the other Hand: The Browsers have their own Password store which should be switched off. Maybe there is a way for a password manager to disable this. But, as there are some use cases to have a password manager and a browser password store, the plugins should give the user a choice.

**Comment by Gitoffthelawn** [comment]
@kspearrin Will the enhancements for #58 resolve this issue as well?

Any ETA?

**Comment by kspearrin** [comment]
Yes, you can use custom fields to set a checkbox (boolean) value.

**Comment by Gitoffthelawn** [comment]
Thank you!
