### ISSUE TITLE
Why there is no desktop application?

### ISSUE THREAD

**Issue by i-panov** [bitwarden/core#60]
I tried bitwarden and everything would be fine, but it's very sad that there is no desktop application. :( I can not use the password manager without it.The browser extension is rather inconvenient for bitwarden.In addition, passwords are entered not only in the browser, but also in various applications. Please make a desktop application.

**Comment by kspearrin** [comment]
Desktop development will be done in this repo: https://github.com/bitwarden/desktop

You can follow along there. However, development on this has not started yet.

**Comment by jenmarketing** [comment]
Is there any update on the timeline for this?
