### ISSUE TITLE
Docker Container is not available

### ISSUE THREAD

**Issue by RaymondSchnyder** [bitwarden/core#61]
Hello,

The docker container "bitwarden/setup" is not available anymore.
Can u fixxing this

**Comment by kspearrin** [comment]
Yes, this is still a WIP. Announcements to come soon.

**Comment by RaymondSchnyder** [comment]
Okay, thank you very much. because im VERY interested in your application. At the moment im testing it as a replace for lastpass.

**Comment by kspearrin** [comment]
@RaymondSchnyder Please see https://github.com/bitwarden/core/issues/62 for the beta.
