### ISSUE TITLE
No any hint when try to retrieve an incorrect email address

### ISSUE THREAD

**Issue by yfdyh000** [bitwarden/core#67]
When I try to login or retrieve an account (within extension or https://vault.bitwarden.com/#/recover-delete), there is no information to tell me that the account does not exist. The extension says the username or password is incorrect, and no any email send to the email address with send remind or recover.

This may be a security mechanism, but will consume the user's time and patience.

**Comment by kspearrin** [comment]
No plans to change this message. It is meant to be generic.
