### ISSUE TITLE
Can't access service

### ISSUE THREAD

**Issue by quentindemetz** [bitwarden/core#68]
I am resorting to posting here because I can't access the any bitwarden.com subdomain (including FAQ) nor log in to the service... I'm effectively locked out :/

<img width="895" alt="screen shot 2017-09-13 at 08 35 16" src="https://user-images.githubusercontent.com/2451971/30362924-7de1604c-985e-11e7-9477-9fff95c83736.png">

Nothing seems to work...

**Comment by kspearrin** [comment]
@quentindemetz You are unblocked. We had a bug in our browser extension that would send false positives to trip our abuse detection system. A potential fix was added in v1.16.x. Please update and let us know if it happens again.

**Comment by quentindemetz** [comment]
Thanks! I'll let you know if it happens again.
