### ISSUE TITLE
Suggestion for Global Equivalent Domains

### ISSUE THREAD

**Issue by Palf994** [bitwarden/core#69]
The following Wikimedia domains all use the same account information:

mediawiki.org
wikibooks.org
wikidata.org
wikimedia.org
wikinews.org
wikipedia.org
wikiquote.org
wikisource.org
wikiversity.org
wikivoyage.org
wiktionary.org

It would be great if they could be added to the Global Equivalent Domains list.

Cheers

**Comment by kspearrin** [comment]
Thanks. I am hoping to refactor the way we handle equivalent domains at the moment so that users can easily issue additions like this to the database via PRs.

**Comment by Mikaela** [comment]
Based on the title I think I can suggest others here too.

I think **launchpad.net should be equivalent to ubuntu.com** as it uses the same sign-in system.

I don't know if equivalent domains that are accepted globally should be noteworthy, but Ubuntu is one of the most popular Linux distributions and Launchpad.net is their bug tracker and code hoster etc.

**Comment by kspearrin** [comment]
wiki domains added for next release.
