### ISSUE TITLE
Email for Logging In is Case Sensitive

### ISSUE THREAD

**Issue by LIV3N** [bitwarden/core#7]
Created account using email with caps, for example test@GMAIL.com. 

Unable to login with test@GMAIL.com, had to log in as test@gmail.com.

Email authentication should not be case sensitive.

**Comment by joshsleeper** [comment]
I totally agree with @LIV3N.
Email should never be case sensitive.

**Comment by aloisdg** [comment]
I think you will have to replace

```c#
var result = await _signInManager.PasswordSignInAsync(model.Email.ToLower(),
    model.MasterPasswordHash,
    model.Device?.ToDevice());
```
with

```c#
var result = await _signInManager.PasswordSignInAsync(model.Email,
    model.MasterPasswordHash,
    model.Device?.ToDevice());
```

[here](https://github.com/bitwarden/core/blob/af90d75d06e105fef99086222d4b348bbf953d28/src/Api/Controllers/AuthController.cs#L30)

I am not confident enough to make a PR. Maybe with Unit Tests. ;)

**Comment by kspearrin** [comment]
Logging in is not suppose to be case sensitive. I have put things in place to handle this already (at least I thought). What client application are you seeing this in?

**Comment by LIV3N** [comment]
I got the error on web, Chrome, and Android.

If you need any more info, let me know.

**Comment by kspearrin** [comment]
@LIV3N from what client did you do the initial registration from?

**Comment by kspearrin** [comment]
I found the bug. The issue occurred when registering from the web vault. If you currently have an account that is locked up because of this let me know and I can purge it out for you to re-register. Thanks for the report!

fix is here: https://github.com/bitwarden/web/commit/d49d2275d238cbf586bbc7112f793e7fe3fec36c
