### ISSUE TITLE
connect to available mySQL db host

### ISSUE THREAD

**Issue by MosabHD** [bitwarden/core#71]
Hi
I have installed the bitwarden on my machine, however the mssql container is refusing to start due to limited mem.. 
I have a mysql server available on aws, can I make bitwarder use that server instead of creating a container on my machine?

Thanks

**Comment by kspearrin** [comment]
@MosabHD Yes, you would just need to change the connection string endpoint in `./bitwarden/env/global.override.env`

**Comment by MosabHD** [comment]
hi @kspearrin 
thanks for the fast reply

I have found the connection string, but it is a little bit not clear for me to figure what to change exactly
so I will put what I think I should do and please correct me if I am mistaken:

`globalSettings__sqlServer__connectionString="Data Source=<host url>;Initial Catalog=vault;Persist Security Info=False;User ID=<db username>;Password=<password>`

but where do I specify the database name and the port?

**Comment by kspearrin** [comment]
@MosabHD Perhaps this will help: https://www.connectionstrings.com/sql-server/

**Comment by kspearrin** [comment]
`Initial Catalog` is the database name

**Comment by MosabHD** [comment]
Ok thanks @kspearrin

but still when I run the start command it gives me an error because the mssql container keeps restarting. I want that container not to work ever and just keep everything on my db host

**Comment by kspearrin** [comment]
Even if the mssql container does not start all others will still run. You'd need to modify the docker-compose file in "./bitwarden/docker" to remove the mssql container if you do not want to run.

**Comment by MosabHD** [comment]
ok what about updatedb... it is what is causing the error not start command

**Comment by MosabHD** [comment]
I think I have to modify the updateDatabase() function in run.sh.. but what should I do?

**Comment by MosabHD** [comment]
I have opened the website and tried to create an account, but it is throwing an error "An unhandled server error has occurred."

and when I check the database it has no tables... Can I find a log or something to check for error messages?

**Comment by jprostko** [comment]
MySQL isn't the same thing as MSSQL.  I'm pretty sure that Bitwarden only works with Microsoft SQL Server, not MySQL.

**Comment by kspearrin** [comment]
Whoops, yea I missed that. Can't use MySQL.

**Comment by Mart124** [comment]
https://community.bitwarden.com/t/use-other-database-than-mssql/612
