### ISSUE TITLE
Firefox extension fails to log in

### ISSUE THREAD

**Issue by arantius** [bitwarden/core#72]
Regardless of what I type (including the credentials that work at vault.bitwarden.com) into the Firefox extension, I get a "Errors have occurred / An unexpected error has occured." message.  In the browser  console it says:

    14:36:48.547 Possibly unhandled rejection: {"statusCode":0} undefined 1 angular.js:14700:16
    	consoleLog/< moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angular/angular.js:14700:16
    	$ExceptionHandlerProvider/this.$get</< moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angular/angular.js:11142:7
    	exceptionTrack/</< moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angulartics/angulartics.js:428:20
    	processChecks moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angular/angular.js:17079:11
    	$digest moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angular/angular.js:18233:15
    	$evalAsync/< moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angular/angular.js:18462:15
    	completeOutstandingRequest moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angular/angular.js:6362:7
    	Browser/self.defer/timeoutId< moz-extension://95a9da06-6d8f-45bb-bca1-c0a147da1908/lib/angular/angular.js:6642:7

I've un- and re-installed the browser extension with no change.  Version 1.16.1 from AMO.

P.S. I really dislike the experience of clicking the button, moving my mouse way down to the de-emphasized "log in" link, then way back up to the log in form.  Just show the log in form.  Add a "register" link somewhere else if necessary.  Why be hostile to existing users?

**Comment by kspearrin** [comment]
Duplicate. See https://github.com/bitwarden/browser/issues/237
