### ISSUE TITLE
How to execute the image

### ISSUE THREAD

**Issue by sd2labsei** [bitwarden/core#74]
Please tell me i am using Ubuntu platform docker,bitwarden installation has been done.  When i type docker images command it shows me Repository : bitwarden/setup TAG : latest.

Please let me know how can i execute this image and start using the password manager.

**Comment by kspearrin** [comment]
See https://help.bitwarden.com/article/install-on-premise/

**Comment by sd2labsei** [comment]
Hi Team,

I have already gone through this link but the image is not executing..

Gaurav Vedi | Manager IT

gaurav,vedi@squaredsd.com <https://mail.google.com/mail/u/0/#>



SD Squared
+91-9891960302
Unit- 1004, 10th Floor, JMD Megapolis, Sector- 48, Gurgaon-122018, Haryana,
India

**Comment by kspearrin** [comment]
What is the error you are getting then?

**Comment by sd2labsei** [comment]
There is no error when i type ./bitwarden.sh start nothing starts.

Gaurav Vedi | Manager IT

gaurav,vedi@squaredsd.com <https://mail.google.com/mail/u/0/#>



SD Squared
+91-9891960302
Unit- 1004, 10th Floor, JMD Megapolis, Sector- 48, Gurgaon-122018, Haryana,
India

**Comment by kspearrin** [comment]
Please paste/screenshot the output

**Comment by sd2labsei** [comment]
Please find the screen shot attached :

[image: Inline image 1]

Gaurav Vedi | Manager IT

gaurav,vedi@squaredsd.com <https://mail.google.com/mail/u/0/#>



SD Squared
+91-9891960302
Unit- 1004, 10th Floor, JMD Megapolis, Sector- 48, Gurgaon-122018, Haryana,
India

**Comment by kspearrin** [comment]
Nothing was attached. You need to use the GitHub interface to post the screenshot.

**Comment by sd2labsei** [comment]
[image: Inline image 3]

Gaurav Vedi | Manager IT

gaurav,vedi@squaredsd.com <https://mail.google.com/mail/u/0/#>



SD Squared
+91-9891960302
Unit- 1004, 10th Floor, JMD Megapolis, Sector- 48, Gurgaon-122018, Haryana,
India

**Comment by ple103** [comment]
Try again using GitHub not email

**Comment by sd2labsei** [comment]
![image 1](https://user-images.githubusercontent.com/32098623/30859591-fc9b9af0-a2e1-11e7-8820-3acb39f0fa3f.png)

**Comment by sd2labsei** [comment]
![image 2](https://user-images.githubusercontent.com/32098623/30859627-244e5c0e-a2e2-11e7-98e4-4ff77f3a23e5.png)

**Comment by kspearrin** [comment]
I'm guessing you haven't installed yet? what's in your directory? `ls`

**Comment by sd2labsei** [comment]
it's already installed


![image](https://user-images.githubusercontent.com/32098623/30860152-c13863f6-a2e3-11e7-89a4-23820d1e9d19.png)

**Comment by sd2labsei** [comment]
![image](https://user-images.githubusercontent.com/32098623/30860163-d4ec33fa-a2e3-11e7-852b-95b9c2f5ac3b.png)

**Comment by sd2labsei** [comment]
please suggest

**Comment by kspearrin** [comment]
try running:

`docker-compose -f ./bitwarden/docker/docker-compose.yml -f ./bitwarden/docker/docker-compose.linux.yml up`

**Comment by kspearrin** [comment]
also, can we move this discussion to our live chat at https://gitter.im/bitwarden/Lobby please?

**Comment by sd2labsei** [comment]
sure

**Comment by sd2labsei** [comment]
![image](https://user-images.githubusercontent.com/32098623/30864490-64eae73c-a2f1-11e7-8c32-b57aefbadba3.png)

**Comment by sd2labsei** [comment]
installation has been done
still getting the same issue please find the directory details ls
