### ISSUE TITLE
LastPass CSV import doesn't unescape characters (e.g. "&amp;" -> "&")

### ISSUE THREAD

**Issue by tjb0607** [bitwarden/core#76]
Steps to reproduce:
1. Add a password into LastPass with `&` in it
2. Export your password db from LastPass, and import it into BitWarden
3. Observe that the `&` turned into `&amp;` in BitWarden

**Comment by kspearrin** [comment]
This is a LastPass bug, not bitwarden. See docs here https://help.bitwarden.com/article/import-from-lastpass/
