### ISSUE TITLE
Lan synchronization? 

### ISSUE THREAD

**Issue by Ansem93** [bitwarden/core#79]
Hi everyone, there is some way to sync my 2 windows computers and my android phone when they are connected in the same lan?
If it needed I have small Linux server, so I can deploy the cloud in it.
Can I set it up so that it will only work inside my lan and it will not be reachable from the outside?

**Comment by kspearrin** [comment]
Sure. You could deploy a docker instance that runs on your computer and just connect using a local up address.

**Comment by Ansem93** [comment]
Great! So I will be able to use them even if I'm not at home right? My password will be saved on my Android and Windows too?

**Comment by kspearrin** [comment]
Yes, it would just fail to connect to anything while you are not on your home wifi. Essentially acting in "offline mode" which just gives you read-only access.

**Comment by Ansem93** [comment]
Great! Man you really saved me! :D I will try this manager ASAP!
