### ISSUE TITLE
Email templates?

### ISSUE THREAD

**Issue by petervnv** [bitwarden/core#82]
Hi,

I'm experimenting with bitwarden on a self-hosted installation.
I'm using the instructions in the wiki and have it working fine with docker running on Debian.

My question is where can I find the email templates (Razor I believe) to play around with?

Are they hardcoded into the core? Do I need to install and compile from source to be able to change them?

Cheers,
Peter

**Comment by kspearrin** [comment]
They are compiled into the application and are not custmizable at this time.

**Comment by petervnv** [comment]
Thanks for the quick reply.
Is that customization going to be available sometime in the future?

Also, do you have any instructions about compiling from scratch instead of using docker?

**Comment by kspearrin** [comment]
There are no plans to make email templates customizable at this time. Can you please explain your use case?

No. Although it is possible, there is no documented path outside of the Docker deployments. You're on your own at that point.

**Comment by petervnv** [comment]
Sure. I wanted to test out thoroughly the self-hosted installation and customize it as much as possible.
No worries, I'll figure it out.

Thanks
