### ISSUE TITLE
[query] Can I run bitwarden/core with free/libre dependencies?

### ISSUE THREAD

**Issue by kwill** [bitwarden/core#86]
Is it possible to run bitwarden/core with dependencies that are recognised as free/libre software? (This may require, for example, Mono rather than .NET Core and ??? rather than Microsoft SQL Server.)

**Comment by kspearrin** [comment]
.NET Core and MS SQL Express Edition are free to use. No other technologies are supported.

**Comment by kwill** [comment]
To the best of my knowledge those packages are free/gratis but not free/libre. I understand it is seldom feasible to support a wide range of dependencies. Thanks for the confirmation.

**Comment by kspearrin** [comment]
.NET Core is FOSS. SQL Sever is not.

**Comment by kikawala** [comment]
[Joshua Stein](https://github.com/jcs) has released a FLOSS replacement for bitwarden/core.

source: [https://github.com/jcs/bitwarden-ruby](https://github.com/jcs/bitwarden-ruby)
blog post: [https://jcs.org/2017/11/17/bitwarden](https://jcs.org/2017/11/17/bitwarden)
