### ISSUE TITLE
Mail relay.

### ISSUE THREAD

**Issue by kereza** [bitwarden/core#90]
Hello,

We are using Bitwarden hosted on premise.  We are using Postfix for mail server as open relay for internal mails (requires no authentication) . However when setting the hostname and port in:

globalSettings__mail__smtp__host=infra01.prod.***.loc
globalSettings__mail__smtp__port=25

No email are sent. I have checked the postfix log and the mails are not even reaching it. But from the server on which Bitwarden is hosted I am able to telnet on port 25 on Potsfix and send mails via commands.

Can Bitwarden send mails that way?

Regards.

**Comment by kspearrin** [comment]
Right now if you do not provide a username/password it assumes you have not configured correctly and never attempts to send the mail. We just need to remove that requirement.

**Comment by kspearrin** [comment]
Corrected for next release.

https://github.com/bitwarden/core/commit/ce9067a434223a96943eca9df952a63249880b60

**Comment by kspearrin** [comment]
v1.12.1 is now live.

Update: https://help.bitwarden.com/article/updating-on-premise/
