### ISSUE TITLE
Rmembering Multi Form

### ISSUE THREAD

**Issue by christianreiss** [bitwarden/core#91]
Hey folks,

I am using Bitwarden (current, self-hosted) with current Firefox and current bitwarden Plugin. Everything is peachy except for two things:

- Bitwarden does not offer me to save/remember passwords that I am manually typing in to websites. Note: I disabled the native Firefox password management so I will not save locally. 

- Some websites like Banking require multi-input logins (example: https://meine.deutsche-bank.de/trxm/db/, Banking site). It requires 4 fields to login. How would I go about saving such information? Note: I am running an imported KeePass Vault and said password came imported. As I am unable to save new password, see issue above, I was not able to test this with a "fresh" installation.

Cheers and thanks for your support!
-Christian.

**Comment by kspearrin** [comment]
@christianreiss 

1. Make sure your vault is unlocked. It cannot offer to save newly entered passwords if your vault is locked.
2. Use custom fields for these type of logins.

**Comment by christianreiss** [comment]
Holy 💩 you are fast.

Vault is unlocked; not offering to safe. Tried with 2 different accounts on two different systems (Win10, Win7). "Disable Add Login Notification" is unchecked, too.

Regarding custom fields. ugh. I will try to figure that out. :)

-Chris.

**Comment by kspearrin** [comment]
Can you please provide the website that is not saving?

**Comment by christianreiss** [comment]
Actually I could not convince Bitwarden Plugin to save any website whatsovever. Going to try with Chrome now.

**Comment by christianreiss** [comment]
Ah, 

I found the issue. It only offers you to save when there are zero logins saved for a page. This works in all browsers. I somehow assumed that if you have mutliple logins on a given site that subsequent accounts will be offered to be saved, too.

**Comment by kspearrin** [comment]
Well, it should offer to save any login that is not currently in your vault. It does this based on username. Just because a website already has a login in the vault doesn't mean it shouldn't offer to save a new one.

**Comment by christianreiss** [comment]
Mhh,

Nope, it does not do that at all. Tried with a local rocket.chat instance (login). User A is stored and working, Logging in to User B "fails" (ie, login OK, but no offer to save). So I would re-open this, then.

Also The Login Matches any login for any subdomain in the site. Example:

- docs.site.com show possible logins for site.com, files.site.com, vault.site.com etc. This results in "9+" Logins found.

**Comment by christianreiss** [comment]
Add:

This is what I mean what I consider an incorrect match:
1) https://cloud.alpha-labs.net/index.php/s/pmHSZFMkL6aABFT
2) https://cloud.alpha-labs.net/index.php/s/PDMooNnykWijEvn

Thanks for your support! Awesome software & service!

-Chris.

**Comment by kspearrin** [comment]
I just tested this on several sites and I received the save prompt for a new username even when I already had a different one stored in the vault (ex. https://github.com/login). Can you provide me with a website to reproduce this?

**Comment by christianreiss** [comment]
https://cloud.alpha-labs.net/
https://docs.alpha-labs.net/
[+ 30 more under the same domain].

Most annoying is the incorrect matching, as shown in the 2 pictures above.

**Comment by kspearrin** [comment]
I receive save prompts when entering different credentials into these websites. The incorrect matching of credentials is due to base domain matching. See https://github.com/bitwarden/browser/issues/77 for more info on out future solution to that issue.

If you are till having issues with this, please open a more specific issue in the browser extension repo.
