### ISSUE TITLE
Issues with bitwarden on docker Centos 7 64bits

### ISSUE THREAD

**Issue by emillod** [bitwarden/core#92]
Hi all.
I installed Bitwarden on docker. Everything is ok until i try update db or create account, so:
1. After i try to updatedb in CLI './bitwarden.sh updatedb' i have error:
> 1.12.0: Pulling from bitwarden/setup
> Digest: sha256:1d938bc59e1f2d8d5aef71e53d9ba83df5f5f0fa15538914ebe993de3b049d6c
> Status: Image is up to date for bitwarden/setup:1.12.0
> docker: Error response from daemon: Container 71f07eae5897a6c4efbb1cbac57ffb63f28831c086a412e7f4f66966e7fd9ed3 is restarting, wait until the container is running.

2. When i'm trying to create to account i can't because i have error : https://i.imgur.com/s8jFMmT.png

3. I don't have any data to default account, so i need to create new account, right? 
Bitwarden don't have anything like admin account?

**Comment by kspearrin** [comment]
run `docker ps`

**Comment by emillod** [comment]
![01](https://user-images.githubusercontent.com/17282191/31287432-8ef304ec-aac1-11e7-9fa4-31a98700cbcc.PNG)

**Comment by kspearrin** [comment]
Your mssql instance is not running correctly. How much RAM is on this machine?

**Comment by emillod** [comment]
1 GB RAM i think

**Comment by kspearrin** [comment]
That is your problem. Minimum requirements are 3.25 GB of RAM on Linux machines.

**Comment by emillod** [comment]
Ohh shit! G! Thanks for reply :)
