### ISSUE TITLE
Enpass Import does not work with not english csv

### ISSUE THREAD

**Issue by Blauschirm** [bitwarden/core#98]
Hey,
I noticed I had to set the application of Enpass to english to get a csv with english tags to be able to import it to bitwarden. Otherwise it just puts username and password into the notes section.
I don't really know how to fix this elegantly though...
Language that didn't work was German.

**Comment by kspearrin** [comment]
We won't be able to support every language. We'll probably just need to update our docs to say that it needs to be exported in English to work.

**Comment by kspearrin** [comment]
Updated docs for next release.
